[metadata]

[[block]]
key = "f033356e330d50b8"
origin = '''
---
sidebar_position: 2
---
'''
translate = '''
---
sidebar_position: 2
---
'''

[[block]]
key = "7eef1e46e9b5a956"
origin = '''
# Manta M8P v1 硬件功能
'''
translate = '''
# Manta M8P v1 硬件功能
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e4e43b6d7201907d"
origin = '''
## 外观尺寸
'''
translate = '''
## 外观尺寸
'''

[[block]]
key = "fdcb778b02fae499"
origin = '''
:::info[STEP 模型]

Manta M8P v1.0 模型 [BIGTREETECH MANTA M8P V1.0.step](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/3D/BIGTREETECH%20MANTA%20M8P%20V1.0.step)

Manta M8P v1.1 模型 [BIGTREETECH MANTA M8P V1.1.step.zip](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/3D/BIGTREETECH%20MANTA%20M8P%20V1.1.step.zip)

:::
'''
translate = '''
:::info[STEP 模型]

Manta M8P v1.0 模型 [BIGTREETECH MANTA M8P V1.0.step](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/3D/BIGTREETECH%20MANTA%20M8P%20V1.0.step)

Manta M8P v1.1 模型 [BIGTREETECH MANTA M8P V1.1.step.zip](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/3D/BIGTREETECH%20MANTA%20M8P%20V1.1.step.zip)

:::
'''

[[block]]
key = "2ca8f68b0c1ddec8"
origin = '''
<Tabs groupId="m8p-dim">
    <TabItem value="m8p-dim-1" label="正面尺寸" default>
'''
translate = '''
<Tabs groupId="m8p-dim">
    <TabItem value="m8p-dim-1" label="正面尺寸" default>
'''

[[block]]
key = "149aaa4b24f7f9cc"
origin = '''
        <ImageView src={require('./img/M8P_dimensions_1.png').default} width="100%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_dimensions_1.png').default} width="100%"/>
'''

[[block]]
key = "c44693097808f5f4"
origin = '''
    </TabItem>
    <TabItem value="m8p-dim-2" label="反面尺寸">
        <ImageView src={require('./img/M8P_dimensions_2.png').default} width="100%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m8p-dim-2" label="反面尺寸">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_dimensions_2.png').default} width="100%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "a2df1b4a41a65fdc"
origin = '''
## Pinout
'''
translate = '''
## Pinout
'''

[[block]]
key = "81b0d9d1d85b67f0"
origin = '''
:::info[原理图 / Schematic]

Manta M8P v1.0 原理图 [BIGTREETECH MANTA M8P V1.0-SCH.pdf](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/Hardware/BIGTREETECH%20MANTA%20M8P%20V1.0-SCH.pdf)

Manta M8P v1.1 原理图 [BIGTREETECH MANTA M8P V1.1-SCH.pdf](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/Hardware/BIGTREETECH%20MANTA%20M8P%20V1.1-SCH.pdf)

:::
'''
translate = '''
:::info[原理图 / Schematic]

Manta M8P v1.0 原理图 [BIGTREETECH MANTA M8P V1.0-SCH.pdf](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/Hardware/BIGTREETECH%20MANTA%20M8P%20V1.0-SCH.pdf)

Manta M8P v1.1 原理图 [BIGTREETECH MANTA M8P V1.1-SCH.pdf](https://github.com/bigtreetech/Manta-M8P/blob/master/V1.0_V1.1/Hardware/BIGTREETECH%20MANTA%20M8P%20V1.1-SCH.pdf)

:::
'''

[[block]]
key = "0f122f4696756d2b"
origin = '''
<Tabs groupId="m8p-pinout">
    <TabItem value="m8p-pinout-1_1" label="Manta M8P v1.1" default>
'''
translate = '''
<Tabs groupId="m8p-pinout">
    <TabItem value="m8p-pinout-1_1" label="Manta M8P v1.1" default>
'''

[[block]]
key = "e33a9d7bdbe5373c"
origin = '''
        <ImageView src={require('./img/M8P_pinout-v1_1.png').default} width="100%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_pinout-v1_1.png').default} width="100%"/>
'''

[[block]]
key = "d912a575fd5343f2"
origin = '''
    </TabItem>
    <TabItem value="m8p-pinout-1_0" label="Manta M8P v1.0">
        <ImageView src={require('./img/M8P_pinout-v1_0.png').default} width="100%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m8p-pinout-1_0" label="Manta M8P v1.0">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_pinout-v1_0.png').default} width="100%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "84b2585c7f541b60"
origin = '''
:::info[Manta M8P V1.1 增加了功能]

CAN接口（2引脚*2 XH2.54）

USB端口功能选择（UART到USB，USB OTG）

Pi FAN（由GPIO26控制）

FAN4成为2线CNC风扇。

<ImageView src={require('./img/M8P_Add_Func1.png').default} width="80%"/>

:::
'''
translate = '''
:::info[Manta M8P V1.1 增加了功能]

CAN接口（2引脚*2 XH2.54）

USB端口功能选择（UART到USB，USB OTG）

Pi FAN（由GPIO26控制）

FAN4成为2线CNC风扇。

<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_Add_Func1.png').default} width="80%"/>

:::
'''

[[block]]
key = "465a0d3a27e44929"
origin = '''
## 硬件功能配置
'''
translate = '''
## 硬件功能配置
'''

[[block]]
key = "83e4703555823190"
origin = '''
### USB 供电
'''
translate = '''
### USB 供电
'''

[[block]]
key = "2954207cc6fbf80d"
origin = '''
M8P主板通电后，MCU左侧的D32红灯亮起，表示电源正常。电路板中间的VUSB是电源选择端子。只有在使用USB向主板供电或需要通过USB供电时，才需要使用跳线将其短路。
'''
translate = '''
M8P主板通电后，MCU左侧的D32红灯亮起，表示电源正常。电路板中间的VUSB是电源选择端子。只有在使用USB向主板供电或需要通过USB供电时，才需要使用跳线将其短路。
'''

[[block]]
key = "83fb578747fa768d"
origin = '''
<ImageView src={require('./img/M8P_USB_PS.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_USB_PS.png').default} width="80%"/>
'''

[[block]]
key = "88f07a4cd8a5065a"
origin = '''
### 步进电机驱动
'''
translate = '''
### 步进电机驱动
'''

[[block]]
key = "814cfb63cf1d664a"
origin = '''
#### TMC 2208 / TMC 2209 UART 模式
'''
translate = '''
#### TMC 2208 / TMC 2209 UART 模式
'''

[[block]]
key = "584e67ecee2b77e8"
origin = '''
<ImageView src={require('./img/M8P_uart.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_uart.png').default} width="80%"/>
'''

[[block]]
key = "c89d1e811514edc2"
origin = '''
#### TMC 2130 / TMC 5160 SPI 模式
'''
translate = '''
#### TMC 2130 / TMC 5160 SPI 模式
'''

[[block]]
key = "2ec67b4686f3afae"
origin = '''
<ImageView src={require('./img/M8P_spi.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_spi.png').default} width="80%"/>
'''

[[block]]
key = "4b58b74756fe1fc0"
origin = '''
#### TMC Sensorless
'''
translate = '''
#### TMC Sensorless
'''

[[block]]
key = "dbafa5ef54fd0f6d"
origin = '''
<ImageView src={require('./img/M8P_Dri_sensorless.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_Dri_sensorless.png').default} width="80%"/>
'''

[[block]]
key = "5f1ed59124966c81"
origin = '''
#### 仅使用 STEP/DIR 驱动
'''
translate = '''
#### 仅使用 STEP/DIR 驱动
'''

[[block]]
key = "71f1e490d6355393"
origin = '''
A4988 / DRV8825 使用跳线帽短接 MS0-MS2 以调整细分
'''
translate = '''
A4988 / DRV8825 使用跳线帽短接 MS0-MS2 以调整细分
'''

[[block]]
key = "284a5c6d99407546"
origin = '''
:::info[已知问题]
如果使用 `A4988` 或 `DRV8825` 需要短接 `RST` 和 `SLP` 才能正常工作
:::
'''
translate = '''
:::info[已知问题]
如果使用 `A4988` 或 `DRV8825` 需要短接 `RST` 和 `SLP` 才能正常工作
:::
'''

[[block]]
key = "df8f82d0bad953eb"
origin = '''
<ImageView src={require('./img/M8P_Dri_Step.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_Dri_Step.png').default} width="80%"/>
'''

[[block]]
key = "e399c8f991a5a5a8"
origin = '''
### 驱动电压选择
'''
translate = '''
### 驱动电压选择
'''

[[block]]
key = "5c83abb62490d8b7"
origin = '''
<Tabs groupId="m8p-driver-power">
    <TabItem value="m8p-power-24" label="使用 24V 电源" default>
'''
translate = '''
<Tabs groupId="m8p-driver-power">
    <TabItem value="m8p-power-24" label="使用 24V 电源" default>
'''

[[block]]
key = "e90b33b8e1edeb22"
origin = '''
        <ImageView src={require('./img/M8P_driver_24.png').default} width="80%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_driver_24.png').default} width="80%"/>
'''

[[block]]
key = "492a3d68355023ff"
origin = '''
    </TabItem>
    <TabItem value="m8p-power-48" label="使用 48V 电源">
        <ImageView src={require('./img/M8P_driver_48.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m8p-power-48" label="使用 48V 电源">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_driver_48.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "74aa951c0c99de92"
origin = '''
### 核心板安装
'''
translate = '''
### 核心板安装
'''

[[block]]
key = "2a81ae2d93d304f1"
origin = '''
<Tabs groupId="m8p-cm">
    <TabItem value="m8p-cm-rpi" label="使用树莓派 CM4/CM5" default>
'''
translate = '''
<Tabs groupId="m8p-cm">
    <TabItem value="m8p-cm-rpi" label="使用树莓派 CM4/CM5" default>
'''

[[block]]
key = "bbdffb67b8bbef87"
origin = '''
        <ImageView src={require('./img/M8P_cm_rpi.png').default} width="80%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_cm_rpi.png').default} width="80%"/>
'''

[[block]]
key = "19b3bd9716643164"
origin = '''
    </TabItem>
    <TabItem value="m8p-cm-cb" label="使用 CB1/CB2">
        <ImageView src={require('./img/M8P_cm_cb.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m8p-cm-cb" label="使用 CB1/CB2">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_cm_cb.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "42a1c5868cbd4eef"
origin = '''
### 风扇电压选择
'''
translate = '''
### 风扇电压选择
'''

[[block]]
key = "6349d2e529592521"
origin = '''
使用跳线帽配置输出电压
'''
translate = '''
使用跳线帽配置输出电压
'''

[[block]]
key = "0295af4d22b63c7b"
origin = '''
:::warning

在选择电压之前，请确认风扇的工作电压

:::
'''
translate = '''
:::warning

在选择电压之前，请确认风扇的工作电压

:::
'''

[[block]]
key = "9a965ef8d091a249"
origin = '''
<ImageView src={require('./img/M8P_fan.png').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_fan.png').default} width="60%"/>
'''

[[block]]
key = "8269b6259653cf1c"
origin = '''
### 4Pin PWM 风扇接线
'''
translate = '''
### 4Pin PWM 风扇接线
'''

[[block]]
key = "e12ac38bbedd06b9"
origin = '''
<ImageView src={require('./img/M8P_4_pin_pwm.png').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_4_pin_pwm.png').default} width="60%"/>
'''

[[block]]
key = "4fbb9a4c823aff32"
origin = '''
### 100K NTC 或 PT1000 设置
'''
translate = '''
### 100K NTC 或 PT1000 设置
'''

[[block]]
key = "a0fa71ff2f9cc1f5"
origin = '''
当使用100K NTC热敏电阻时，无需插入跳线帽 `TH0` `TH1` `TH2` `TH3` 的上拉电阻为 4.7K 0.1%。
'''
translate = '''
当使用100K NTC热敏电阻时，无需插入跳线帽 `TH0` `TH1` `TH2` `TH3` 的上拉电阻为 4.7K 0.1%。
'''

[[block]]
key = "5bb3ee4623ca58c3"
origin = '''
:::info

使用PT1000时，需要插入 PT 的跳线帽。此时 `TH0` `TH1` `TH2` `TH3` 的上拉电阻为2.2K。

这样读取的温度精度将远不如MAX31865读取的精度

<ImageView src={require('./img/M8P_pt1000.png').default} width="30%"/>

:::
'''
translate = '''
:::info

使用PT1000时，需要插入 PT 的跳线帽。此时 `TH0` `TH1` `TH2` `TH3` 的上拉电阻为2.2K。

这样读取的温度精度将远不如MAX31865读取的精度

<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_pt1000.png').default} width="30%"/>

:::
'''

[[block]]
key = "055af79b3798a6be"
origin = '''
### BLTouch
'''
translate = '''
### BLTouch
'''

[[block]]
key = "bb171e09f96be880"
origin = '''
<ImageView src={require('./img/M8P_BLTouch.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_BLTouch.png').default} width="80%"/>
'''

[[block]]
key = "1edc2ff103b2910c"
origin = '''
### 接近开关接线
'''
translate = '''
### 接近开关接线
'''

[[block]]
key = "1313296b1a8d3327"
origin = '''
<Tabs groupId="m8p-proximity">
    <TabItem value="m8p-proximity-npn" label="NPN 接近开关" default>
'''
translate = '''
<Tabs groupId="m8p-proximity">
    <TabItem value="m8p-proximity-npn" label="NPN 接近开关" default>
'''

[[block]]
key = "4606370f6d79313f"
origin = '''
        <ImageView src={require('./img/M8P_Proximity_npn.png').default} width="80%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_Proximity_npn.png').default} width="80%"/>
'''

[[block]]
key = "f0c92b137899e8c7"
origin = '''
    </TabItem>
    <TabItem value="m8p-proximity-pnp" label="PNP 接近开关">
        <ImageView src={require('./img/M8P_Proximity_pnp.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m8p-proximity-pnp" label="PNP 接近开关">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_Proximity_pnp.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "e05ee8fddc1f9427"
origin = '''
### ADXL345 加速计
'''
translate = '''
### ADXL345 加速计
'''

[[block]]
key = "f32c2af65702ccdd"
origin = '''
:::info

使用加速度计参考 Klipper [Measuring_Resonances](https://www.klipper3d.org/Measuring_Resonances.html)

Manta M8P ADXL 345 配置文件参考 [Manta M8P ADXL 配置文件](./manta-m8p-v1-firmware.md#adxl345-配置文件参考)

:::
'''
translate = '''
:::info

使用加速度计参考 Klipper [Measuring_Resonances](https://www.klipper3d.org/Measuring_Resonances.html)

Manta M8P ADXL 345 配置文件参考 [Manta M8P ADXL 配置文件](./manta-m8p-v1-firmware.md#adxl345-配置文件参考)

:::
'''

[[block]]
key = "3d98b0d92471b1ae"
origin = '''
<ImageView src={require('./img/M8P_ADXL345.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_ADXL345.png').default} width="80%"/>
'''

[[block]]
key = "c5ba87e7a93379bf"
origin = '''
### Neopixel 
'''
translate = '''
### Neopixel 
'''

[[block]]
key = "cf101be16a902bc3"
origin = '''
<ImageView src={require('./img/M8P_RGB.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_RGB.png').default} width="80%"/>
'''

[[block]]
key = "49f4d5cac4d45c44"
origin = '''
### 断料检测
'''
translate = '''
### 断料检测
'''

[[block]]
key = "8d12ad552a844a0f"
origin = '''
<ImageView src={require('./img/M8P_Filament.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_Filament.png').default} width="80%"/>
'''

[[block]]
key = "9e8249f5c2f599ab"
origin = '''
### 40 Pin GPIO
'''
translate = '''
### 40 Pin GPIO
'''

[[block]]
key = "6e179ce6671a49dc"
origin = '''
<ImageView src={require('./img/M8P_40_Pin.png').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_40_Pin.png').default} width="60%"/>
'''

[[block]]
key = "96fd696e3ab6643b"
origin = '''
### DSI/CSI 接线
'''
translate = '''
### DSI/CSI 接线
'''

[[block]]
key = "3997ea819febd8a2"
origin = '''
:::info

DSI/CSI 需要核心板硬件支持

:::
'''
translate = '''
:::info

DSI/CSI 需要核心板硬件支持

:::
'''

[[block]]
key = "1bf43f25adaeb769"
origin = '''
<ImageView src={require('./img/M8P_DSI.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/M8P_DSI.png').default} width="80%"/>
'''
