[metadata]

[[block]]
key = "ed4371df8041fbd1"
origin = '''
---
sidebar_position: 1
description: Manta M8P V1 一体打印板
---
'''
translate = '''
---
sidebar_position: 1
description: Manta M8P V1 一体打印板
---
'''

[[block]]
key = "646039d55b9e2b6a"
origin = '''
# Manta M8P V1
'''
translate = '''
# Manta M8P V1
'''

[[block]]
key = "df079ecf04a03abd"
origin = '''
Manta M8P 板说明文档
'''
translate = '''
Manta M8P 板说明文档
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "49b2bf7f593d1f7c"
origin = '''
import DocCardList from '@theme/DocCardList';
'''
translate = '''
import DocCardList from '@theme/DocCardList';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "5dde13dabc406e59"
origin = '''
<div class="div-table">

<ImageView 
    src={require('./img/m8p-v1-main.png').default} 
    width="45%" class="right-image"
/>
'''
translate = '''
<div class="div-table">

<ImageView 
    src={require('@site/docs/board-docs/manta-series/manta-m8p-v1/img/m8p-v1-main.png').default} 
    width="45%" class="right-image"
/>
'''

[[block]]
key = "61695731d894e982"
origin = '''
## 简介
'''
translate = '''
## 简介
'''

[[block]]
key = "2234ba970e098ce0"
origin = '''
M8P 亦是在解决 Klipper 接线过于复杂的问题。一体化的 Klipper 电路控制。并且保留 Octopus 系列的部分功能，使得拓展性得到提升。
'''
translate = '''
M8P 亦是在解决 Klipper 接线过于复杂的问题。一体化的 Klipper 电路控制。并且保留 Octopus 系列的部分功能，使得拓展性得到提升。
'''

[[block]]
key = "cc93f65bfb52fa05"
origin = '''
## 硬件规格
'''
translate = '''
## 硬件规格
'''

[[block]]
key = "95ea83182068d246"
origin = '''
| Manta M8P v1 | Specification                      |
| ------------ | ---------------------------------- |
| MCU          | ARM Cortex-M0+ STM32G0B1VET6 64MHz |
| 尺寸         | $170mm \times 102.7mm$             |
'''
translate = '''
| Manta M8P v1 | Specification                      |
| ------------ | ---------------------------------- |
| MCU          | ARM Cortex-M0+ STM32G0B1VET6 64MHz |
| 尺寸         | $170mm \times 102.7mm$             |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "d3ac9811ffbf8210"
origin = '''
<DocCardList />
'''
translate = '''
<DocCardList />
'''
