[metadata]

[[block]]
key = "0dfe55a8eeac2c18"
origin = '''
---
sidebar_position: 2
description: Pad5 V2 硬件功能配置
---
'''
translate = '''
---
sidebar_position: 2
description: Pad5 V2.0 Hardware Configuration
---
'''

[[block]]
key = "d428a51f23e0c19d"
origin = '''
# Pad5 V2 硬件
'''
translate = '''
# Pad5 V2 Hardware
'''

[[block]]
key = "28af09579d62ebe0"
origin = '''
## 外设接口
'''
translate = '''
## Peripheral Interfaces
'''

[[block]]
key = "69e561fe88834e17"
origin = '''
### 接口示意图
'''
translate = '''
### Interface Diagram
'''

[[block]]
key = "b7932a87fc9a8cf5"
origin = '''
<ImageView src={require('./img/interface.webp').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/interface.webp').default} width="60%"/>
'''

[[block]]
key = "ad62aede29da5f17"
origin = '''
### 功能概要
'''
translate = '''
### Feature Overview
'''

[[block]]
key = "8468694c7ca4df96"
origin = '''
搭配各个核心板对应拥有的功能如下图所示，`√`代表支持，`×`代表不支持。
'''
translate = '''
The table below summarizes the features supported by each compatible core board: `√`= Supported, `×`= Not supported.
'''

[[block]]
key = "3c60a6f98368b1db"
origin = '''
<ImageView src={require('./img/functional.webp').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/functional.webp').default} width="60%"/>
'''

[[block]]
key = "1089bab5f55a4f09"
origin = '''
## 功能介绍
'''
translate = '''
## Feature Details
'''

[[block]]
key = "9e8249f5c2f599ab"
origin = '''
### 40 Pin GPIO
'''
translate = '''
### 40 Pin GPIO
'''

[[block]]
key = "bdd28e29d5b29874"
origin = '''
搭配各个核心板对应的 40Pin GPIO 如下图:
'''
translate = '''
The diagram shows the GPIO pinout mapping for different core boards on the 40-pin header.
'''

[[block]]
key = "1e7a63897fc527e3"
origin = '''
<ImageView src={require('./img/40pin-gpio.webp').default} width="100%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/40pin-gpio.webp').default} width="100%"/>
'''

[[block]]
key = "696d9b14fbe44e8c"
origin = '''
### CAN接口
'''
translate = '''
### CAN Interface
'''

[[block]]
key = "75ae6b09eb7e4ff9"
origin = '''
本产品搭配CM5/CM4使用时，支持CAN通讯，实现方式是由SOC的SPI信号转换为CAN信号。
'''
translate = '''
The Pad5 supports CAN communication when used with CM5 or CM4.This is achieved by converting the SoC’s SPI signals to CAN signals.
'''

[[block]]
key = "5e4895522b9003e0"
origin = '''
SPI信号为：CS-GPIO8，MISO-GPIO9，MOSI-GPIO10，SCK-GPIO11，INT-GPIO24
'''
translate = '''
SPI to CAN Mapping: CS-GPIO8，MISO-GPIO9，MOSI-GPIO10，SCK-GPIO11，INT-GPIO24
'''

[[block]]
key = "65f3e05f077ab0ba"
origin = '''
### 风扇接口
'''
translate = '''
### Fan Interface
'''

[[block]]
key = "f58a5a91e96690f9"
origin = '''
本产品搭配CM5使用时，支持4线风扇进行主动散热，插座型号是ZX-SH1.0 4P接口线序如下图：
'''
translate = '''
The Pad5 supports a 4-wire fan for active cooling when used with CM5. Connector type: ZX-SH1.0 4P
'''

[[block]]
key = "cc91201f9a59a034"
origin = '''
<ImageView src={require('./img/fan.webp').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/fan.webp').default} width="60%"/>
'''

[[block]]
key = "21a0d4f455762173"
origin = '''
### RTC电路
'''
translate = '''
### RTC Circuit
'''

[[block]]
key = "0f3806c33b27ce5d"
origin = '''
本产品搭配CM5/CM4/CB2使用时，支持RTC电路，实现方式是由SOC的I2C驱动PCF8563时钟芯片。
'''
translate = '''
The Pad5 provides an RTC circuit when used with CM5, CM4, or CB2, using the SoC’s I2C interface to control a PCF8563 clock chip.
'''

[[block]]
key = "309ae76f2cf9ca40"
origin = '''
:::info

使用此功能之前必须确保板子已安装CR1220 3V的纽扣电池，安装时需要带LOGO的一面朝上。推荐品牌：Lithium Cell，Panasonic等等。

:::
'''
translate = '''
:::info

Before using the RTC, install a CR1220 3V coin cell battery with the logo side facing up; recommended brands include Panasonic, Lithium Cell, and similar.

:::
'''

[[block]]
key = "e28e371013563cf0"
origin = '''
### MIPI接口
'''
translate = '''
### MIPI Interfaces
'''

[[block]]
key = "b4ae64ad8c029bad"
origin = '''
本产品搭配CM5/CM4/CB2使用时，支持MIPI-DSI（DSI）和MIPI-CSI（CAM）接口。其中搭配CM5使用时，两路MIPI接口可以混合使用，即：DPHY0和DPHY1可作为DSI接口使用，也可作为CSI接口使用；搭配CM4和CB2使用时，CAM接口仅可接摄像头，DSI接口仅可接DSI屏幕使用。
'''
translate = '''
The Pad5 supports MIPI-DSI (display) and MIPI-CSI (camera) when used with CM5, CM4, or CB2. On the CM5, both MIPI interfaces can be used interchangeably, with DPHY0 and DPHY1 functioning as either DSI or CSI. On the CM4 and CB2, the CSI interface connects only to a camera, while the DSI interface connects only to a DSI display.
'''

[[block]]
key = "5c5ed908588577a4"
origin = '''
:::info

连接摄像头或者屏幕时，需要检查使用的线是对应的，不可将摄像头的线用于接屏幕，也不可将屏幕的线用于接摄像头；接线时，注意查看金手指对应金手指触点插入，插入完毕后扣紧锁扣。

:::
'''
translate = '''
:::info

Use the correct cable for each device—do not use a camera cable for the display or vice versa—and ensure the gold fingers are properly aligned with the connector and the latch is secured.

:::
'''

[[block]]
key = "5890f7d7827e6471"
origin = '''
DSI线材：
'''
translate = '''
DSI Cable:
'''

[[block]]
key = "77c2169bd194b302"
origin = '''
<ImageView src={require('./img/mipi-dsi.webp').default} width="45%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/mipi-dsi.webp').default} width="45%"/>
'''

[[block]]
key = "211d11b772858567"
origin = '''
CSI线材：
'''
translate = '''
CSI Cable：
'''

[[block]]
key = "7147038047fee510"
origin = '''
<ImageView src={require('./img/mipi-csi.webp').default} width="45%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/mipi-csi.webp').default} width="45%"/>
'''

[[block]]
key = "de87ed8e127069a0"
origin = '''
线序：
'''
translate = '''
Pin Sequence:
'''

[[block]]
key = "165a029f3c881ec7"
origin = '''
<ImageView src={require('./img/mipi.webp').default} width="45%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/mipi.webp').default} width="45%"/>
'''

[[block]]
key = "91d885c7dbb6e766"
origin = '''
### 按键
'''
translate = '''
### Buttons
'''

[[block]]
key = "8b4f46411262e184"
origin = '''
<ImageView src={require('./img/button.webp').default} width="60%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/iot-series/iot-pad5-v2/img/button.webp').default} width="60%"/>
'''

[[block]]
key = "91582c5f264a13ee"
origin = '''
BK+: 增加背光亮度，范围为0~100%，每次点击增加1%，长按按钮可快速调整亮度
'''
translate = '''
BK+: Increase backlight brightness (0–100%). Each click increases by 1%; long press adjusts faster.
'''

[[block]]
key = "25ca0480b73d6711"
origin = '''
Rotate: 显示方向旋转180°
'''
translate = '''
Rotate: Rotate display 180°.
'''

[[block]]
key = "0d50e21a615bf2b6"
origin = '''
BK-: 降低背光亮度，范围为0~100%，每次点击降低1%，长按按钮可快速调整亮度
'''
translate = '''
BK-: Decrease backlight brightness (0–100%). Each click decreases by 1%; long press adjusts faster.
'''

[[block]]
key = "af61c1c65aa1258d"
origin = '''
ON/OFF: 电源开关按键（仅支持搭配Raspberry Pi CM5时使用）
'''
translate = '''
ON/OFF: Power switch (supported only with Raspberry Pi CM5).
'''
