[metadata]

[[block]]
key = "78d04f42aac2c182"
origin = '''
---
sidebar_position: 10
---
'''
translate = '''
---
sidebar_position: 10
---
'''

[[block]]
key = "16fa2719542cbf73"
origin = '''
# EBB 系列固件 (STM32G0B1)
'''
translate = '''
# EBB Series Firmware (STM32G0B1)
'''

[[block]]
key = "bc5e3ec9c4f2134f"
origin = '''
使用 `STM32G0B1` MCU 的 EBB
'''
translate = '''
EBB using the `STM32G0B1` MCU
'''

[[block]]
key = "9debc9a58b6d331b"
origin = '''
## 构建固件
'''
translate = '''
## Build Firmware
'''

[[block]]
key = "b58c7f3c437b6f83"
origin = '''
使用 ssh 连接到 Klipper Host. 然后使用以下命令进入 Klipper 目录。并且使用 `make menuconfig` 配置固件。
'''
translate = '''
Use SSH to connect to the Klipper Host. Then use the following command to enter the Klipper directory, and use `make menuconfig` to configure the firmware.
'''

[[block]]
key = "656b8b743b9fd7b4"
origin = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''
translate = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''

[[block]]
key = "48be041f69080a61"
origin = '''
然后按照以下选项构建使用 `STM32G0B1` 为 `MCU` 的 `EBB` 固件
'''
translate = '''
Then build the `EBB` firmware using `STM32G0B1` as the `MCU` according to the following options.
'''

[[block]]
key = "cded6edcd44a0d4b"
origin = '''
<ImageView
    src={require('./img/ebb-g0b1-make-can.png').default}
    alt="EBB with G0B1 build config"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/board-docs/ebb-series/img/ebb-g0b1-make-can.png').default}
    alt="EBB with G0B1 build config"
/>
'''

[[block]]
key = "8774d602a438d5ac"
origin = '''
当配置完成使用 `q` 来退出。使用 `y` 来保存编译选项。
'''
translate = '''
After the configuration is complete, use `q` to exit. Use `y` to save the compilation options.
'''

[[block]]
key = "b29b749495956614"
origin = '''
然后使用 `make` 命令来开始编译 Klipper 固件
'''
translate = '''
Then use the `make` command to start compiling the Klipper firmware.
'''

[[block]]
key = "5b81e604caf35eea"
origin = '''
``` shell
make
```
'''
translate = '''
``` shell
make
```
'''

[[block]]
key = "6479f7c4b55cff4a"
origin = '''
## 写入固件
'''
translate = '''
## Flash Firmware
'''

[[block]]
key = "2e0a78c3b6896ca8"
origin = '''
:::note[USB 供电]
如果你在写入固件的时候使用 USB Type-C 接口进行供电。`VUSB` 跳线需要接上。
:::
'''
translate = '''
:::note[USB Power Supply]
If you use the USB Type-C interface for power supply when flashing the firmware, the `VUSB` jumper needs to be connected.
:::
'''

[[block]]
key = "f64725a427045898"
origin = '''
:::warning[已知问题]
如果你使用的 EBB 为 `EBB 36 v1.1` 或者 `EBB 42 v1.1`。热端加热输出引脚 `PA2` 会在进入 `DFU` 模式的时候启用。
:::
'''
translate = '''
:::warning[Known Issue]
If the EBB you are using is `EBB 36 v1.1` or `EBB 42 v1.1`, the hotend heater output pin `PA2` will be enabled when entering `DFU` mode.
:::
'''

[[block]]
key = "90d06b16cf5eb1ae"
origin = '''
当使用 Klipper 固件编译完成后。使用 USB Type-C 连接线连接到 Klipper Host 上。
'''
translate = '''
After the Klipper firmware compilation is complete, use a USB Type-C cable to connect to the Klipper Host.
'''

[[block]]
key = "9d495449d22b8a71"
origin = '''
然后按住 `EBB` 的 `boot` 按钮。然后按一下 `reset` 然后松开 `boot` 按钮进入 `DFU` 模式。
'''
translate = '''
Then press and hold the `boot` button on the `EBB`. Then press the `reset` button once and release the `boot` button to enter `DFU` mode.
'''

[[block]]
key = "4f3222dbd05ea982"
origin = '''
然后可以使用 `lsusb` 命令来确认 `EBB` 是否在 `DFU` 模式中。
'''
translate = '''
Then you can use the `lsusb` command to confirm whether the `EBB` is in `DFU` mode.
'''

[[block]]
key = "6bc3022426bddfe1"
origin = '''
当确认 EBB 在 DFU 模式中后。可以使用以下命令来写入固件。
'''
translate = '''
After confirming that the EBB is in DFU mode, you can use the following command to flash the firmware.
'''

[[block]]
key = "07f5dba4134ca463"
origin = '''
``` shell
make flash FLASH_DEVICE=0483:df11
```
'''
translate = '''
``` shell
make flash FLASH_DEVICE=0483:df11
```
'''
