[metadata]

[[block]]
key = "8a95ac5770f23abd"
origin = '''
---
sidebar_position: 3
description: EZ 5160 T Plus 软件配置
---
'''
translate = '''
---
sidebar_position: 3
description: EZ 5160 T Plus 软件配置
---
'''

[[block]]
key = "1a5efb2057f408bc"
origin = '''
# TMC 5160 T Plus 软件
'''
translate = '''
# TMC 5160 T Plus 软件
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "97a654915a067474"
origin = '''
## Klipper 配置文件参考
'''
translate = '''
## Klipper 配置文件参考
'''

[[block]]
key = "023cbadae34d0f24"
origin = '''
```klipper_cfg title="printer.cfg"
[tmc5160 stepper_x]
cs_pin: PD2
spi_software_sclk_pin: PC6
spi_software_mosi_pin: PC8
spi_software_miso_pin: PC7
diag1_pin: PF3
run_current: 0.8
sense_resistor: 0.022
interpolate: False
stealthchop_threshold: 0
driver_SGT: 0
```
'''
translate = '''
```klipper_cfg title="printer.cfg"
[tmc5160 stepper_x]
cs_pin: PD2
spi_software_sclk_pin: PC6
spi_software_mosi_pin: PC8
spi_software_miso_pin: PC7
diag1_pin: PF3
run_current: 0.8
sense_resistor: 0.022
interpolate: False
stealthchop_threshold: 0
driver_SGT: 0
```
'''

[[block]]
key = "83c4659b19c5beab"
origin = '''
## Marlin 配置
'''
translate = '''
## Marlin 配置
'''

[[block]]
key = "f154c9d58628f783"
origin = '''
:::info[Marlin 最低版本]
只有 Marlin 2.0 及更高版本的固件支持 TMC5160 的 SPI 模式
:::
'''
translate = '''
:::info[Marlin 最低版本]
只有 Marlin 2.0 及更高版本的固件支持 TMC5160 的 SPI 模式
:::
'''
