[metadata]

[[block]]
key = "4166138484be8f6a"
origin = '''
---
sidebar_position: 2
description: EZ 5160 T Plus 硬件
---
'''
translate = '''
---
sidebar_position: 2
description: EZ 5160 T Plus 硬件
---
'''

[[block]]
key = "80e497990bb805f1"
origin = '''
# TMC 5160 T Plus 硬件
'''
translate = '''
# TMC 5160 T Plus 硬件
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e106c153eb196b41"
origin = '''
## 模型下载
'''
translate = '''
## 模型下载
'''

[[block]]
key = "dbae5bffed432d31"
origin = '''
:::info[3D 参考文件]

TMC 5160 T Plus 建模参考文件 [bigtreetech/BIGTREETECH-Stepper-Motor-Driver/TMC5160T Plus/3D](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/tree/master/TMC5160T%20Plus/3D)

:::
'''
translate = '''
:::info[3D 参考文件]

TMC 5160 T Plus 建模参考文件 [bigtreetech/BIGTREETECH-Stepper-Motor-Driver/TMC5160T Plus/3D](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/tree/master/TMC5160T%20Plus/3D)

:::
'''

[[block]]
key = "0d822d8017660e45"
origin = '''
## 接口和功能
'''
translate = '''
## 接口和功能
'''

[[block]]
key = "dad521f5e3fb1cdc"
origin = '''
<ImageView
    src={require('./img/TMC5160TPlus_Pin.png').default}
    alt="" width="60%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160-t-plus/img/TMC5160TPlus_Pin.png').default}
    alt="" width="60%"
/>
'''

[[block]]
key = "530159d6e91bb510"
origin = '''
## 接口介绍
'''
translate = '''
## 接口介绍
'''

[[block]]
key = "20f53a36852fff37"
origin = '''
### 使用标准驱动接口
'''
translate = '''
### 使用标准驱动接口
'''

[[block]]
key = "59aee75c1ceabcac"
origin = '''
:::warning
TMC 驱动转换模块只支持 24V
:::
'''
translate = '''
:::warning
TMC 驱动转换模块只支持 24V
:::
'''

[[block]]
key = "1fbc2518b38b27e2"
origin = '''
<ImageView
    src={require('./img/TMC5160TPlus_Ins1.png').default}
    alt="" width="60%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160-t-plus/img/TMC5160TPlus_Ins1.png').default}
    alt="" width="60%"
/>
'''

[[block]]
key = "4d1b566bde29dbdf"
origin = '''
### 使用 EZ 驱动接口
'''
translate = '''
### 使用 EZ 驱动接口
'''

[[block]]
key = "5bf5beec2f7a26af"
origin = '''
:::warning
EZ 驱动转换模块只支持 24V
:::
'''
translate = '''
:::warning
EZ 驱动转换模块只支持 24V
:::
'''

[[block]]
key = "538b94b12d0146f7"
origin = '''
<ImageView
    src={require('./img/TMC5160TPlus_Ins2.png').default}
    alt="" width="60%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160-t-plus/img/TMC5160TPlus_Ins2.png').default}
    alt="" width="60%"
/>
'''
