[metadata]

[[block]]
key = "78d04f42aac2c182"
origin = '''
---
sidebar_position: 10
---
'''
translate = '''
---
sidebar_position: 10
---
'''

[[block]]
key = "01e89ade69667e07"
origin = '''
# Octopus 系列固件 (STM32F446)
'''
translate = '''
# Octopus 系列固件 (STM32F446)
'''

[[block]]
key = "a0f6afabf1eecfab"
origin = '''
使用 `STM32F446` MCU 的 Octopus 
'''
translate = '''
使用 `STM32F446` MCU 的 Octopus 
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "9debc9a58b6d331b"
origin = '''
## 构建固件
'''
translate = '''
## 构建固件
'''

[[block]]
key = "b58c7f3c437b6f83"
origin = '''
使用 ssh 连接到 Klipper Host. 然后使用以下命令进入 Klipper 目录。并且使用 `make menuconfig` 配置固件。
'''
translate = '''
使用 ssh 连接到 Klipper Host. 然后使用以下命令进入 Klipper 目录。并且使用 `make menuconfig` 配置固件。
'''

[[block]]
key = "656b8b743b9fd7b4"
origin = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''
translate = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''

[[block]]
key = "6323cb45f20056b1"
origin = '''
<Tabs groupId="octopus-make-connect">
    <TabItem value="bridge" label="CAN 桥接固件" default>
'''
translate = '''
<Tabs groupId="octopus-make-connect">
    <TabItem value="bridge" label="CAN 桥接固件" default>
'''

[[block]]
key = "deba95d125edfa5f"
origin = '''
        按照以下选项构建使用 `STM32F446` 为 `MCU` 的 `Octopus` CAN 桥接固件
        <ImageView
            src={require('./img/octopus-f446-make-bridge.png').default}
            alt="octopus with h723 bridge"
        />
    </TabItem>
    <TabItem value="usb" label="USB 串口固件">
        按照以下选项构建使用 `STM32F446` 为 `MCU` 的 `Octopus` USB 串口固件
        <ImageView
            src={require('./img/octopus-f446-make-usb.png').default}
            alt="octopus with h723 usb"
        />
    </TabItem>
</Tabs>
'''
translate = '''
        按照以下选项构建使用 `STM32F446` 为 `MCU` 的 `Octopus` CAN 桥接固件
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/img/octopus-f446-make-bridge.png').default}
            alt="octopus with h723 bridge"
        />
    </TabItem>
    <TabItem value="usb" label="USB 串口固件">
        按照以下选项构建使用 `STM32F446` 为 `MCU` 的 `Octopus` USB 串口固件
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/img/octopus-f446-make-usb.png').default}
            alt="octopus with h723 usb"
        />
    </TabItem>
</Tabs>
'''

[[block]]
key = "8774d602a438d5ac"
origin = '''
当配置完成使用 `q` 来退出。使用 `y` 来保存编译选项。
'''
translate = '''
当配置完成使用 `q` 来退出。使用 `y` 来保存编译选项。
'''

[[block]]
key = "b29b749495956614"
origin = '''
然后使用 `make` 命令来开始编译 Klipper 固件
'''
translate = '''
然后使用 `make` 命令来开始编译 Klipper 固件
'''

[[block]]
key = "5b81e604caf35eea"
origin = '''
``` shell
make
```
'''
translate = '''
``` shell
make
```
'''

[[block]]
key = "6479f7c4b55cff4a"
origin = '''
## 写入固件
'''
translate = '''
## 写入固件
'''

[[block]]
key = "2e0a78c3b6896ca8"
origin = '''
:::note[USB 供电]
如果你在写入固件的时候使用 USB Type-C 接口进行供电。`VUSB` 跳线需要接上。
:::
'''
translate = '''
:::note[USB 供电]
如果你在写入固件的时候使用 USB Type-C 接口进行供电。`VUSB` 跳线需要接上。
:::
'''

[[block]]
key = "90d06b16cf5eb1ae"
origin = '''
当使用 Klipper 固件编译完成后。使用 USB Type-C 连接线连接到 Klipper Host 上。
'''
translate = '''
当使用 Klipper 固件编译完成后。使用 USB Type-C 连接线连接到 Klipper Host 上。
'''

[[block]]
key = "58e9503929b62914"
origin = '''
然后按住 `Octopus` 的 `boot` 按钮。然后按一下 `reset` 然后松开 `boot` 按钮进入 `DFU` 模式。
'''
translate = '''
然后按住 `Octopus` 的 `boot` 按钮。然后按一下 `reset` 然后松开 `boot` 按钮进入 `DFU` 模式。
'''

[[block]]
key = "3830090637c9a47c"
origin = '''
然后可以使用 `lsusb` 命令来确认 `Octopus` 是否在 `DFU` 模式中。
'''
translate = '''
然后可以使用 `lsusb` 命令来确认 `Octopus` 是否在 `DFU` 模式中。
'''

[[block]]
key = "f3ef6a155a9769a7"
origin = '''
当确认 Octopus 在 DFU 模式中后。可以使用以下命令来写入固件。
'''
translate = '''
当确认 Octopus 在 DFU 模式中后。可以使用以下命令来写入固件。
'''

[[block]]
key = "07f5dba4134ca463"
origin = '''
``` shell
make flash FLASH_DEVICE=0483:df11
```
'''
translate = '''
``` shell
make flash FLASH_DEVICE=0483:df11
```
'''
