[metadata]

[[block]]
key = "eea9eb093724828e"
origin = '''
---
sidebar_position: 1
description: MMB CAN V1.0 简介
---
'''
translate = '''
---
sidebar_position: 1
description: MMB CAN V1.0 简介
---
'''

[[block]]
key = "aef331608b9d9890"
origin = '''
# MMB CAN V1.0 简介
'''
translate = '''
# MMB CAN V1.0 简介
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''
