[metadata]

[[block]]
key = "0a9ea62f33b073e2"
origin = '''
---
sidebar_position: 1
description: MMB CAN V1.0 硬件功能
---
'''
translate = '''
---
sidebar_position: 1
description: MMB CAN V1.0 Hardware Features
---
'''

[[block]]
key = "6c4f261d1cf413b3"
origin = '''
# MMB CAN V1.0 硬件功能
'''
translate = '''
# MMB CAN V1.0 Hardware Features
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "744a1a9d0f69411c"
origin = '''
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
'''
translate = '''
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e4e43b6d7201907d"
origin = '''
## 外观尺寸
'''
translate = '''
## Dimensions
'''

[[block]]
key = "ec533d6811cc3a0f"
origin = '''
<ImageView src={require('./img/mmb-can-dimension.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-dimension.webp').default} />
'''

[[block]]
key = "1a8680c17a3eb80b"
origin = '''
:::tip[3D 参考文件]

MMB CAN V1.0 模型 [bigtreetech/MMB/3D/BIGTREETECH MMB CAN V1.0-3D.step](https://github.com/bigtreetech/MMB/blob/master/3D/BIGTREETECH%20MMB%20CAN%20V1.0-3D.step)

:::
'''
translate = '''
:::tip[3D STEP File]

MMB CAN V1.0 Model [bigtreetech/MMB/3D/BIGTREETECH MMB CAN V1.0-3D.step](https://github.com/bigtreetech/MMB/blob/master/3D/BIGTREETECH%20MMB%20CAN%20V1.0-3D.step)

:::
'''

[[block]]
key = "6b910fe79dd6f70a"
origin = '''
## 引脚说明
'''
translate = '''
## Pin Description
'''

[[block]]
key = "7e49f79d5a1b45ad"
origin = '''
<ImageView src={require('./img/mmb-can-pin.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-pin.webp').default} />
'''

[[block]]
key = "a37d0ba9f2d181f0"
origin = '''
:::tip[原理图 / SCHEMATIC]

MMB CAN V1.0 原理图 [BIGTREETECH MMB CAN V1.0-SCH.pdf](https://github.com/bigtreetech/MMB/blob/master/Hardware/V1.0/BIGTREETECH%20MMB%20CAN%20V1.0-SCH.pdf)

:::
'''
translate = '''
:::tip[Schematic Diagram]

MMB CAN V1.0 Schematic Diagram [BIGTREETECH MMB CAN V1.0-SCH.pdf](https://github.com/bigtreetech/MMB/blob/master/Hardware/V1.0/BIGTREETECH%20MMB%20CAN%20V1.0-SCH.pdf)

:::
'''

[[block]]
key = "530159d6e91bb510"
origin = '''
## 接口介绍
'''
translate = '''
## Interface Introduction
'''

[[block]]
key = "83e4703555823190"
origin = '''
### USB 供电
'''
translate = '''
### USB Power Supply
'''

[[block]]
key = "f495d131d127448b"
origin = '''
主板上电之后， 电源灯会亮起，表示供电正常。板上标识 VUSB 是电源选择端，仅当使用USB 给主板供电时，才需要使用跳帽将 VUSB 短接。
'''
translate = '''
When the board is powered on, the power indicator light will turn on to confirm that the power supply is functioning correctly. The VUSB terminal on the board is the power selection terminal, which should only be shorted with a jumper when powering through USB.
'''

[[block]]
key = "47206c5d7b891d60"
origin = '''
<ImageView src={require('./img/mmb-can-usb.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-usb.webp').default} />
'''

[[block]]
key = "29b168f94fea9a63"
origin = '''
### Servo 接线
'''
translate = '''
### Servo Wiring
'''

[[block]]
key = "0436604534ae5914"
origin = '''
:::warning[警告]
此处演示为使用MMB的板载DC-DC为舵机供电。

MMB可以胜任这项工作，但如果舵机出现损坏，将迫使MMB的5V供电触发短路保护，致使MCU离线。
:::
'''
translate = '''
:::warning[Note]
This demonstration shows using the MMB's onboard DC-DC module to power the servo.

While the MMB is capable of handling this task, any damage to the servo will force the MMB's 5V power supply to trigger short-circuit protection, causing the MCU to go offline.
:::
'''

[[block]]
key = "55b2effbac29739e"
origin = '''
<ImageView src={require('./img/mmb-can-servo.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-servo.webp').default} />
'''

[[block]]
key = "8333053ebdf2e9e9"
origin = '''
### RGB-WS2812 接线
'''
translate = '''
### RGB-WS2812 Wiring
'''

[[block]]
key = "d1ff12f087a6b7ef"
origin = '''
<ImageView src={require('./img/mmb-can-ws2812.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-ws2812.webp').default} />
'''

[[block]]
key = "7c8e20a6b1ca6e9c"
origin = '''
### Sensor（如 binky/TCRT5000 红外传感器）接线
'''
translate = '''
### Sensor (e.g., binky/TCRT5000 IR Sensor) Wiring
'''

[[block]]
key = "a56c99dc71ef4fbd"
origin = '''
<ImageView src={require('./img/mmb-can-sensor.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-sensor.webp').default} />
'''

[[block]]
key = "2a232ee24c022ef8"
origin = '''
### I2C（如 AHT10 温湿度传感器）接线
'''
translate = '''
### I2C (e.g., AHT10 Temperature and Humidity Sensor) Wiring
'''

[[block]]
key = "9a74521e2a88535e"
origin = '''
<ImageView src={require('./img/mmb-can-iic.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-iic.webp').default} />
'''

[[block]]
key = "bc6a74c4bc0487dc"
origin = '''
### Endstop（如霍尔传感器）接线
'''
translate = '''
### Endstop (e.g., Hall Effect Sensor) Wiring
'''

[[block]]
key = "9fd0cc45f0ce25d5"
origin = '''
<ImageView src={require('./img/mmb-can-endstop.webp').default} />
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/mmb-series/mmb-1/img/mmb-can-endstop.webp').default} />
'''
