[metadata]

[[block]]
key = "c57823f7145956ae"
origin = '''
# Panda PTFree
'''
translate = '''
# Panda PTFree
'''

[[block]]
key = "b986a0b748729974"
origin = '''
<div class="div-table">

<img src={require('./img/panda_ptfree.webp').default} width="50%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<img src={require('@site/docs/panda-series/module/panda-ptfree/img/panda_ptfree.webp').default} width="50%" class="right-image"/>
'''

[[block]]
key = "b70e14bb5cf3ded7"
origin = '''
- 产品链接: [点击购买](https://bit.ly/42q5Oc0)
'''
translate = '''
- 产品链接: [点击购买](https://bit.ly/42q5Oc0)
'''

[[block]]
key = "2ead86bc7d9baecc"
origin = '''
## 修订历史
'''
translate = '''
## 修订历史
'''

[[block]]
key = "a7fd64b451240f15"
origin = '''
| 版本号   | 日期              | 更新内容   |
|:---------|:------------------|:-----------|
| v1.00    | 2025年9月10日      | 初始版本   |
'''
translate = '''
| 版本号   | 日期              | 更新内容   |
|:---------|:------------------|:-----------|
| v1.00    | 2025年9月10日      | 初始版本   |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## 产品简介
'''

[[block]]
key = "c1fe5c12464dfc3f"
origin = '''
Panda PTFree 是为 3D 打印设计的小帮手，让你拆 PTFE 管更快更轻松。
'''
translate = '''
Panda PTFree 是为 3D 打印设计的小帮手，让你拆 PTFE 管更快更轻松。
'''

[[block]]
key = "45f9a82242e0d4ef"
origin = '''
## 产品参数
'''
translate = '''
## 产品参数
'''

[[block]]
key = "20088fd29d414f49"
origin = '''
<img src={require('./img/size.webp').default} width="60%"/>
'''
translate = '''
<img src={require('@site/docs/panda-series/module/panda-ptfree/img/size.webp').default} width="60%"/>
'''

[[block]]
key = "75d6229cd9590f1f"
origin = '''
## 使用指南
'''
translate = '''
## 使用指南
'''

[[block]]
key = "7f4cdd09f27a2896"
origin = '''
<img src={require('./img/usage_1.webp').default} width="60%"/>
'''
translate = '''
<img src={require('@site/docs/panda-series/module/panda-ptfree/img/usage_1.webp').default} width="60%"/>
'''

[[block]]
key = "85c36a03d5868774"
origin = '''
<img src={require('./img/usage_2.webp').default} width="60%"/>
'''
translate = '''
<img src={require('@site/docs/panda-series/module/panda-ptfree/img/usage_2.webp').default} width="60%"/>
'''
