[metadata]

[[block]]
key = "1632e2cadce32b91"
origin = '''
---
sidebar_position: 3
description: EBB 2209 RP2040 Klipper 固件配置 
---
'''
translate = '''
---
sidebar_position: 3
description: EBB 2209 RP2040 Klipper Firmware Configuration 
---
'''

[[block]]
key = "945d6271ceffe9ca"
origin = '''
# EBB 2209 RP2040 固件配置
'''
translate = '''
# EBB 2209 RP2040 Firmware Configuration
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "710dc62b3fd1deb6"
origin = '''
## 写入 Klipper 固件
'''
translate = '''
## Flash Klipper Firmware
'''

[[block]]
key = "9be18829cd292d32"
origin = '''
写入 Klipper 固件参考 [EBB 系列固件 (RP2040)](../ebb-firmware-rp2040.md)
'''
translate = '''
For flashing the Klipper firmware, refer to [EBB Series Firmware (RP2040)](../ebb-firmware-rp2040.md)
'''

[[block]]
key = "97a654915a067474"
origin = '''
## Klipper 配置文件参考
'''
translate = '''
## Klipper Configuration File Reference
'''

[[block]]
key = "d5888bd7d0b91330"
origin = '''
``` klipper_cfg title="printer.cfg"
'''
translate = '''
``` klipper_cfg title="printer.cfg"
'''

[[block]]
key = "1c8aa0ba3ceb799e"
origin = '''
# This file contains common pin mappings for the BIGTREETECH EBBCan
'''
translate = '''
# This file contains common pin mappings for the BIGTREETECH EBBCan
'''

[[block]]
key = "da3f531bbcd3f3f8"
origin = '''
# Canbus board. To use this config, the firmware should be compiled for the
'''
translate = '''
# Canbus board. To use this config, the firmware should be compiled for the
'''

[[block]]
key = "26bd8f92b0db203d"
origin = '''
# RP2040 with "USB" or "CAN bus (on gpio4/gpio5)".
'''
translate = '''
# RP2040 with "USB" or "CAN bus (on gpio4/gpio5)".
'''

[[block]]
key = "48b5b64967d97d16"
origin = '''
# The "EBB Can" micro-controller will be used to control the components on the nozzle.
'''
translate = '''
# The "EBB Can" micro-controller will be used to control the components on the nozzle.
'''

[[block]]
key = "dbde9bee7c4f38a0"
origin = '''
# See docs/Config_Reference.md for a description of parameters.
'''
translate = '''
# See docs/Config_Reference.md for a description of parameters.
'''

[[block]]
key = "7eed58fcb165b304"
origin = '''
[mcu EBBCan]
canbus_uuid: 11aa22bb33cc
'''
translate = '''
[mcu EBBCan]
canbus_uuid: 11aa22bb33cc
'''

[[block]]
key = "dbba40d3b0a5cbaf"
origin = '''
[temperature_sensor EBB_NTC]
sensor_type: Generic 3950
sensor_pin: EBBCan:gpio28
'''
translate = '''
[temperature_sensor EBB_NTC]
sensor_type: Generic 3950
sensor_pin: EBBCan:gpio28
'''

[[block]]
key = "db4cfd761ad8aa6d"
origin = '''
[adxl345]
cs_pin: EBBCan:gpio1
spi_software_sclk_pin: EBBCan:gpio2
spi_software_mosi_pin: EBBCan:gpio0
spi_software_miso_pin: EBBCan:gpio3
axes_map: z,-y,x
'''
translate = '''
[adxl345]
cs_pin: EBBCan:gpio1
spi_software_sclk_pin: EBBCan:gpio2
spi_software_mosi_pin: EBBCan:gpio0
spi_software_miso_pin: EBBCan:gpio3
axes_map: z,-y,x
'''

[[block]]
key = "19cf3233400e7f4b"
origin = '''
[resonance_tester]
probe_points: 100, 100, 20
accel_chip: adxl345
'''
translate = '''
[resonance_tester]
probe_points: 100, 100, 20
accel_chip: adxl345
'''

[[block]]
key = "5df6cb57c1de87de"
origin = '''
[extruder]
step_pin: EBBCan:gpio18
dir_pin: !EBBCan:gpio19
enable_pin: !EBBCan:gpio17
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: EBBCan:gpio7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: EBBCan:gpio27
control: pid
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250
'''
translate = '''
[extruder]
step_pin: EBBCan:gpio18
dir_pin: !EBBCan:gpio19
enable_pin: !EBBCan:gpio17
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: EBBCan:gpio7
sensor_type: EPCOS 100K B57560G104F
sensor_pin: EBBCan:gpio27
control: pid
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250
'''

[[block]]
key = "154e4efe2d5b0908"
origin = '''
# sensor_type: MAX31865
'''
translate = '''
# sensor_type: MAX31865
'''

[[block]]
key = "edb6b3201a4271f8"
origin = '''
# sensor_pin: EBBCan:gpio9
'''
translate = '''
# sensor_pin: EBBCan:gpio9
'''

[[block]]
key = "7acea2e85f2b27e8"
origin = '''
# spi_software_sclk_pin: EBBCan:gpio10
'''
translate = '''
# spi_software_sclk_pin: EBBCan:gpio10
'''

[[block]]
key = "aeb5c793da8fef40"
origin = '''
# spi_software_mosi_pin: EBBCan:gpio8
'''
translate = '''
# spi_software_mosi_pin: EBBCan:gpio8
'''

[[block]]
key = "db3c363b089d99fb"
origin = '''
# spi_software_miso_pin: EBBCan:gpio11
'''
translate = '''
# spi_software_miso_pin: EBBCan:gpio11
'''

[[block]]
key = "a3b881ac8fbda254"
origin = '''
# rtd_nominal_r: 100
'''
translate = '''
# rtd_nominal_r: 100
'''

[[block]]
key = "cd96be72bcc40044"
origin = '''
# rtd_reference_r: 430
'''
translate = '''
# rtd_reference_r: 430
'''

[[block]]
key = "311d221d4aa0aad3"
origin = '''
# rtd_num_of_wires: 2
'''
translate = '''
# rtd_num_of_wires: 2
'''

[[block]]
key = "862ff26d41186888"
origin = '''
[tmc2209 extruder]
uart_pin: EBBCan:gpio20
run_current: 0.650
stealthchop_threshold: 999999
'''
translate = '''
[tmc2209 extruder]
uart_pin: EBBCan:gpio20
run_current: 0.650
stealthchop_threshold: 999999
'''

[[block]]
key = "7c097a60e252e6d1"
origin = '''
[fan]
pin: EBBCan:gpio13
'''
translate = '''
[fan]
pin: EBBCan:gpio13
'''

[[block]]
key = "54817d6d74b1bc3c"
origin = '''
[heater_fan hotend_fan]
pin: EBBCan:gpio14
heater: extruder
heater_temp: 50.0
'''
translate = '''
[heater_fan hotend_fan]
pin: EBBCan:gpio14
heater: extruder
heater_temp: 50.0
'''

[[block]]
key = "b022948410a10147"
origin = '''
[fan_generic 4W_FAN0]
pin: EBBCan:gpio15
tachometer_pin: EBBCan:gpio12
'''
translate = '''
[fan_generic 4W_FAN0]
pin: EBBCan:gpio15
tachometer_pin: EBBCan:gpio12
'''

[[block]]
key = "bbf45c466c691e1f"
origin = '''
#tachometer_ppr: 1
'''
translate = '''
#tachometer_ppr: 1
'''

[[block]]
key = "5e75945566d12ad0"
origin = '''
[neopixel hotend_rgb]
pin: EBBCan:gpio16
'''
translate = '''
[neopixel hotend_rgb]
pin: EBBCan:gpio16
'''

[[block]]
key = "8932d169c4e92577"
origin = '''
[bltouch]
sensor_pin: ^EBBCan:gpio21
control_pin: EBBCan:gpio22
'''
translate = '''
[bltouch]
sensor_pin: ^EBBCan:gpio21
control_pin: EBBCan:gpio22
'''

[[block]]
key = "42e7b56fe5c27ba4"
origin = '''
## NPN and PNP proximity switch types can be set by jumper
'''
translate = '''
## NPN and PNP proximity switch types can be set by jumper
'''

[[block]]
key = "b67fb40f92efb6d2"
origin = '''
#[probe]
'''
translate = '''
#[probe]
'''

[[block]]
key = "37d366e45daaabe5"
origin = '''
#pin: ^EBBCan:gpio6
'''
translate = '''
#pin: ^EBBCan:gpio6
'''

[[block]]
key = "3022884942eb05fa"
origin = '''
```
'''
translate = '''
```
'''
