[metadata]

[[block]]
key = "350c520fcbbd745d"
origin = '''
---
sidebar_position: 1
description: EBB 2209 (RP 2040)
---
'''
translate = '''
---
sidebar_position: 1
description: EBB 2209 (RP 2040)
---
'''

[[block]]
key = "205c1be24628968e"
origin = '''
# EBB 2209 (RP 2040)
'''
translate = '''
# EBB 2209 (RP 2040)
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "49b2bf7f593d1f7c"
origin = '''
import DocCardList from '@theme/DocCardList';
'''
translate = '''
import DocCardList from '@theme/DocCardList';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "a62ffdb50ff94cca"
origin = '''
<div class="div-table">

<ImageView 
    src={require('./img/ebb2209-rp2040-main.png').default} 
    width="45%" class="right-image"
/>
'''
translate = '''
<div class="div-table">

<ImageView 
    src={require('@site/docs/board-docs/ebb-series/ebb-2209-rp2040/img/ebb2209-rp2040-main.png').default} 
    width="45%" class="right-image"
/>
'''

[[block]]
key = "61695731d894e982"
origin = '''
## 简介
'''
translate = '''
## Introduction
'''

[[block]]
key = "d600ce5317e7c2aa"
origin = '''
EBB 2209 (RP2040) 是一个适配 voron stealthburner 的工具头板。通过 CAN 线进行连接以简化工具头接线
'''
translate = '''
EBB 2209 (RP2040) is a toolhead board adapted for the Voron Stealthburner. It connects via a CAN line to simplify toolhead wiring.
'''

[[block]]
key = "cc93f65bfb52fa05"
origin = '''
## 硬件规格
'''
translate = '''
## Hardware Specifications
'''

[[block]]
key = "a01804b18e158855"
origin = '''
| Specification         | EBB 2209 RP2040                 |
| --------------------- | ------------------------------- |
| MCU                   | RP 2040                         |
| 挤出机驱动            | TMC 2209                        |
| 温度传感器 (TH0)      | NTC / PT1000                    |
| 温度传感器 (MAX31865) | PT100 / PT1000 2 wire or 4 wire |
| 热端最大电流          | 5A                              |
| 风扇 2Pin             | x2                              |
| 风扇 4Pin             | x1                              |
'''
translate = '''
| Specification                 | EBB 2209 RP2040                 |
| ----------------------------- | ------------------------------- |
| MCU                           | RP 2040                         |
| Extruder Driver               | TMC 2209                        |
| Temperature Sensor (TH0)      | NTC / PT1000                    |
| Temperature Sensor (MAX31865) | PT100 / PT1000 2 wire or 4 wire |
| Hotend Maximum Current        | 5A                              |
| Fan 2Pin                      | x2                              |
| Fan 4Pin                      | x1                              |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "d3ac9811ffbf8210"
origin = '''
<DocCardList />
'''
translate = '''
<DocCardList />
'''
