[metadata]

[[block]]
key = "78d04f42aac2c182"
origin = '''
---
sidebar_position: 10
---
'''
translate = '''
---
sidebar_position: 10
---
'''

[[block]]
key = "6a534a4b5a193c6a"
origin = '''
# Manta M5P 系列固件 (STM32G0B1)
'''
translate = '''
# Manta M5P Series Firmware (STM32G0B1)
'''

[[block]]
key = "8309ca7c2f3f2fb4"
origin = '''
使用 `STM32G0B1` MCU 的 Manta M5P 
'''
translate = '''
Manta M5P using the `STM32G0B1` MCU
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "9debc9a58b6d331b"
origin = '''
## 构建固件
'''
translate = '''
## Build Firmware
'''

[[block]]
key = "b58c7f3c437b6f83"
origin = '''
使用 ssh 连接到 Klipper Host. 然后使用以下命令进入 Klipper 目录。并且使用 `make menuconfig` 配置固件。
'''
translate = '''
Use SSH to connect to the Klipper Host. Then use the following command to enter the Klipper directory and use `make menuconfig` to configure the firmware.
'''

[[block]]
key = "656b8b743b9fd7b4"
origin = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''
translate = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''

[[block]]
key = "95b1857d91f7258a"
origin = '''
<Tabs groupId="M5P-v1-make-connect">
    <TabItem value="bridge" label="CAN 桥接固件" default>
'''
translate = '''
<Tabs groupId="M5P-v1-make-connect">
    <TabItem value="bridge" label="CAN Bridge Firmware" default>
'''

[[block]]
key = "280e030b5d0a9cb0"
origin = '''
        按照以下选项构建使用 `STM32G0B1` 为 `MCU` 的 `Manta M5P` CAN 桥接固件
        <ImageView
            src={require('./img/manta-m5p-make-bridge.png').default}
            alt="manta M5P with g0b1 bridge"
        />
    </TabItem>
    <TabItem value="usb" label="USB 串口固件">
        按照以下选项构建使用 `STM32G0B1` 为 `MCU` 的 `Manta M5P` USB 串口固件
        <ImageView
            src={require('./img/manta-m5p-make-usb.png').default}
            alt="manta M5P with g0b1 usb"
        />
    </TabItem>
</Tabs>
'''
translate = '''
        Build the CAN bridge firmware for `Manta M5P` using `STM32G0B1` as the `MCU` according to the following options.
        <ImageView
            src={require('@site/docs/board-docs/manta-series/img/manta-m5p-make-bridge.png').default}
            alt="manta M5P with g0b1 bridge"
        />
    </TabItem>
    <TabItem value="usb" label="USB Serial Firmware">
        Build the USB serial firmware for `Manta M5P` using `STM32G0B1` as the `MCU` according to the following options.
        <ImageView
            src={require('@site/docs/board-docs/manta-series/img/manta-m5p-make-usb.png').default}
            alt="manta M5P with g0b1 usb"
        />
    </TabItem>
</Tabs>
'''

[[block]]
key = "8774d602a438d5ac"
origin = '''
当配置完成使用 `q` 来退出。使用 `y` 来保存编译选项。
'''
translate = '''
After configuration, use `q` to exit and `y` to save the build options.
'''

[[block]]
key = "b29b749495956614"
origin = '''
然后使用 `make` 命令来开始编译 Klipper 固件
'''
translate = '''
Then use the `make` command to start compiling the Klipper firmware.
'''

[[block]]
key = "5b81e604caf35eea"
origin = '''
``` shell
make
```
'''
translate = '''
``` shell
make
```
'''

[[block]]
key = "6479f7c4b55cff4a"
origin = '''
## 写入固件
'''
translate = '''
## 写入固件
'''

[[block]]
key = "4b95c3b446ddda79"
origin = '''
当使用 Klipper 固件编译完成后。然后按住 `Manta M5P` 的 `boot` 按钮。然后按一下 `reset` 然后松开 `boot` 按钮进入 `DFU` 模式。
'''
translate = '''
After compiling the Klipper firmware, press and hold the `boot` button on the `Manta M5P`. Then press `reset` once and release the `boot` button to enter `DFU` mode.
'''

[[block]]
key = "9a9de856fa57b2ee"
origin = '''
然后可以使用 `lsusb` 命令来确认 `Manta M5P` 是否在 `DFU` 模式中。
'''
translate = '''
You can then use the `lsusb` command to confirm whether the `Manta M5P` is in `DFU` mode.
'''

[[block]]
key = "d2e3cfd693be5e2c"
origin = '''
当确认 Manta M5P 在 DFU 模式中后。可以使用以下命令来写入固件。
'''
translate = '''
Once confirmed that the Manta M5P is in DFU mode, you can use the following command to flash the firmware.
'''

[[block]]
key = "07f5dba4134ca463"
origin = '''
``` shell
make flash FLASH_DEVICE=0483:df11
```
'''
translate = '''
``` shell
make flash FLASH_DEVICE=0483:df11
```
'''
