[metadata]

[[block]]
key = "78d04f42aac2c182"
origin = '''
---
sidebar_position: 10
---
'''
translate = '''
---
sidebar_position: 10
---
'''

[[block]]
key = "0f6d52c2b7f62c1b"
origin = '''
# Manta M4P 系列固件 (STM32G0B1)
'''
translate = '''
# Manta M4P Series Firmware (STM32G0B1)
'''

[[block]]
key = "2ad85477117e4b2c"
origin = '''
使用 `STM32G0B1` MCU 的 Manta M4P
'''
translate = '''
Manta M4P using the `STM32G0B1` MCU
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "9debc9a58b6d331b"
origin = '''
## 构建固件
'''
translate = '''
## Build Firmware
'''

[[block]]
key = "b58c7f3c437b6f83"
origin = '''
使用 ssh 连接到 Klipper Host. 然后使用以下命令进入 Klipper 目录。并且使用 `make menuconfig` 配置固件。
'''
translate = '''
Use SSH to connect to the Klipper Host. Then use the following command to enter the Klipper directory and use `make menuconfig` to configure the firmware.
'''

[[block]]
key = "656b8b743b9fd7b4"
origin = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''
translate = '''
``` shell
cd ~/klipper
make menuconfig 
```
'''

[[block]]
key = "d10c30f300d3bc7d"
origin = '''
按照以下选项构建使用 `STM32G0B1` 为 `MCU` 的 `Manta M4P` USB 串口固件
'''
translate = '''
Build the USB serial firmware for `Manta M4P` using `STM32G0B1` as the `MCU` according to the following options.
'''

[[block]]
key = "233348df985acfed"
origin = '''
<ImageView src={require('./img/manta-m4p-make-usb.png').default} alt="manta m4p with g0b1 usb"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/img/manta-m4p-make-usb.png').default} alt="manta m4p with g0b1 usb"/>
'''

[[block]]
key = "8774d602a438d5ac"
origin = '''
当配置完成使用 `q` 来退出。使用 `y` 来保存编译选项。
'''
translate = '''
After configuration, use `q` to exit and `y` to save the build options.
'''

[[block]]
key = "b29b749495956614"
origin = '''
然后使用 `make` 命令来开始编译 Klipper 固件
'''
translate = '''
Then use the `make` command to start compiling the Klipper firmware.
'''

[[block]]
key = "5b81e604caf35eea"
origin = '''
``` shell
make
```
'''
translate = '''
``` shell
make
```
'''

[[block]]
key = "0bbac83a4666201b"
origin = '''
## 写入固件 (Via SD card)
'''
translate = '''
## Flash Firmware (Via SD card)
'''

[[block]]
key = "e5764ce3bfcf5b29"
origin = '''
1. 从 `~/klipper/out/` 中复制 `klipper.bin` 并且改名为 `firmware.bin`
2. 复制 `firmware.bin` 到MCU SD卡的根目录中
3. 插入MCU SD卡
4. 给主板通电
'''
translate = '''
1. Copy `klipper.bin` from `~/klipper/out/` and rename it to `firmware.bin`
2. Copy `firmware.bin` to the root directory of the MCU SD card
3. Insert the MCU SD card
4. Power on the mainboard
'''
