[metadata]

[[block]]
key = "2910e28b037e0d95"
origin = '''
---
sidebar_position: 1
description: CB2
---
'''
translate = '''
---
sidebar_position: 1
description: CB2
---
'''

[[block]]
key = "0589256e38ba9133"
origin = '''
# CB2
'''
translate = '''
# CB2
'''

[[block]]
key = "49b2bf7f593d1f7c"
origin = '''
import DocCardList from '@theme/DocCardList';
'''
translate = '''
import DocCardList from '@theme/DocCardList';
'''

[[block]]
key = "cbbf8187293c762f"
origin = '''
<div class="div-table">

<ImageView src={require('./img/cb2-title.webp').default} width="40%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<ImageView src={require('@site/docs/board-docs/iot-series/iot-cb2/img/cb2-title.webp').default} width="40%" class="right-image"/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## Product Overview
'''

[[block]]
key = "a7b5ef0473436118"
origin = '''
BIGTREETECH CB2 是针对树莓派 CM4 缺货问题推出的替代方案,所有输出信号采用 2 个 100PIN微型 BTB 高速连接座与外面扩展底板方便快速连接(包括千兆以太网、HDMI 等)，板载 2.4G、5GWIFI BT5.2。
'''
translate = '''
The BIGTREETECH CB2 is an alternative solution designed to address the shortage of Raspberry Pi CM4 units. All output signals utilize two 100-pin micro BTB high-speed connectors for quick and easy connection to external expansion boards (including Gigabit Ethernet, HDMI, etc.). It features onboard 2.4GHz and 5GHz Wi-Fi and Bluetooth 5.2.
'''

[[block]]
key = "3793c167c87a1c58"
origin = '''
## 产品特点
'''
translate = '''
## Product Features
'''

[[block]]
key = "1502499fcd9aeb48"
origin = '''
- CPU: 瑞芯微 RK3566，四核 Cortex-A55 @1.8GHz
- GPU: Mali-G52 1-Core-2EE
- NPU: 0.8 TOPS NPU
- RAM: 2GB/4GB LPDDR4
- 板载 EMMC
- MIPI DSI 显示支持
- 摄像头 2-Lane MIPI CSI2
- 3 路 USB2.0 端口 1 路 USB3.0
- PCIe 2.1 1x1 Lane
- 千兆以太网+433Mbps WiFi+BT5.0
- 40-pin GPIO
- 与树莓派 CM4 完全相同的 BTB 座子
'''
translate = '''
- CPU: Rockchip RK3566, Quad-core Cortex-A55 @ 1.8GHz
- GPU: Mali-G52 1-Core-2EE
- NPU: 0.8 TOPS NPU
- RAM: 2GB/4GB LPDDR4
- On-board eMMC
- MIPI DSI display support
- Camera: 2-Lane MIPI CSI2
- 3 USB 2.0 ports, 1 USB 3.0 port
- PCIe 2.1 1x1 Lane
- Gigabit Ethernet + 433Mbps Wi-Fi + Bluetooth 5.0
- 40-pin GPIO
- BTB socket identical to the Raspberry Pi CM4
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "45f9a82242e0d4ef"
origin = '''
## 产品参数
'''
translate = '''
## Product Specifications
'''

[[block]]
key = "d2626246ccc4f60c"
origin = '''
| 核心板外观尺寸 | 40mm x 55mm                         |
| -------------- | ----------------------------------- |
| 核心板安装尺寸 | 33mm x 48mm                         |
| 核心板输入电压 | 5V±5%/2A                            |
| 核心板输出电压 | 3.3V±2%/100mA                       |
| 核心板输出电压 | 1.8V±2%/100mA                       |
| 核心板 WIFI    | 2.4G/5G，802.11 ac/a/b/g/n/无线标准 |
'''
translate = '''
| Core Board Dimensions          | 40mm x 55mm                                         |
| ------------------------------ | --------------------------------------------------- |
| Core Board Mounting Dimensions | 33mm x 48mm                                         |
| Core Board Input Voltage       | 5V±5%/2A                                            |
| Core Board Output Voltage      | 3.3V±2%/100mA                                       |
| Core Board Output Voltage      | 1.8V±2%/100mA                                       |
| Core Board Wi-Fi               | 2.4 GHz/5 GHz, 802.11 ac/a/b/g/n wireless standards |
'''

[[block]]
key = "d3ac9811ffbf8210"
origin = '''
<DocCardList />
'''
translate = '''
<DocCardList />
'''
