[metadata]

[[block]]
key = "dd24dfa5953e1236"
origin = '''
---
sidebar_position: 1
---
'''
translate = '''
---
sidebar_position: 1
---
'''

[[block]]
key = "bc793c98005b896d"
origin = '''
# Panda Claw A1/A1 Mini
'''
translate = '''
# Panda Claw A1/A1 Mini
'''

[[block]]
key = "5dc8cca84f5a8b69"
origin = '''
<div class="div-table">

<ImageView src={require('./img/Panda_Claw_A1mini_Title.webp').default} width="40%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Title.webp').default} width="40%" class="right-image"/>
'''

[[block]]
key = "6e3d031df0b0cf65"
origin = '''
## **产品简介**
'''
translate = '''
## **产品简介**
'''

[[block]]
key = "ae256af4845deb1b"
origin = '''
BIQU Panda Claw 是一种专为 X1、P1和A1系列打印机设计的挤出机齿轮套件。该齿轮组采用金色RNC纳米涂层硬化钢齿轮和铝制 CNC 惰轮支臂，旨在提高打印机的挤出性能和耐用性。
'''
translate = '''
BIQU Panda Claw 是一种专为 X1、P1和A1系列打印机设计的挤出机齿轮套件。该齿轮组采用金色RNC纳米涂层硬化钢齿轮和铝制 CNC 惰轮支臂，旨在提高打印机的挤出性能和耐用性。
'''

[[block]]
key = "53b10a12d3de6d92"
origin = '''
## **功能亮点**
'''
translate = '''
## **功能亮点**
'''

[[block]]
key = "44f5eaf069410e2b"
origin = '''
- **高耐磨性**: 金色RNC纳米涂层硬化钢齿轮，硬度升级，耐磨性增强，轻松应对各类纤维耗材。
- **稳定耐用**: AL6061T6铝合金CNC惰轮支臂，轻量化，高强度，精密制造，减少挤出齿轮位移；黄铜材质减速齿轮，具有自润滑属性，更耐磨，寿命更久，耗材控制更精准。
- **高精度**: 减速齿轮五辐镂空偷轻结构，惯性更小，定位更精准，打印更精细。
- **兼容性强**: 兼容Bambu Lab X1/P1/A1系列打印机。
'''
translate = '''
- **高耐磨性**: 金色RNC纳米涂层硬化钢齿轮，硬度升级，耐磨性增强，轻松应对各类纤维耗材。
- **稳定耐用**: AL6061T6铝合金CNC惰轮支臂，轻量化，高强度，精密制造，减少挤出齿轮位移；黄铜材质减速齿轮，具有自润滑属性，更耐磨，寿命更久，耗材控制更精准。
- **高精度**: 减速齿轮五辐镂空偷轻结构，惯性更小，定位更精准，打印更精细。
- **兼容性强**: 兼容Bambu Lab X1/P1/A1系列打印机。
'''

[[block]]
key = "d95dace42963d665"
origin = '''
## **包装清单**
'''
translate = '''
## **包装清单**
'''

[[block]]
key = "e0c950e3e14ff1a4"
origin = '''
| 物品名称       | 数量 |
| -------------- | ---- |
| Panda Claw     | 1    |
| 轴承           | 2    |
| 二硫化钼润滑脂 | 1    |
'''
translate = '''
| 物品名称       | 数量 |
| -------------- | ---- |
| Panda Claw     | 1    |
| 轴承           | 2    |
| 二硫化钼润滑脂 | 1    |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "c62f6c621d36af44"
origin = '''
## **Panda Claw 安装指南**
'''
translate = '''
## **Panda Claw 安装指南**
'''

[[block]]
key = "8381b4147878ae07"
origin = '''
在本指南中，您将学习如何将A1打印机的原装挤出齿轮更换为Panda Claw组件。
'''
translate = '''
在本指南中，您将学习如何将A1打印机的原装挤出齿轮更换为Panda Claw组件。
'''

[[block]]
key = "ad83d0679eed241c"
origin = '''
### 步骤 1: 移出原挤出机齿轮组件
'''
translate = '''
### 步骤 1: 移出原挤出机齿轮组件
'''

[[block]]
key = "1a57b26858b9dde7"
origin = '''
1.移除喷嘴组件
'''
translate = '''
1.移除喷嘴组件
'''

[[block]]
key = "b84958cbda83a41c"
origin = '''
（如果挤出机处于咬合料线的状态，请使用切刀手动切断料线）从侧面用力按压工具头前盖，解锁并移除前盖。用手扣热端硅胶套侧面的凸起，取下热端硅胶套。
'''
translate = '''
（如果挤出机处于咬合料线的状态，请使用切刀手动切断料线）从侧面用力按压工具头前盖，解锁并移除前盖。用手扣热端硅胶套侧面的凸起，取下热端硅胶套。
'''

[[block]]
key = "39c6eaccb2821557"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide.webp').default} width="80%"/>
'''

[[block]]
key = "fb854131743d0d1c"
origin = '''
卸下旋转轮。使用H1.5内六角扳手移除两颗螺丝，取下料线压块。
'''
translate = '''
卸下旋转轮。使用H1.5内六角扳手移除两颗螺丝，取下料线压块。
'''

[[block]]
key = "cebb257a2f1d8999"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide1.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide1.webp').default} width="80%"/>
'''

[[block]]
key = "cf8cbb43cf91680a"
origin = '''
解锁热端锁扣，手握散热片，取出热端。
'''
translate = '''
解锁热端锁扣，手握散热片，取出热端。
'''

[[block]]
key = "20e76873be29b883"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide2.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide2.webp').default} width="80%"/>
'''

[[block]]
key = "c012952794972354"
origin = '''
2.拧松切刀
'''
translate = '''
2.拧松切刀
'''

[[block]]
key = "94ea879bf573ce55"
origin = '''
使用H2.0内六角扳手移除螺丝，松开切刀刀柄。
'''
translate = '''
使用H2.0内六角扳手移除螺丝，松开切刀刀柄。
'''

[[block]]
key = "aba66abc354b8832"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide3.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide3.webp').default} width="80%"/>
'''

[[block]]
key = "14e2240e266f4457"
origin = '''
用镊子和气吹从图示位置清理断料和残渣（断电时可手动顺时针转动黄色齿轮清理，或者，上电时点击屏幕退料按钮，让挤出轮旋转到指定角度清理）。 
'''
translate = '''
用镊子和气吹从图示位置清理断料和残渣（断电时可手动顺时针转动黄色齿轮清理，或者，上电时点击屏幕退料按钮，让挤出轮旋转到指定角度清理）。 
'''

[[block]]
key = "26cbb691dc3fa655"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide4.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide4.webp').default} width="80%"/>
'''

[[block]]
key = "7a82f5fc2d72179a"
origin = '''
3.移出原挤出机齿轮组件
'''
translate = '''
3.移出原挤出机齿轮组件
'''

[[block]]
key = "30a51e65649e1d3f"
origin = '''
1)移除五通：使用H2.0内六角扳手移除两颗螺丝，取出五通。
'''
translate = '''
1)移除五通：使用H2.0内六角扳手移除两颗螺丝，取出五通。
'''

[[block]]
key = "fee3d3998d7de3d3"
origin = '''
  注意不要损坏黑色FPC线缆，取出五通后放置于工具头上方，如图所示。
'''
translate = '''
  注意不要损坏黑色FPC线缆，取出五通后放置于工具头上方，如图所示。
'''

[[block]]
key = "1d43053e18995f0f"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide5.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide5.webp').default} width="80%"/>
'''

[[block]]
key = "34a9ac29ae3c587d"
origin = '''
2)移除挤出机前盖：使用H2.0内六角扳手移除前盖上的四颗螺丝。
'''
translate = '''
2)移除挤出机前盖：使用H2.0内六角扳手移除前盖上的四颗螺丝。
'''

[[block]]
key = "87df9e303d09d2e3"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide6.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide6.webp').default} width="80%"/>
'''

[[block]]
key = "d86ed02dece2c8c6"
origin = '''
取下前盖时，先稍微拧松侧边螺丝（只需要拧松一些即可），然后按住从动轮支架顶部，用力移除前盖。
'''
translate = '''
取下前盖时，先稍微拧松侧边螺丝（只需要拧松一些即可），然后按住从动轮支架顶部，用力移除前盖。
'''

[[block]]
key = "147bbf2db41e0a73"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide7.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide7.webp').default} width="80%"/>
'''

[[block]]
key = "0eac96a6162673bd"
origin = '''
3）移除从动轮支架：使用H2.0内六角扳手移除侧面螺丝。
'''
translate = '''
3）移除从动轮支架：使用H2.0内六角扳手移除侧面螺丝。
'''

[[block]]
key = "a39ad88f4333391b"
origin = '''
取出支架时，内部弹簧和端盖容易掉落，请用镊子小心取出，避免丢失。
'''
translate = '''
取出支架时，内部弹簧和端盖容易掉落，请用镊子小心取出，避免丢失。
'''

[[block]]
key = "d92f9efb8e31281b"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide8.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide8.webp').default} width="80%"/>
'''

[[block]]
key = "1fd816c151e29ae4"
origin = '''
4）移除挤出齿轮：直接取出挤出机齿轮组件。
'''
translate = '''
4）移除挤出齿轮：直接取出挤出机齿轮组件。
'''

[[block]]
key = "821093f9d2474c49"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide9.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide9.webp').default} width="80%"/>
'''

[[block]]
key = "0632ceaee4fc36d5"
origin = '''
现在您已经移除了原装的挤出齿轮，我们可以开始安装Panda Claw了。
'''
translate = '''
现在您已经移除了原装的挤出齿轮，我们可以开始安装Panda Claw了。
'''

[[block]]
key = "42d5cb00d3d68d85"
origin = '''
### 步骤 2. Panda Claw 组装指南
'''
translate = '''
### 步骤 2. Panda Claw 组装指南
'''

[[block]]
key = "035785ab5b45a3ab"
origin = '''
1.安装挤出齿轮
'''
translate = '''
1.安装挤出齿轮
'''

[[block]]
key = "6dfa06fd1fd3ccfc"
origin = '''
给齿轮润滑后（润滑区域如下图中绿色高亮部分所示），安装挤出齿轮。
'''
translate = '''
给齿轮润滑后（润滑区域如下图中绿色高亮部分所示），安装挤出齿轮。
'''

[[block]]
key = "9e45703a121dd0d7"
origin = '''
<font  color="red">**注意：请务必避免润滑油接触到挤出齿轮的齿（如下图中蓝色高亮部分所示）。如润滑油已沾上，简单擦拭无法去除。必须使用肥皂彻底清洗齿轮，以去除油脂，之后再重新涂抹润滑油。**</font>
'''
translate = '''
<font  color="red">**注意：请务必避免润滑油接触到挤出齿轮的齿（如下图中蓝色高亮部分所示）。如润滑油已沾上，简单擦拭无法去除。必须使用肥皂彻底清洗齿轮，以去除油脂，之后再重新涂抹润滑油。**</font>
'''

[[block]]
key = "387eb21001a0efbb"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide20.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide20.webp').default} width="80%"/>
'''

[[block]]
key = "3b9bf39ee1952b41"
origin = '''
2.安装从动轮支架
'''
translate = '''
2.安装从动轮支架
'''

[[block]]
key = "acb7b80ebf04837e"
origin = '''
将从动轮支架装到相应的转轴上。按正确方向和位置安装弹簧和端盖（参照下方正确与错误示范），用镊子放到从动轮支架对应的位置上，拧入侧面螺丝将其顶住，但先不要将其拧紧。
'''
translate = '''
将从动轮支架装到相应的转轴上。按正确方向和位置安装弹簧和端盖（参照下方正确与错误示范），用镊子放到从动轮支架对应的位置上，拧入侧面螺丝将其顶住，但先不要将其拧紧。
'''

[[block]]
key = "606eeefac59870ae"
origin = '''
**重要提醒！**
'''
translate = '''
**重要提醒！**
'''

[[block]]
key = "2b73369e87fa6658"
origin = '''
确保弹簧和端盖正确安装，否则挤出机将无法正常咬合耗材，导致打印失败。
'''
translate = '''
确保弹簧和端盖正确安装，否则挤出机将无法正常咬合耗材，导致打印失败。
'''

[[block]]
key = "c801e38bcf3d0cf6"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide11.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide11.webp').default} width="80%"/>
'''

[[block]]
key = "82214f7225788211"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide12.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide12.webp').default} width="80%"/>
'''

[[block]]
key = "6c5418beae90de1c"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide13.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide13.webp').default} width="80%"/>
'''

[[block]]
key = "2143be6498da636e"
origin = '''
3.安装挤出机前盖
'''
translate = '''
3.安装挤出机前盖
'''

[[block]]
key = "3d84da3ff62d4f3b"
origin = '''
拧入挤出机前盖的四颗螺丝。
'''
translate = '''
拧入挤出机前盖的四颗螺丝。
'''

[[block]]
key = "bbbfe45bb4fc24de"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide14.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide14.webp').default} width="80%"/>
'''

[[block]]
key = "8b1801f86d0e27ff"
origin = '''
4.将挤出机侧面的螺丝拧紧
'''
translate = '''
4.将挤出机侧面的螺丝拧紧
'''

[[block]]
key = "fb40e359acea056b"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide15.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide15.webp').default} width="80%"/>
'''

[[block]]
key = "5dd22f4a25579f67"
origin = '''
5.安装五通
'''
translate = '''
5.安装五通
'''

[[block]]
key = "7232e0f983b3bc6c"
origin = '''
安装五通组件时，确保黑色FPC线缆不被折叠，顺利放入空缺位置。然后拧入两颗螺丝，固定五通。
'''
translate = '''
安装五通组件时，确保黑色FPC线缆不被折叠，顺利放入空缺位置。然后拧入两颗螺丝，固定五通。
'''

[[block]]
key = "7176207caae2b2a5"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide16.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide16.webp').default} width="80%"/>
'''

[[block]]
key = "637e09495af9beaf"
origin = '''
6.安装切刀
'''
translate = '''
6.安装切刀
'''

[[block]]
key = "8ed6da67f6f86999"
origin = '''
抬起刀柄，沿刀槽将切刀滑入到位，拧紧螺丝固定刀柄。
'''
translate = '''
抬起刀柄，沿刀槽将切刀滑入到位，拧紧螺丝固定刀柄。
'''

[[block]]
key = "bf42653e5ba0177e"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide17.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide17.webp').default} width="80%"/>
'''

[[block]]
key = "213e83e1843b5218"
origin = '''
7.安装喷嘴组件
'''
translate = '''
7.安装喷嘴组件
'''

[[block]]
key = "707ecfe1cafcd6cb"
origin = '''
握住喷嘴散热片，对齐安装位置，安装喷嘴并锁定，装上热端硅胶套。拧紧两颗螺丝固定料线压块。
'''
translate = '''
握住喷嘴散热片，对齐安装位置，安装喷嘴并锁定，装上热端硅胶套。拧紧两颗螺丝固定料线压块。
'''

[[block]]
key = "799b447913a1a652"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide18.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide18.webp').default} width="80%"/>
'''

[[block]]
key = "391335f42aa8bf9c"
origin = '''
最后，安装旋转轮及工具头前盖。
'''
translate = '''
最后，安装旋转轮及工具头前盖。
'''

[[block]]
key = "29c73ff5a3befc89"
origin = '''
<ImageView src={require('./img/Panda_Claw_A1mini_Guide19.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/extruder/panda-claw-a1mini/img/Panda_Claw_A1mini_Guide19.webp').default} width="80%"/>
'''

[[block]]
key = "4bada99ca5356eae"
origin = '''
恭喜您！Panda Claw已经安装完成。享受更高的打印性能与精度吧！
'''
translate = '''
恭喜您！Panda Claw已经安装完成。享受更高的打印性能与精度吧！
'''
