[metadata]

[[block]]
key = "2823cd6243f10720"
origin = '''
---
sidebar_position: 1
description: Octopus Pro
---
'''
translate = '''
---
sidebar_position: 1
description: Octopus Pro
---
'''

[[block]]
key = "610bf0b0f6033635"
origin = '''
# Octopus Pro
'''
translate = '''
# Octopus Pro
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "9a4d9968e431e52b"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocCardList from '@theme/DocCardList';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocCardList from '@theme/DocCardList';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "5896f32630f9d24c"
origin = '''
## Specification
'''
translate = '''
## Specification
'''

[[block]]
key = "9dad27d08ba1706c"
origin = '''
| Octopus Pro H7 version | Specification                      |
| ---------------------- | ---------------------------------- |
| MCU                    | Arm Cortex-M7 STM32H723ZET6 550MHz |
| 主板供电               | DC 12V - DC 24V                    |
| 驱动供电               | 最高 DC56V (需要驱动支持)          |
| 热床接口供电           | DC 12V - DC 24V                    |  |
| 热床最大电流           | 10A (峰值 12A)                     |
| 热端加热最大电流       | 5.5A (峰值 6A)                     |
'''
translate = '''
| Octopus Pro H7 version | Specification                      |
| ---------------------- | ---------------------------------- |
| MCU                    | Arm Cortex-M7 STM32H723ZET6 550MHz |
| 主板供电               | DC 12V - DC 24V                    |
| 驱动供电               | 最高 DC56V (需要驱动支持)          |
| 热床接口供电           | DC 12V - DC 24V                    |  |
| 热床最大电流           | 10A (峰值 12A)                     |
| 热端加热最大电流       | 5.5A (峰值 6A)                     |
'''

[[block]]
key = "fd15a153377385b3"
origin = '''
| Octopus Pro F446 version | Specification                      |
| ------------------------ | ---------------------------------- |
| MCU                      | Arm Cortex-M7 STM32F446ZET6 180MHz |
| 主板供电                 | DC 12V - DC 24V                    |
| 驱动供电                 | 最高 DC56V (需要驱动支持)          |
| 热床接口供电             | DC 12V - DC 24V                    |  |
| 热床最大电流             | 10A (峰值 12A)                     |
| 热端加热最大电流         | 5.5A (峰值 6A)                     |
'''
translate = '''
| Octopus Pro F446 version | Specification                      |
| ------------------------ | ---------------------------------- |
| MCU                      | Arm Cortex-M7 STM32F446ZET6 180MHz |
| 主板供电                 | DC 12V - DC 24V                    |
| 驱动供电                 | 最高 DC56V (需要驱动支持)          |
| 热床接口供电             | DC 12V - DC 24V                    |  |
| 热床最大电流             | 10A (峰值 12A)                     |
| 热端加热最大电流         | 5.5A (峰值 6A)                     |
'''

[[block]]
key = "f1016bca0c1f13d3"
origin = '''
| Octopus Pro F429 version | Specification                      |
| ------------------------ | ---------------------------------- |
| MCU                      | Arm Cortex-M7 STM32F429ZGT6 180MHz |
| 主板供电                 | DC 12V - DC 24V                    |
| 驱动供电                 | 最高 DC56V (需要驱动支持)          |
| 热床接口供电             | DC 12V - DC 24V                    |  |
| 热床最大电流             | 10A (峰值 12A)                     |
| 热端加热最大电流         | 5.5A (峰值 6A)                     |
'''
translate = '''
| Octopus Pro F429 version | Specification                      |
| ------------------------ | ---------------------------------- |
| MCU                      | Arm Cortex-M7 STM32F429ZGT6 180MHz |
| 主板供电                 | DC 12V - DC 24V                    |
| 驱动供电                 | 最高 DC56V (需要驱动支持)          |
| 热床接口供电             | DC 12V - DC 24V                    |  |
| 热床最大电流             | 10A (峰值 12A)                     |
| 热端加热最大电流         | 5.5A (峰值 6A)                     |
'''

[[block]]
key = "d3ac9811ffbf8210"
origin = '''
<DocCardList />
'''
translate = '''
<DocCardList />
'''
