[metadata]

[[block]]
key = "a97f04a69ec5fbb8"
origin = '''
---
sidebar_position: 2
description: Octopus Pro 硬件详细
---
'''
translate = '''
---
sidebar_position: 2
description: Octopus Pro 硬件详细
---
'''

[[block]]
key = "9d8dca7b892af64c"
origin = '''
# Octopus Pro 硬件功能
'''
translate = '''
# Octopus Pro 硬件功能
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "d246b00b41b81b5c"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import ThemedImage from '@theme/ThemedImage';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import ThemedImage from '@theme/ThemedImage';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "a9ae5a7eafeac08f"
origin = '''
## 尺寸
'''
translate = '''
## 尺寸
'''

[[block]]
key = "ec687742b946d7fe"
origin = '''
:::info

尺寸参考 GitHub Repo [bigtreetech/BIGTREETECH-OCTOPUS-Pro/Hardware/BIGTREETECH Octopus Pro - SIZE](https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-Pro/blob/master/Hardware/BIGTREETECH%20Octopus%20Pro%20-%20SIZE.pdf)

:::
'''
translate = '''
:::info

尺寸参考 GitHub Repo [bigtreetech/BIGTREETECH-OCTOPUS-Pro/Hardware/BIGTREETECH Octopus Pro - SIZE](https://github.com/bigtreetech/BIGTREETECH-OCTOPUS-Pro/blob/master/Hardware/BIGTREETECH%20Octopus%20Pro%20-%20SIZE.pdf)

:::
'''

[[block]]
key = "a2df1b4a41a65fdc"
origin = '''
## Pinout 
'''
translate = '''
## Pinout 
'''

[[block]]
key = "3a12c1565871bf6d"
origin = '''
<a href={require('./img/octopus-pro-pinout-light.png').default} target="_blank">
    <ThemedImage
        alt="octopus-pro-pinout"
        sources={{
            light: require('./img/octopus-pro-pinout-light.png').default,
            dark: require('./img/octopus-pro-pinout-dark.png').default,
        }} width="100%"
    />
'''
translate = '''
<a href={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-pinout-light.png').default} target="_blank">
    <ThemedImage
        alt="octopus-pro-pinout"
        sources={{
            light: require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-pinout-light.png').default,
            dark: require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-pinout-dark.png').default,
        }} width="100%"
    />
'''

[[block]]
key = "cfb0b5f8ccae7182"
origin = '''
</a>
'''
translate = '''
</a>
'''

[[block]]
key = "465a0d3a27e44929"
origin = '''
## 硬件功能配置
'''
translate = '''
## 硬件功能配置
'''

[[block]]
key = "f24f89cbf275581b"
origin = '''
### USB 接口供电
'''
translate = '''
### USB 接口供电
'''

[[block]]
key = "c70a0021b91d5c5e"
origin = '''
插入跳线即可使用 `USB-C` 为 `octopus` 供电。这可以使使用DFU模式直接编译和下载固件到主板更容易。
'''
translate = '''
插入跳线即可使用 `USB-C` 为 `octopus` 供电。这可以使使用DFU模式直接编译和下载固件到主板更容易。
'''

[[block]]
key = "1b69d2f6bd3e4749"
origin = '''
如果您不连接此跳线，那么如果您想通过 `USB-C` 进行通信，则必须通过主输入电源为板供电。
'''
translate = '''
如果您不连接此跳线，那么如果您想通过 `USB-C` 进行通信，则必须通过主输入电源为板供电。
'''

[[block]]
key = "98a40492700510ab"
origin = '''
<ImageView src={require('./img/octopus-pro-usb-power.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-usb-power.png').default} width="80%"/>
'''

[[block]]
key = "5a9c1b36b2837086"
origin = '''
### 自动断电接线
'''
translate = '''
### 自动断电接线
'''

[[block]]
key = "e596951ddc4bd319"
origin = '''
当使用 BIGTREETECH 继电器 V1.2 模块时，可以按照下图所示进行接线。
'''
translate = '''
当使用 BIGTREETECH 继电器 V1.2 模块时，可以按照下图所示进行接线。
'''

[[block]]
key = "01cffaf36bd83501"
origin = '''
<ImageView src={require('./img/octopus-pro-relay.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-relay.png').default} width="80%"/>
'''

[[block]]
key = "1d467d765b521cd9"
origin = '''
:::warning

由于 `Relay 1.2` 模块在切断主板电源后仍将供电，因此在打印机仍连接到电源时触摸它是极其危险的。在处理此接线时，请务必断开所有主电源。

:::
'''
translate = '''
:::warning

由于 `Relay 1.2` 模块在切断主板电源后仍将供电，因此在打印机仍连接到电源时触摸它是极其危险的。在处理此接线时，请务必断开所有主电源。

:::
'''

[[block]]
key = "2ca3c8457d4d427a"
origin = '''
### BL TOUCH
'''
translate = '''
### BL TOUCH
'''

[[block]]
key = "ef2e666b2aa4cf21"
origin = '''
使用BL Touch时，如下图所示将其连接到主板。
'''
translate = '''
使用BL Touch时，如下图所示将其连接到主板。
'''

[[block]]
key = "c9cb52982bbdddf0"
origin = '''
<ImageView src={require('./img/octopus-pro-bltouch.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-bltouch.png').default} width="80%"/>
'''

[[block]]
key = "c5ba87e7a93379bf"
origin = '''
### Neopixel
'''
translate = '''
### Neopixel
'''

[[block]]
key = "648ac8863b71b7ec"
origin = '''
<ImageView src={require('./img/octopus-pro-neopix.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-neopix.png').default} width="80%"/>
'''

[[block]]
key = "488411871e4986d5"
origin = '''
### Raspberry Pi
'''
translate = '''
### Raspberry Pi
'''

[[block]]
key = "4c506ba2e99f8e38"
origin = '''
Octopus Pro 支持连接到树莓派进行打印。有几种连接方式可用于连接 Raspberry Pi。
'''
translate = '''
Octopus Pro 支持连接到树莓派进行打印。有几种连接方式可用于连接 Raspberry Pi。
'''

[[block]]
key = "a6dfa5d5c82025fe"
origin = '''
- Raspberry Pi 直接连接到 USB-C 端口
- 使用 UART 或 SPI 使用直接串行连接将 Raspberry Pi 连接
'''
translate = '''
- Raspberry Pi 直接连接到 USB-C 端口
- 使用 UART 或 SPI 使用直接串行连接将 Raspberry Pi 连接
'''

[[block]]
key = "220a9e10e5664f5c"
origin = '''
### 电机驱动配置
'''
translate = '''
### 电机驱动配置
'''

[[block]]
key = "45a97cd4fcb89742"
origin = '''
<Tabs groupId="octopus-stepper-driver">
    <TabItem value="tmc-uart" label="Uart 模式" default>
'''
translate = '''
<Tabs groupId="octopus-stepper-driver">
    <TabItem value="tmc-uart" label="Uart 模式" default>
'''

[[block]]
key = "2a684a21b52ba44d"
origin = '''
        使用 Uart 模式连接驱动
        <ImageView
            src={require('./img/octopus-pro-driver-uart.png').default}
            alt="" width="100%"
        />
    </TabItem>
    <TabItem value="tmc-spi" label="SPI 模式">
        使用 SPI 模式连接驱动
        <ImageView
            src={require('./img/octopus-pro-driver-spi.png').default}
            alt="" width="100%"
        />
    </TabItem>
    <TabItem value="step-dir" label="Step / dir 模式">
        使用不支持 Uart 或者 SPI 的驱动。
        <ImageView
            src={require('./img/octopus-pro-driver-step-dir.png').default}
            alt="" width="100%"
        />
        以下是跳线参考，不同的驱动会有不同的跳线配置
        <ImageView
            src={require('./img/octopus-pro-driver-step-dir-config.png').default}
            alt="" width="100%"
        />
    </TabItem>
</Tabs>
'''
translate = '''
        使用 Uart 模式连接驱动
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-uart.png').default}
            alt="" width="100%"
        />
    </TabItem>
    <TabItem value="tmc-spi" label="SPI 模式">
        使用 SPI 模式连接驱动
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-spi.png').default}
            alt="" width="100%"
        />
    </TabItem>
    <TabItem value="step-dir" label="Step / dir 模式">
        使用不支持 Uart 或者 SPI 的驱动。
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-step-dir.png').default}
            alt="" width="100%"
        />
        以下是跳线参考，不同的驱动会有不同的跳线配置
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-step-dir-config.png').default}
            alt="" width="100%"
        />
    </TabItem>
</Tabs>
'''

[[block]]
key = "9dc7fe83eb9cf977"
origin = '''
### 电机驱动电压选择
'''
translate = '''
### 电机驱动电压选择
'''

[[block]]
key = "ea8b59c14c4eaca9"
origin = '''
:::warning

请勿在通电状态下插拔跳线帽

:::
'''
translate = '''
:::warning

请勿在通电状态下插拔跳线帽

:::
'''

[[block]]
key = "3982a8b48ac6796c"
origin = '''
<Tabs groupId="octopus-driver-v">
    <TabItem value="VBB" label="Octopus Pro VBB" default>
'''
translate = '''
<Tabs groupId="octopus-driver-v">
    <TabItem value="VBB" label="Octopus Pro VBB" default>
'''

[[block]]
key = "752a2bf9ef4e762f"
origin = '''
        当使用 `VBB` 进行供电的时候。来源为主板 `Power` 输入。最高电压为 `24V`。
        <ImageView
            src={require('./img/octopus-pro-driver-vbb.png').default}
            alt="octo pro vbb" width="60%"
        />
    </TabItem>
    <TabItem value="high-oltage" label="Octopus Pro High Voltage">
        当使用 `High Voltage` 进行供电的时候。来源为主板 `Motor Power` 输入。最高电压为 `56V`。需要注意驱动最大电压范围。
        <ImageView
            src={require('./img/octopus-pro-driver-hv.png').default}
            alt="octo pro high voltage" width="60%"
        />
    </TabItem>
</Tabs>
'''
translate = '''
        当使用 `VBB` 进行供电的时候。来源为主板 `Power` 输入。最高电压为 `24V`。
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-vbb.png').default}
            alt="octo pro vbb" width="60%"
        />
    </TabItem>
    <TabItem value="high-oltage" label="Octopus Pro High Voltage">
        当使用 `High Voltage` 进行供电的时候。来源为主板 `Motor Power` 输入。最高电压为 `56V`。需要注意驱动最大电压范围。
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-hv.png').default}
            alt="octo pro high voltage" width="60%"
        />
    </TabItem>
</Tabs>
'''

[[block]]
key = "42a1c5868cbd4eef"
origin = '''
### 风扇电压选择
'''
translate = '''
### 风扇电压选择
'''

[[block]]
key = "b96c5b218fbb4629"
origin = '''
Octopus_Pro具有6个PWM风扇输出和两个“常开”风扇输出。还有一个用于接近传感器或探针的专用针头。
'''
translate = '''
Octopus_Pro具有6个PWM风扇输出和两个“常开”风扇输出。还有一个用于接近传感器或探针的专用针头。
'''

[[block]]
key = "f90f3ed0459be2d7"
origin = '''
所有风扇输出和接近传感器输入都可以通过配置与每个插头相关的跳线来分别选择由其引脚插头提供的电压。
'''
translate = '''
所有风扇输出和接近传感器输入都可以通过配置与每个插头相关的跳线来分别选择由其引脚插头提供的电压。
'''

[[block]]
key = "2eb548b9ad0ff02e"
origin = '''
按以下方式配置跳线以选择24V（注意，所有跳线都显示在相同的配置中，即使它们可以单独配置）。
'''
translate = '''
按以下方式配置跳线以选择24V（注意，所有跳线都显示在相同的配置中，即使它们可以单独配置）。
'''

[[block]]
key = "3ee4f561e516d087"
origin = '''
<Tabs groupId="octopus-fan-v">
    <TabItem value="24v-fan" label="24V 风扇 / 接近开关" default>
'''
translate = '''
<Tabs groupId="octopus-fan-v">
    <TabItem value="24v-fan" label="24V 风扇 / 接近开关" default>
'''

[[block]]
key = "42a44b1675defb99"
origin = '''
        <ImageView
            src={require('./img/octopus-pro-fan-24.png').default}
            alt="octo pro fan 24" width="100%"
        />
'''
translate = '''
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-fan-24.png').default}
            alt="octo pro fan 24" width="100%"
        />
'''

[[block]]
key = "69febe22760ca43b"
origin = '''
    </TabItem>
    <TabItem value="12v-fan" label="12V 风扇 / 接近开关">
        <ImageView
            src={require('./img/octopus-pro-fan-12.png').default}
            alt="octo pro fan 12" width="100%"
        />
    </TabItem>
    <TabItem value="5v-fan" label=" 5V 风扇 / 接近开关">
        <ImageView
            src={require('./img/octopus-pro-fan-5.png').default}
            alt="octo pro fan 5" width="100%"
        />
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="12v-fan" label="12V 风扇 / 接近开关">
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-fan-12.png').default}
            alt="octo pro fan 12" width="100%"
        />
    </TabItem>
    <TabItem value="5v-fan" label=" 5V 风扇 / 接近开关">
        <ImageView
            src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-fan-5.png').default}
            alt="octo pro fan 5" width="100%"
        />
    </TabItem>
</Tabs>
'''

[[block]]
key = "334cfc24f2bf5d6e"
origin = '''
### TMC STALLGUARD 跳线设置
'''
translate = '''
### TMC STALLGUARD 跳线设置
'''

[[block]]
key = "1bf07e591be34c04"
origin = '''
可在下图所示的位置找到用于将诊断输出引脚连接到支持安装保护功能（TMC2209/TMC2226等）的驱动器端部停止输入的“diag”跳线。
'''
translate = '''
可在下图所示的位置找到用于将诊断输出引脚连接到支持安装保护功能（TMC2209/TMC2226等）的驱动器端部停止输入的“diag”跳线。
'''

[[block]]
key = "8b15b3fbc1f3d27e"
origin = '''
确切的diag编号可以通过查看引脚文件或板下的丝印来找到。
'''
translate = '''
确切的diag编号可以通过查看引脚文件或板下的丝印来找到。
'''

[[block]]
key = "26cfd77cbb352a08"
origin = '''
<ImageView src={require('./img/octopus-pro-driver-spi.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-driver-spi.png').default} width="80%"/>
'''

[[block]]
key = "a0e031fd38e1cde6"
origin = '''
### MAX 31865
'''
translate = '''
### MAX 31865
'''

[[block]]
key = "0242f424768bbe93"
origin = '''
<div class="div-table">

<ImageView src={require('./img/octopus-pro-max-31865.png').default} width="50%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<ImageView src={require('@site/docs/board-docs/octopus-series/octopus-pro/img/octopus-pro-max-31865.png').default} width="50%" class="right-image"/>
'''

[[block]]
key = "8524c8a185a6a9f3"
origin = '''
MAX 31865 选择 PT100/PT1000 2线或4线配置
'''
translate = '''
MAX 31865 选择 PT100/PT1000 2线或4线配置
'''

[[block]]
key = "151c84176ac833f0"
origin = '''
| 1   | 2   | 3   | 4   | Sensor Model  |
| --- | --- | --- | --- | ------------- |
| ON  | ON  | ON  | OFF | 2 wire PT100  |
| ON  | ON  | OFF | ON  | 2 wire PT1000 |
| OFF | OFF | ON  | OFF | 4 wire PT100  |
| OFF | OFF | OFF | ON  | 4 wire PT1000 |
'''
translate = '''
| 1   | 2   | 3   | 4   | Sensor Model  |
| --- | --- | --- | --- | ------------- |
| ON  | ON  | ON  | OFF | 2 wire PT100  |
| ON  | ON  | OFF | ON  | 2 wire PT1000 |
| OFF | OFF | ON  | OFF | 4 wire PT100  |
| OFF | OFF | OFF | ON  | 4 wire PT1000 |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''
