[metadata]

[[block]]
key = "0178d67d43d44577"
origin = '''
---
sidebar_position: 1
description: MMB CAN V2.0 简介
---
'''
translate = '''
---
sidebar_position: 1
description: MMB CAN V2.0 Introduction
---
'''

[[block]]
key = "544e66ecf329062f"
origin = '''
# MMB CAN V2.0
'''
translate = '''
# MMB CAN V2.0
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "744a1a9d0f69411c"
origin = '''
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
'''
translate = '''
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "263b106671f87e97"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-title.webp').default}
	width="40%"
	class="right-image"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-title.webp').default}
	width="40%"
	class="right-image"
/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## Product Introduction
'''

[[block]]
key = "b8709ea3383c8797"
origin = '''
BIGTREETECH MMB CAN V2.0是深圳市必趣创新科技有限公司3D打印团队针对多色挤出机制作的挤出控制板，可以通过USB或者CAN进行通讯，大大简化接线。
针对MMB CAN V1遇到的同时控制多个舵机时可能会出现电流不足的问题进行了改良，将5V供电的最大输出电流提升至7A，并增加了一些必要的防护。
'''
translate = '''
The BIGTREETECH MMB CAN V2.0 is a buddy board designed specifically for the ERCF V2, co-developed by BIGTREETECH and the ERCF Team. 
It is optimized to enhance the stability and responsiveness of multi-color operation in the ERCF V2, ensuring excellent compatibility and performance for this kit.
'''

[[block]]
key = "3793c167c87a1c58"
origin = '''
## 产品特点
'''
translate = '''
## Product Features
'''

[[block]]
key = "b34502521811f3c1"
origin = '''
- 主板预留BOOT和RESET按键，用户可以通过USB进入DFU模式更新固件。
- 预留I2C接口，此端口也可用于耗材检测，或者进行其它功能的DIY操作。
- 电源接口有防反接保护，避免客户在DIY时接反电源线导致板子烧毁。
- 支持CAN或USB通讯，其中CAN的终端电阻120R可通过跳线帽选择，且预留CAN拓展接口。
- USB口增设ESD保护芯片，防止主控被USB口静电击穿。
- 采用艾迈斯接口进行CAN通讯及主板供电，让接线简单化。
- 步进电机驱动支持高压，方便客户DIY使用
'''
translate = '''
- The board contains BOOT and RESET buttons to enter DFU mode when updating firmware using USB.
- An I2C interface is provided for filament detection or DIY capabilities.
- The power input interface is equipped with reverse polarity protection to prevent damage to the board if the power supply is connected incorrectly during DIY projects.
- The board supports both CAN and USB communication protocols. The CAN terminal resistor (120Ω) can be selected via a jumper, and a CAN expansion interface is reserved.
- The USB port features an ESD protection chip to safeguard the MCU against potential static discharge damage.
- The board utilizes an XT30 interface for both CAN communication and power supply, streamlining the wiring process.
- The stepper motor driver interface supports high-voltage operation, enabling enhanced DIY customization options.
'''

[[block]]
key = "45f9a82242e0d4ef"
origin = '''
## 产品参数
'''
translate = '''
## Specifications
'''

[[block]]
key = "a7e5bcefa312fb3c"
origin = '''
| **外观尺寸**                |                         **108.26mm x 59mm**                          |
| :--------------------------- | :------------------------------------------------------------------: |
| **安装尺寸**                |          **详情请参考：BIGTREETECH MMB CAN V2.0-SIZE.pdf**           |
| **微处理器**                |                **ARM Cortex-M0+ STM32G0B1RET6 64MHz**                |
| **输入电压**                |                           **DC12V-DC60V**                            |
| **输入电流**                |                                **9A**                                |
| **逻辑电压**                |                             **DC 3.3V**                              |
| **舵机接口（MOT）最大输出** |                         **5V 2A，峰值2.5A**                          |
| **拓展接口**                | **STP1-STP11，I2C，RGB，Sensor（红外传感器接口），USB接口，CAN接口** |
| **电机驱动支持**            |                            **EZ系列驱动**                            |
| **驱动工作模式**            |                       **STEP/DIR, UART, SPI**                        |
| **步进电机接口**            |                          **M1，M2，M3，M4**                          |
| **USB通信接口**             |                            **USB Type-C**                            |
| **DCDC 5V输出最大电流**     |                                **7A**                                |
'''
translate = '''
| **Dimensions** | **108.26mm x 59mm** |
| :--- | :---: |
| **Mounting Dimensions** | **For details, please refer to: BIGTREETECH MMB CAN V2.0-SIZE.pdf** |
| **Microprocessor** | **ARM Cortex-M0+ STM32G0B1RET6 64MHz** |
| **Input Voltage** | **DC12V-DC60V** |
| **Input Current** | **9A** |
| **Logic Voltage** | **DC 3.3V** |
| **Servo (MOT) Max Output** | **5V 2A, peak 2.5A** |
| **Expansion Interfaces** | **STP1-STP11, I2C, RGB, Sensor (IR sensor interface), USB port, CAN port** |
| **Motor Driver Support** | **EZ Series Drivers** |
| **Driver Operating Modes** | **STEP/DIR, UART, SPI** |
| **Motor Interfaces** | **M1, M2, M3, M4** |
| **USB Communication** | **USB Type-C** |
| **DCDC 5V Max Current** | **7A** |
'''
