[metadata]

[[block]]
key = "23bf5690fbf9f3a7"
origin = '''
---
sidebar_position: 2
description: MMB CAN V2.0 硬件功能
---
'''
translate = '''
---
sidebar_position: 2
description: MMB CAN V2.0 Hardware Features
---
'''

[[block]]
key = "b069379743358525"
origin = '''
# MMB CAN V2.0 硬件功能
'''
translate = '''
# MMB CAN V2.0 Hardware Features
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "744a1a9d0f69411c"
origin = '''
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
'''
translate = '''
import Tabs from "@theme/Tabs";
import TabItem from "@theme/TabItem";
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e4e43b6d7201907d"
origin = '''
## 外观尺寸
'''
translate = '''
## Dimensions
'''

[[block]]
key = "5b60f763863d7fa4"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-dimensions.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-dimensions.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "5b893cdd7e60f1bb"
origin = '''
:::tip[3D 参考文件]

MMB CAN V2.0 模型 [bigtreetech/MMB/3D/BIGTREETECH MMB CAN V2.0-3D.step](https://github.com/bigtreetech/MMB/blob/master/3D/BIGTREETECH%20MMB%20CAN%20V2.0-3D.step)

:::
'''
translate = '''
:::tip[3D STEP File]

MMB CAN V2.0 Model [bigtreetech/MMB/3D/BIGTREETECH MMB CAN V2.0-3D.step](https://github.com/bigtreetech/MMB/blob/master/3D/BIGTREETECH%20MMB%20CAN%20V2.0-3D.step)

:::
'''

[[block]]
key = "6b910fe79dd6f70a"
origin = '''
## 引脚说明
'''
translate = '''
## Pin Description
'''

[[block]]
key = "1a33d2579218274f"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-pin.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-pin.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "034757710bdf8540"
origin = '''
:::tip[原理图 / SCHEMATIC]

MMB CAN V2.0 原理图 [BIGTREETECH MMB CAN V2.0-SCH.pdf](https://github.com/bigtreetech/MMB/blob/master/Hardware/V2.0/BIGTREETECH%20MMB%20CAN%20V2.0-SCH.pdf)

:::
'''
translate = '''
:::tip[Schematic Diagram]

MMB CAN V2.0 Schematic Diagram [BIGTREETECH MMB CAN V2.0-SCH.pdf](https://github.com/bigtreetech/MMB/blob/master/Hardware/V2.0/BIGTREETECH%20MMB%20CAN%20V2.0-SCH.pdf)

:::
'''

[[block]]
key = "465a0d3a27e44929"
origin = '''
## 硬件功能配置
'''
translate = '''
## Interface Introduction
'''

[[block]]
key = "83e4703555823190"
origin = '''
### USB 供电
'''
translate = '''
### USB Power Supply
'''

[[block]]
key = "5ef29a87295a6203"
origin = '''
主板上电之后， 电源灯会亮起，表示供电正常。板上标识VUSB是电源选择端，仅当使用USB给主板供电时，才需要使用跳帽将VUSB短接。
'''
translate = '''
When the board is powered on, the power indicator light will turn on to confirm that the power supply is functioning correctly. The VUSB terminal on the board is the power selection terminal, which should only be shorted with a jumper when powering through USB.
'''

[[block]]
key = "d93824dd7b490000"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-usb.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-usb.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "f95d7e9c05b4c225"
origin = '''
### 舵机接口
'''
translate = '''
### Servo Interface
'''

[[block]]
key = "96845378ad66b1e4"
origin = '''
:::info[注意]
此处演示为使用MMB的板载DC-DC为舵机供电。

MMB CAN V2 在舵机输出口添加了一枚3A的自恢复保险丝用以避免电源触发短路保护，足以胜任该应用。但需确保其接入MOT1或MOT2连接器，且尽量避免同步动作，或开启`servo_always_active: 1`来允许舵机重启后仍有持续的控制信号。
:::
'''
translate = '''
:::info[Note]
This demonstration shows using the MMB's onboard DC-DC module to power the servo.

The MMB CAN V2 features an added 3A resettable fuse at the servo output port to prevent the power supply from triggering short-circuit protection, making it fully capable of handling this application. However, please ensure it is connected to the MOT1 or MOT2 connector, minimize simultaneous movements, or enable `servo_always_active: 1` to maintain continuous control signals even after a servo reset.
:::
'''

[[block]]
key = "570622432222a412"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-mot.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-mot.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "c5ba87e7a93379bf"
origin = '''
### Neopixel
'''
translate = '''
### Neopixel Wiring
'''

[[block]]
key = "bc626bcc734e0be4"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-rgb.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-rgb.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "b844b1869edcadd8"
origin = '''
### 编码器接线
'''
translate = '''
### Encoder Wiring
'''

[[block]]
key = "8172700cf9738b13"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-sensor.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-sensor.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "dc850f8205b50255"
origin = '''
### IIC 接线
'''
translate = '''
### I2C Wiring
'''

[[block]]
key = "62b7a85dea16fc1c"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-i2c.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-i2c.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''

[[block]]
key = "e9d0b93c08ed8605"
origin = '''
### 限位开关
'''
translate = '''
### Endstops Wiring
'''

[[block]]
key = "f1f05836aeb32273"
origin = '''
<ImageView
	src={require('./img/mmb-can-v2-0-endstop.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
translate = '''
<ImageView
	src={require('@site/docs/board-docs/mmb-series/mmb-2/img/mmb-can-v2-0-endstop.webp').default}
	alt="mmb can v2"
	width="80%"
/>
'''
