[metadata]

[[block]]
key = "49acf3845a479582"
origin = '''
---
sidebar_position: 1
description: TFT 43 DIP 文档
---
'''
translate = '''
---
sidebar_position: 1
description: TFT 43 DIP 文档
---
'''

[[block]]
key = "145aa530f0cce7e3"
origin = '''
# TFT 43 DIP
'''
translate = '''
# TFT 43 DIP
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "7d0794832c568ab6"
origin = '''
<div class="div-table">

<ImageView src={require('./img/TFT43_DIP_Title.png').default} width="45%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<ImageView src={require('@site/docs/accessories-docs/display/TFT43-DIP/img/TFT43_DIP_Title.png').default} width="45%" class="right-image"/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## 产品简介
'''

[[block]]
key = "bd7f04377572c7ea"
origin = '''
TFT43-DIP是带电容式触摸屏的树莓派显示器。
'''
translate = '''
TFT43-DIP是带电容式触摸屏的树莓派显示器。
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "0bb80755db66cf58"
origin = '''
## 软件配置
'''
translate = '''
## 软件配置
'''

[[block]]
key = "193c8b806198d5d8"
origin = '''
:::note

"2022-04-04"之后的Raspberry Pi操作系统具有内置的DPI驱动程序，因此我们只需要在 `/boot/config.txt` 文件中进行简单配置即可使用此屏幕。

"2022-09-22"的操作系统显示180度旋转功能异常，请不要使用。

::: 
'''
translate = '''
:::note

"2022-04-04"之后的Raspberry Pi操作系统具有内置的DPI驱动程序，因此我们只需要在 `/boot/config.txt` 文件中进行简单配置即可使用此屏幕。

"2022-09-22"的操作系统显示180度旋转功能异常，请不要使用。

::: 
'''

[[block]]
key = "a14c4723928838da"
origin = '''
### 显示功能
'''
translate = '''
### 显示功能
'''

[[block]]
key = "388bca0febb10813"
origin = '''
将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分。(通常，它可以添加到/boot/config.txt文件的底部)
'''
translate = '''
将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分。(通常，它可以添加到/boot/config.txt文件的底部)
'''

[[block]]
key = "33cf979fdac177f4"
origin = '''
```systemd title="/boot/config.txt"
dtoverlay=vc4-kms-dpi-generic
dtparam=rgb666-padhi,clock-frequency=32000000
dtparam=hactive=800,hfp=16,hsync=1,hbp=46
dtparam=vactive=480,vfp=7,vsync=3,vbp=23
dtparam=backlight-gpio=19
dtparam=rotate=0
```
'''
translate = '''
```systemd title="/boot/config.txt"
dtoverlay=vc4-kms-dpi-generic
dtparam=rgb666-padhi,clock-frequency=32000000
dtparam=hactive=800,hfp=16,hsync=1,hbp=46
dtparam=vactive=480,vfp=7,vsync=3,vbp=23
dtparam=backlight-gpio=19
dtparam=rotate=0
```
'''

[[block]]
key = "24e6783e681bee7f"
origin = '''
:::info[配置显示器旋转]

`rotate=显示旋转` 可设置的值包括 `0`, `90`, `180`, `270`。默认值为 `0`

:::
'''
translate = '''
:::info[配置显示器旋转]

`rotate=显示旋转` 可设置的值包括 `0`, `90`, `180`, `270`。默认值为 `0`

:::
'''

[[block]]
key = "54b81951dee31e1d"
origin = '''
### 触摸功能
'''
translate = '''
### 触摸功能
'''

[[block]]
key = "c1377905cc1357cf"
origin = '''
使用以下命令下载配置文件
'''
translate = '''
使用以下命令下载配置文件
'''

[[block]]
key = "99fdc27fcf145e7d"
origin = '''
```shell
sudo wget https://raw.githubusercontent.com/bigtreetech/TFT43-DIP/master/gt911_btt_tft43_dip.dtbo -O /boot/overlays/gt911_btt_tft43_dip.dtbo
```
'''
translate = '''
```shell
sudo wget https://raw.githubusercontent.com/bigtreetech/TFT43-DIP/master/gt911_btt_tft43_dip.dtbo -O /boot/overlays/gt911_btt_tft43_dip.dtbo
```
'''

[[block]]
key = "9137ae48e112812e"
origin = '''
并将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分。
'''
translate = '''
并将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分。
'''

[[block]]
key = "7e1e4c85df318438"
origin = '''
``` systemd title="/boot/config.txt"
dtoverlay=gt911_btt_tft43_dip
dtparam=rotate_0
```
'''
translate = '''
``` systemd title="/boot/config.txt"
dtoverlay=gt911_btt_tft43_dip
dtparam=rotate_0
```
'''

[[block]]
key = "264f2eee5403128e"
origin = '''
:::info[旋转触摸]

`rotate_*` 是触摸旋转，可设置为 `rotate_0`, `rotate_90`, `rotate_180`, `rotate_270` 与显示器旋转相对应

:::
'''
translate = '''
:::info[旋转触摸]

`rotate_*` 是触摸旋转，可设置为 `rotate_0`, `rotate_90`, `rotate_180`, `rotate_270` 与显示器旋转相对应

:::
'''

[[block]]
key = "f1d16fdc695d1920"
origin = '''
## 示例配置文件
'''
translate = '''
## 示例配置文件
'''

[[block]]
key = "45117cedadaebfed"
origin = '''
### 正常显示
'''
translate = '''
### 正常显示
'''

[[block]]
key = "ad2680c978c24de2"
origin = '''
复制 gt911_btt_tft43_dip.dtbo（./gt911_bttl_tft43.dtbo）文件
'''
translate = '''
复制 gt911_btt_tft43_dip.dtbo（./gt911_bttl_tft43.dtbo）文件
'''

[[block]]
key = "1a8aa4c59736bbc4"
origin = '''
将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分
'''
translate = '''
将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分
'''

[[block]]
key = "e1916c97ec1c0d4d"
origin = '''
```systemd title="/boot/config.txt"
dtoverlay=vc4-kms-dpi-generic
dtparam=rgb666-padhi,clock-frequency=32000000
dtparam=hactive=800,hfp=16,hsync=1,hbp=46
dtparam=vactive=480,vfp=7,vsync=3,vbp=23
dtparam=backlight-gpio=19
dtparam=rotate=0
'''
translate = '''
```systemd title="/boot/config.txt"
dtoverlay=vc4-kms-dpi-generic
dtparam=rgb666-padhi,clock-frequency=32000000
dtparam=hactive=800,hfp=16,hsync=1,hbp=46
dtparam=vactive=480,vfp=7,vsync=3,vbp=23
dtparam=backlight-gpio=19
dtparam=rotate=0
'''

[[block]]
key = "0d9bd62749184fb8"
origin = '''
dtoverlay=gt911_btt_tft43_dip
dtparam=rotate_0
```
'''
translate = '''
dtoverlay=gt911_btt_tft43_dip
dtparam=rotate_0
```
'''

[[block]]
key = "7ef37dd1b1fde234"
origin = '''
### 旋转90度显示
'''
translate = '''
### 旋转90度显示
'''

[[block]]
key = "ad2680c978c24de2"
origin = '''
复制 gt911_btt_tft43_dip.dtbo（./gt911_bttl_tft43.dtbo）文件
'''
translate = '''
复制 gt911_btt_tft43_dip.dtbo（./gt911_bttl_tft43.dtbo）文件
'''

[[block]]
key = "1a8aa4c59736bbc4"
origin = '''
将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分
'''
translate = '''
将以下配置添加到 `/boot/config.txt` 文件的 `[all]` 部分
'''

[[block]]
key = "a8734c692572f29a"
origin = '''
```systemd title="/boot/config.txt"
dtoverlay=vc4-kms-dpi-generic
dtparam=rgb666-padhi,clock-frequency=32000000
dtparam=hactive=800,hfp=16,hsync=1,hbp=46
dtparam=vactive=480,vfp=7,vsync=3,vbp=23
dtparam=backlight-gpio=19
dtparam=rotate=90
'''
translate = '''
```systemd title="/boot/config.txt"
dtoverlay=vc4-kms-dpi-generic
dtparam=rgb666-padhi,clock-frequency=32000000
dtparam=hactive=800,hfp=16,hsync=1,hbp=46
dtparam=vactive=480,vfp=7,vsync=3,vbp=23
dtparam=backlight-gpio=19
dtparam=rotate=90
'''

[[block]]
key = "75cc5dd0a81bf62e"
origin = '''
dtoverlay=gt911_btt_tft43_dip
dtparam=rotate_90
```
'''
translate = '''
dtoverlay=gt911_btt_tft43_dip
dtparam=rotate_90
```
'''
