[metadata]

[[block]]
key = "78d04f42aac2c182"
origin = '''
---
sidebar_position: 10
---
'''
translate = '''
---
sidebar_position: 10
---
'''

[[block]]
key = "e0ef5753334fc48c"
origin = '''
# EZ 系列引脚
'''
translate = '''
# EZ 系列引脚
'''

[[block]]
key = "a03f0e582c476999"
origin = '''
EZ 驱动的引脚图
'''
translate = '''
EZ 驱动的引脚图
'''

[[block]]
key = "5a51d25329e19dbf"
origin = '''
import EZPin1 from "./img/ez-pin-1.svg";
'''
translate = '''
import EZPin1 from "@site/docs/accessories-docs/ez-series/img/ez-pin-1.svg";
'''

[[block]]
key = "0d0cc6dea05facf3"
origin = '''
<EZPin1 class="left-image" width="40%" height="auto"/>
'''
translate = '''
<EZPin1 class="left-image" width="40%" height="auto"/>
'''

[[block]]
key = "eb4a81a90b8805b9"
origin = '''
import EZPin2 from "./img/ez-pin-2.svg";
'''
translate = '''
import EZPin2 from "@site/docs/accessories-docs/ez-series/img/ez-pin-2.svg";
'''

[[block]]
key = "e988720952b8d944"
origin = '''
<EZPin2 class="right-image" width="40%" height="auto"/>
'''
translate = '''
<EZPin2 class="right-image" width="40%" height="auto"/>
'''
