[metadata]

[[block]]
key = "0ce2a22d8e0bff16"
origin = '''
---
sidebar_position: 1
description: EBB 36 Gen 1 工具板
---
'''
translate = '''
---
sidebar_position: 1
description: EBB 36 Gen 1 工具板
---
'''

[[block]]
key = "4f19696fc8a13cf1"
origin = '''
# EBB 36 Gen 1
'''
translate = '''
# EBB 36 Gen 1
'''

[[block]]
key = "620cc612f9e710b6"
origin = '''
EBB 36 CAN 板说明文档
'''
translate = '''
EBB 36 CAN 板说明文档
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "9a4d9968e431e52b"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocCardList from '@theme/DocCardList';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocCardList from '@theme/DocCardList';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "4b6dbad446fc91dc"
origin = '''
<ImageView
    src={require('./img/ebb_36_title.png').default}
    alt="ebb 36 title" width="550"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/board-docs/ebb-series/ebb-36/img/ebb_36_title.png').default}
    alt="ebb 36 title" width="550"
/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## 产品简介
'''

[[block]]
key = "97b4855f03269c86"
origin = '''
BIGTREETECH EBB36 CAN V1.0/V1.1/v1.2 是一个用于简化工具头接线的工具头 CAN 板。EBB 36 可以通过 USB 端口或 CAN 总线进行通信，极大的简化了 3D 打印机工具头的接线和走线。
'''
translate = '''
BIGTREETECH EBB36 CAN V1.0/V1.1/v1.2 是一个用于简化工具头接线的工具头 CAN 板。EBB 36 可以通过 USB 端口或 CAN 总线进行通信，极大的简化了 3D 打印机工具头的接线和走线。
'''

[[block]]
key = "00d8c66044e511be"
origin = '''
:::info[固件支持]
EBB 36 V1.0/V1.1/V1.2 目前只支持 Klipper 固件
:::
'''
translate = '''
:::info[固件支持]
EBB 36 V1.0/V1.1/V1.2 目前只支持 Klipper 固件
:::
'''

[[block]]
key = "cc93f65bfb52fa05"
origin = '''
## 硬件规格
'''
translate = '''
## 硬件规格
'''

[[block]]
key = "9ec0c4f3f079c64d"
origin = '''
| EBB 36 CAN       | Specification                                                                          |
| ---------------- | -------------------------------------------------------------------------------------- |
| 外形尺寸         | 51.5mm x 37mm                                                                          |
| MCU              | ARM Cortex-M0+STM32G0B1CBT6 64MHz (v1.1/v1.2) ARM Cortex-M0 STM32F072C8T6 48MHz (v1.0) |
| 输入电压         | DC 12V - DC 24V 6A                                                                     |
| 逻辑电压         | DC 3.3V                                                                                |
| 热端加热接口     | 5A                                                                                     |
| 板载加速度传感器 | ADXL345                                                                                |
| 电机驱动         | TMC 2209                                                                               |
'''
translate = '''
| EBB 36 CAN       | Specification                                                                          |
| ---------------- | -------------------------------------------------------------------------------------- |
| 外形尺寸         | 51.5mm x 37mm                                                                          |
| MCU              | ARM Cortex-M0+STM32G0B1CBT6 64MHz (v1.1/v1.2) ARM Cortex-M0 STM32F072C8T6 48MHz (v1.0) |
| 输入电压         | DC 12V - DC 24V 6A                                                                     |
| 逻辑电压         | DC 3.3V                                                                                |
| 热端加热接口     | 5A                                                                                     |
| 板载加速度传感器 | ADXL345                                                                                |
| 电机驱动         | TMC 2209                                                                               |
'''

[[block]]
key = "d3ac9811ffbf8210"
origin = '''
<DocCardList />
'''
translate = '''
<DocCardList />
'''
