[metadata]

[[block]]
key = "1ecc15ff390b2db4"
origin = '''
---
sidebar_position: 3
---
'''
translate = '''
---
sidebar_position: 3
---
'''

[[block]]
key = "9b358d21e069bf56"
origin = '''
# EBB 36 CAN 固件配置
'''
translate = '''
# EBB 36 CAN Firmware
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "00d8c66044e511be"
origin = '''
:::info[固件支持]
EBB 36 V1.0/V1.1/V1.2 目前只支持 Klipper 固件
:::
'''
translate = '''
:::info[Firmware Support]
EBB 36 V1.0/V1.1/V1.2 currently only supports Klipper firmware
:::
'''

[[block]]
key = "710dc62b3fd1deb6"
origin = '''
## 写入 Klipper 固件
'''
translate = '''
## Flashing Klipper Firmware
'''

[[block]]
key = "9ad86f7b4e732105"
origin = '''
EBB 36 v1.1 / v1.2 写入 Klipper 固件参考 [EBB 系列固件 (STM32G0B1)](../ebb-firmware-g0b1.md)
'''
translate = '''
For EBB 36 v1.1 / v1.2, refer to [EBB Series Firmware (STM32G0B1)](../ebb-firmware-g0b1.md) for flashing Klipper firmware.
'''

[[block]]
key = "685cb0036ccfd69b"
origin = '''
EBB 36 v1.0 写入 Klipper 固件参考 [EBB 系列固件 (STM32F072)](../ebb-firmware-f072.md)
'''
translate = '''
For EBB 36 v1.0, refer to [EBB Series Firmware (STM32F072)](../ebb-firmware-f072.md) for flashing Klipper firmware.
'''

[[block]]
key = "97a654915a067474"
origin = '''
## Klipper 配置文件参考
'''
translate = '''
## Klipper Configuration Reference
'''

[[block]]
key = "3d3f2203d8429368"
origin = '''
``` klipper_cfg title="printer.cfg"
[mcu EBBCan]
canbus_uuid: 11aa22bb33cc
'''
translate = '''
``` klipper_cfg title="printer.cfg"
[mcu EBBCan]
canbus_uuid: 11aa22bb33cc
'''

[[block]]
key = "08a1abba7cdc67fd"
origin = '''
[adxl345]
cs_pin: EBBCan: PB12
spi_software_sclk_pin: EBBCan: PB10
spi_software_mosi_pin: EBBCan: PB11
spi_software_miso_pin: EBBCan: PB2
axes_map: x,y,z
'''
translate = '''
[adxl345]
cs_pin: EBBCan: PB12
spi_software_sclk_pin: EBBCan: PB10
spi_software_mosi_pin: EBBCan: PB11
spi_software_miso_pin: EBBCan: PB2
axes_map: x,y,z
'''

[[block]]
key = "b4adf602d22c7ec8"
origin = '''
[extruder]
step_pin: EBBCan: PD0
dir_pin: !EBBCan: PD1
enable_pin: !EBBCan: PD2
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: EBBCan: PB13
sensor_type: EPCOS 100K B57560G104F
sensor_pin: EBBCan: PA3
control: pid
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250
'''
translate = '''
[extruder]
step_pin: EBBCan: PD0
dir_pin: !EBBCan: PD1
enable_pin: !EBBCan: PD2
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: EBBCan: PB13
sensor_type: EPCOS 100K B57560G104F
sensor_pin: EBBCan: PA3
control: pid
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250
'''

[[block]]
key = "154e4efe2d5b0908"
origin = '''
# sensor_type: MAX31865
'''
translate = '''
# sensor_type: MAX31865
'''

[[block]]
key = "df117df3756db04d"
origin = '''
# sensor_pin: EBBCan: PA4
'''
translate = '''
# sensor_pin: EBBCan: PA4
'''

[[block]]
key = "da96b28db19eaee0"
origin = '''
# spi_bus: spi1
'''
translate = '''
# spi_bus: spi1
'''

[[block]]
key = "a3b881ac8fbda254"
origin = '''
# rtd_nominal_r: 100
'''
translate = '''
# rtd_nominal_r: 100
'''

[[block]]
key = "cd96be72bcc40044"
origin = '''
# rtd_reference_r: 430
'''
translate = '''
# rtd_reference_r: 430
'''

[[block]]
key = "311d221d4aa0aad3"
origin = '''
# rtd_num_of_wires: 2
'''
translate = '''
# rtd_num_of_wires: 2
'''

[[block]]
key = "8a52b76db71ade6c"
origin = '''
[tmc2209 extruder]
uart_pin: EBBCan: PA15
run_current: 0.650
stealthchop_threshold: 999999
'''
translate = '''
[tmc2209 extruder]
uart_pin: EBBCan: PA15
run_current: 0.650
stealthchop_threshold: 999999
'''

[[block]]
key = "5674bd42faeaa55e"
origin = '''
[fan]
pin: EBBCan: PA0
'''
translate = '''
[fan]
pin: EBBCan: PA0
'''

[[block]]
key = "6facba0733077203"
origin = '''
[heater_fan hotend_fan]
pin: EBBCan: PA1
heater: extruder
heater_temp: 50.0
'''
translate = '''
[heater_fan hotend_fan]
pin: EBBCan: PA1
heater: extruder
heater_temp: 50.0
'''

[[block]]
key = "6562203e32b04bc3"
origin = '''
#[neopixel hotend_rgb]
'''
translate = '''
#[neopixel hotend_rgb]
'''

[[block]]
key = "1f9844871635c0f4"
origin = '''
#pin: EBBCan:PD3
'''
translate = '''
#pin: EBBCan:PD3
'''

[[block]]
key = "6fd25d1dc939266d"
origin = '''
#[bltouch]
'''
translate = '''
#[bltouch]
'''

[[block]]
key = "f85fd8fcbd6e6399"
origin = '''
#sensor_pin: ^EBBCan:PB8
'''
translate = '''
#sensor_pin: ^EBBCan:PB8
'''

[[block]]
key = "0b90714b2b101f00"
origin = '''
#control_pin: EBBCan:PB9
'''
translate = '''
#control_pin: EBBCan:PB9
'''

[[block]]
key = "dd01581268650aa3"
origin = '''
#[filament_switch_sensor switch_sensor]
'''
translate = '''
#[filament_switch_sensor switch_sensor]
'''

[[block]]
key = "964322aa0d5ccf84"
origin = '''
#switch_pin: EBBCan:PB4
'''
translate = '''
#switch_pin: EBBCan:PB4
'''

[[block]]
key = "8e3bbe06d560c28e"
origin = '''
#[filament_motion_sensor motion_sensor]
'''
translate = '''
#[filament_motion_sensor motion_sensor]
'''

[[block]]
key = "df40f61d2041e1df"
origin = '''
#switch_pin: ^EBBCan:PB3
'''
translate = '''
#switch_pin: ^EBBCan:PB3
'''

[[block]]
key = "3022884942eb05fa"
origin = '''
```
'''
translate = '''
```
'''
