[metadata]

[[block]]
key = "f033356e330d50b8"
origin = '''
---
sidebar_position: 2
---
'''
translate = '''
---
sidebar_position: 2
---
'''

[[block]]
key = "82bbf635b03cad7d"
origin = '''
# EBB 36 CAN 硬件功能
'''
translate = '''
# EBB 36 CAN Hardware 
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "00d8c66044e511be"
origin = '''
:::info[固件支持]
EBB 36 V1.0/V1.1/V1.2 目前只支持 Klipper 固件
:::
'''
translate = '''
:::info[Firmware support]

EBB 36 V1.0/V1.1/V1.2 currently only supports Klipper firmware

:::
'''

[[block]]
key = "e4e43b6d7201907d"
origin = '''
## 外观尺寸
'''
translate = '''
## Dimensions
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "871e53da6e31236a"
origin = '''
        <ImageView src={require('./img/G0B1/EBB_G0B1_Diagram.png').default} width="450"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_Diagram.png').default} width="450"/>
'''

[[block]]
key = "38320e68668713ae"
origin = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('./img/072/EBB_072_Diagram.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_Diagram.png').default} width="450"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "a2df1b4a41a65fdc"
origin = '''
## Pinout
'''
translate = '''
## Pinout
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "f41240fd45094fb1"
origin = '''
        <ImageView src={require('./img/G0B1/EBB_G0B1_Pin.png').default} width="450"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_Pin.png').default} width="450"/>
'''

[[block]]
key = "ce458dd8238afb06"
origin = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('./img/072/EBB_072_Pin.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_Pin.png').default} width="450"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "465a0d3a27e44929"
origin = '''
## 硬件功能配置
'''
translate = '''
## Hardware Function Configuration
'''

[[block]]
key = "f24f89cbf275581b"
origin = '''
### USB 接口供电
'''
translate = '''
### USB Power
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "6a50e7e41181a264"
origin = '''
        当 `EBB 36 v1.1 / v1.2` 通电的时候 LED1 才会亮起。`EBB 36` 右侧的 `VUSB` 是选择使用 USB 接口对 MCU 进行供电。
        <ImageView src={require('./img/G0B1/EBB_G0B1_USB_Power.png').default} width="450"/>
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        当 `EBB 36 v1.0` 通电的时候 `D1 LED` 才会亮起。`EBB 36` 上的 `VUSB` 是选择使用 USB 接口对 MCU 进行供电。
        <ImageView src={require('./img/072/EBB_072_USB_Power.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
        LED1 lights up only when `EBB 36 v1.1 / v1.2` is powered on. The `VUSB` on the right side of `EBB 36` is used to select USB interface power for the MCU.
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_USB_Power.png').default} width="450"/>
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        The `D1 LED` lights up only when `EBB 36 v1.0` is powered on. The `VUSB` on `EBB 36` is used to select USB interface power for the MCU.
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_USB_Power.png').default} width="450"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "72820f801e88b40d"
origin = '''
## 硬件安装
'''
translate = '''
## Hardware Installation
'''

[[block]]
key = "01163b0098b1a125"
origin = '''
### NTC 100K 或 PT1000 
'''
translate = '''
### NTC 100K or PT1000
'''

[[block]]
key = "cb6af9c619ffa128"
origin = '''
不带 31865 的版本： 使用 100K NTC 热敏电阻时无需插入跳线帽，`TH0`上拉电阻值为 `4.7K`。使用 `PT1000` 时，需要使用跳线帽将两个引脚短接，如下图所示。此时，`TH0`上拉电阻值为`2.2K`。
'''
translate = '''
For versions without 31865: When using a 100K NTC thermistor, no jumper is needed, and the `TH0` pull-up resistor value is `4.7K`. When using a `PT1000`, a jumper must short the two pins as shown below. At this point, the `TH0` pull-up resistor value is `2.2K`.
'''

[[block]]
key = "9311835c7e2a0b10"
origin = '''
:::info[温度准确性]
这样使用 `PT1000` 的温度准确性会比使用 `MAX31865` 低
:::
'''
translate = '''
:::info[Temperature Accuracy]
Using PT1000 in this way results in lower temperature accuracy compared to using `MAX31865`.
:::
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "8e59355a908cca6e"
origin = '''
        <ImageView src={require('./img/G0B1/EBB_G0B1_PT100.png').default} width="450"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_PT100.png').default} width="450"/>
'''

[[block]]
key = "58d0cd9a4a40ce67"
origin = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('./img/072/EBB_072_PT100.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_PT100.png').default} width="450"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "a0e031fd38e1cde6"
origin = '''
### MAX 31865
'''
translate = '''
### MAX 31865
'''

[[block]]
key = "80bcad525a167773"
origin = '''
<div class="div-table">
    <Tabs groupId="ebb-version">
'''
translate = '''
<div class="div-table">
    <Tabs groupId="ebb-version">
'''

[[block]]
key = "f8698247c77e1c22"
origin = '''
        <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
            <ImageView src={require('./img/G0B1/EBB_G0B1_TwoW.png').default} width="300" class="image-margin"/>
'''
translate = '''
        <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
            <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_TwoW.png').default} width="300" class="image-margin"/>
'''

[[block]]
key = "707e057b8b097de8"
origin = '''
            <ImageView src={require('./img/G0B1/EBB_G0B1_FourW.png').default} width="300" class="image-margin"/>
'''
translate = '''
            <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_FourW.png').default} width="300" class="image-margin"/>
'''

[[block]]
key = "3400ab8430e732c5"
origin = '''
        </TabItem>
        <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
            <ImageView src={require('./img/072/EBB_072_TwoW.png').default} width="300" class="image-margin"/>
            <ImageView src={require('./img/072/EBB_072_FourW.png').default} width="300" class="image-margin"/>
        </TabItem>
    </Tabs>
</div>
'''
translate = '''
        </TabItem>
        <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
            <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_TwoW.png').default} width="300" class="image-margin"/>
            <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_FourW.png').default} width="300" class="image-margin"/>
        </TabItem>
    </Tabs>
</div>
'''

[[block]]
key = "5953fc22bfc3c049"
origin = '''
:::info
MAX 31865 选择 PT100/PT1000 2线或4线配置

| 1   | 2   | 3   | 4   | Sensor Model  |
| --- | --- | --- | --- | ------------- |
| ON  | ON  | ON  | OFF | 2 wire PT100  |
| ON  | ON  | OFF | ON  | 2 wire PT1000 |
| OFF | OFF | ON  | OFF | 4 wire PT100  |
| OFF | OFF | OFF | ON  | 4 wire PT1000 |
:::
'''
translate = '''
:::info
MAX 31865 selects PT100/PT1000 2-wire or 4-wire configuration

| 1   | 2   | 3   | 4   | Sensor Model  |
| --- | --- | --- | --- | ------------- |
| ON  | ON  | ON  | OFF | 2 wire PT100  |
| ON  | ON  | OFF | ON  | 2 wire PT1000 |
| OFF | OFF | ON  | OFF | 4 wire PT100  |
| OFF | OFF | OFF | ON  | 4 wire PT1000 |
:::
'''

[[block]]
key = "959d166b5d6adaff"
origin = '''
### BL-Touch 接线
'''
translate = '''
### BL-Touch wire
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "46ad33e14718fbdc"
origin = '''
        <ImageView src={require('./img/G0B1/EBB_G0B1_BLTouch.png').default} width="450"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_BLTouch.png').default} width="450"/>
'''

[[block]]
key = "abe2b4eb2e45caab"
origin = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('./img/072/EBB_072_BLTouch.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_BLTouch.png').default} width="450"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "b0593a3f25c4d84e"
origin = '''
### 耗材传感器
'''
translate = '''
### Filament Sensor
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "6c8ad518d2316a0a"
origin = '''
        <ImageView src={require('./img/G0B1/EBB_G0B1_Broke.png').default} width="450"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_Broke.png').default} width="450"/>
'''

[[block]]
key = "e3bd22926c90d36a"
origin = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('./img/072/EBB_072_Broke.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_Broke.png').default} width="450"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "c5ba87e7a93379bf"
origin = '''
### Neopixel
'''
translate = '''
### Neopixel
'''

[[block]]
key = "66c33e97bd2a016e"
origin = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''
translate = '''
<Tabs groupId="ebb-version">
    <TabItem value="ebb-36-1_2" label="EBB 36 V1.1 / V1.2" default>
'''

[[block]]
key = "4a3b4a79c3106f15"
origin = '''
        <ImageView src={require('./img/G0B1/EBB_G0B1_RGB.png').default} width="450"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/G0B1/EBB_G0B1_RGB.png').default} width="450"/>
'''

[[block]]
key = "3ea7b7920fa7582f"
origin = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('./img/072/EBB_072_RGB.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="ebb-36-1_0" label="EBB 36 V1.0">
        <ImageView src={require('@site/docs/board-docs/ebb-series/ebb-36/img/072/EBB_072_RGB.png').default} width="450"/>
    </TabItem>
</Tabs>
'''
