[metadata]

[[block]]
key = "3c1d9c66cd14e524"
origin = '''
# Panda Breeze
'''
translate = '''
# Panda Breeze
'''

[[block]]
key = "27d2ed874dee84d6"
origin = '''
<div class="div-table">

<ImageView src={require('./img/panda_breeze.webp').default} width="40%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze.webp').default} width="40%" class="right-image"/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## 产品简介
'''

[[block]]
key = "3c75dfe988c015cc"
origin = '''
BIQU Panda Breeze 专为 Bambu Lab A1 打印机设计，安装于 X 轴，采用恒流风机，实现均匀送风与大面积覆盖，有效改善搭桥、垂悬与精细部位的成型质量。
'''
translate = '''
BIQU Panda Breeze 专为 Bambu Lab A1 打印机设计，安装于 X 轴，采用恒流风机，实现均匀送风与大面积覆盖，有效改善搭桥、垂悬与精细部位的成型质量。
'''

[[block]]
key = "3793c167c87a1c58"
origin = '''
## 产品特点
'''
translate = '''
## 产品特点
'''

[[block]]
key = "99547e9d20e60989"
origin = '''
**横流风机:** 风力均匀，大面积覆盖，实现精准冷却。
'''
translate = '''
**横流风机:** 风力均匀，大面积覆盖，实现精准冷却。
'''

[[block]]
key = "7954b2f8f162cad7"
origin = '''
**打印质量提升:**  显著改善桥接、垂悬与细节打印效果。
'''
translate = '''
**打印质量提升:**  显著改善桥接、垂悬与细节打印效果。
'''

[[block]]
key = "8cf30ed2ae609662"
origin = '''
**即插即用:** 对接原有安装孔和电源孔，无需改动。
'''
translate = '''
**即插即用:** 对接原有安装孔和电源孔，无需改动。
'''

[[block]]
key = "c7a8363740cee16d"
origin = '''
**坚固结构:** 高品质铝合金机身，兼顾强度与耐用性。
'''
translate = '''
**坚固结构:** 高品质铝合金机身，兼顾强度与耐用性。
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "1d4d588a0053c343"
origin = '''
## 安装指南
'''
translate = '''
## 安装指南
'''

[[block]]
key = "e985759532f1490a"
origin = '''
**步骤1：安装Panda Breeze**
'''
translate = '''
**步骤1：安装Panda Breeze**
'''

[[block]]
key = "e667ce32d35ceabd"
origin = '''
1、使用H2.0螺丝刀取下X轴后方的两颗螺丝，如下图所示。
'''
translate = '''
1、使用H2.0螺丝刀取下X轴后方的两颗螺丝，如下图所示。
'''

[[block]]
key = "ee473502deab9703"
origin = '''
<ImageView src={require('./img/panda_breeze_installation1.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation1.webp').default} width="80%"/>
'''

[[block]]
key = "6049e48e235e53a2"
origin = '''
2、复用取下的螺丝，将Panda Breeze与X轴后方的螺丝孔对准后拧紧螺丝以将Panda Breeze牢固地固定在X轴后方。
'''
translate = '''
2、复用取下的螺丝，将Panda Breeze与X轴后方的螺丝孔对准后拧紧螺丝以将Panda Breeze牢固地固定在X轴后方。
'''

[[block]]
key = "bc8b51c6fe4dfed6"
origin = '''
<ImageView src={require('./img/panda_breeze_installation2.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation2.webp').default} width="80%"/>
'''

[[block]]
key = "acb1df7614ceb6b1"
origin = '''
<ImageView src={require('./img/panda_breeze_installation3.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation3.webp').default} width="80%"/>
'''

[[block]]
key = "9153655bf57d1e41"
origin = '''
**步骤2：安装转接板**
'''
translate = '''
**步骤2：安装转接板**
'''

[[block]]
key = "00aec55fed7def82"
origin = '''
<ImageView src={require('./img/panda_breeze_installation4.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation4.webp').default} width="80%"/>
'''

[[block]]
key = "24bc93a66b095771"
origin = '''
<ImageView src={require('./img/panda_breeze_installation5.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation5.webp').default} width="80%"/>
'''

[[block]]
key = "cb75050958845dc8"
origin = '''
**步骤3：接线**
'''
translate = '''
**步骤3：接线**
'''

[[block]]
key = "7fe9dd4ca88d41ad"
origin = '''
1、如图红圈所示，将风机线插入对应接口。
'''
translate = '''
1、如图红圈所示，将风机线插入对应接口。
'''

[[block]]
key = "678e823b5105de8a"
origin = '''
<ImageView src={require('./img/panda_breeze_installation6.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation6.webp').default} width="80%"/>
'''

[[block]]
key = "9d71362e55001a01"
origin = '''
2、将电源线插入机器后方的MX3.0 插口，见图中红圈位置。
'''
translate = '''
2、将电源线插入机器后方的MX3.0 插口，见图中红圈位置。
'''

[[block]]
key = "8bf23bbb8045b698"
origin = '''
<ImageView src={require('./img/panda_breeze_installation7.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation7.webp').default} width="80%"/>
'''

[[block]]
key = "29772198dbe77e1e"
origin = '''
3、按图示插入电源线。
'''
translate = '''
3、按图示插入电源线。
'''

[[block]]
key = "2dd7bb52fbac6e4f"
origin = '''
<ImageView src={require('./img/panda_breeze_installation8.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation8.webp').default} width="80%"/>
'''

[[block]]
key = "58d9da06e8bfcdd1"
origin = '''
4、通过工具头下方的缺口，将工具头后盖揭开。
'''
translate = '''
4、通过工具头下方的缺口，将工具头后盖揭开。
'''

[[block]]
key = "0aef8a64fea134e9"
origin = '''
<ImageView src={require('./img/panda_breeze_installation9.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation9.webp').default} width="80%"/>
'''

[[block]]
key = "1c373c486114e697"
origin = '''
5、断开部件冷却风扇连接，如图红圈所示。
'''
translate = '''
5、断开部件冷却风扇连接，如图红圈所示。
'''

[[block]]
key = "9473e47933ef5bce"
origin = '''
<ImageView src={require('./img/panda_breeze_installation10.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation10.webp').default} width="80%"/>
'''

[[block]]
key = "0718a47a4382d3b6"
origin = '''
6、插入风扇信号转接线到原部件冷却风扇接口。
'''
translate = '''
6、插入风扇信号转接线到原部件冷却风扇接口。
'''

[[block]]
key = "da531d3f9a4d3cb5"
origin = '''
<ImageView src={require('./img/panda_breeze_installation11.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation11.webp').default} width="80%"/>
'''

[[block]]
key = "f9c032c37f9e09fb"
origin = '''
7、将之前断开的部件冷却风扇接线口与风扇信号转接线对接。
'''
translate = '''
7、将之前断开的部件冷却风扇接线口与风扇信号转接线对接。
'''

[[block]]
key = "aa031b4cb4dcfd61"
origin = '''
<ImageView src={require('./img/panda_breeze_installation12.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation12.webp').default} width="80%"/>
'''

[[block]]
key = "988ca5e4c0c335eb"
origin = '''
8、如图所示，将所有线缆固定在工具头内，撬开打印头右侧的盖板，根据箭头指示，将风扇信号转接线沿着箭头所示的出口方向布线。
'''
translate = '''
8、如图所示，将所有线缆固定在工具头内，撬开打印头右侧的盖板，根据箭头指示，将风扇信号转接线沿着箭头所示的出口方向布线。
'''

[[block]]
key = "440ae8939fcdcc2f"
origin = '''
<ImageView src={require('./img/panda_breeze_installation13.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation13.webp').default} width="80%"/>
'''

[[block]]
key = "fe26f30cb7fd9229"
origin = '''
9、将后盖按压安装回位，确保固定牢靠。
'''
translate = '''
9、将后盖按压安装回位，确保固定牢靠。
'''

[[block]]
key = "c6670336bfc691b9"
origin = '''
<ImageView src={require('./img/panda_breeze_installation14.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation14.webp').default} width="80%"/>
'''

[[block]]
key = "af74c5b14ced4b05"
origin = '''
10、打印 [makerworld](https://makerworld.com/en/models/1698174-panda-breeze-printed-parts#profileId-1800624) 上提供的侧盖，安装回走线槽，固定线材
'''
translate = '''
10、打印 [makerworld](https://makerworld.com/en/models/1698174-panda-breeze-printed-parts#profileId-1800624) 上提供的侧盖，安装回走线槽，固定线材
'''

[[block]]
key = "f1f7ba9887b5346e"
origin = '''
<ImageView src={require('./img/panda_breeze_installation16.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation16.webp').default} width="80%"/>
'''

[[block]]
key = "8df99d77f60ed9c5"
origin = '''
**步骤4：灯条安装**
'''
translate = '''
**步骤4：灯条安装**
'''

[[block]]
key = "ca9f1d30539f8c42"
origin = '''
1. 使用酒精棉片清洁X轴下方，确保表面无尘且无油渍。
2. 撕开灯条背胶的保护膜。
3. 对齐灯条与X轴下方，从左侧开始，缓慢向右侧按压，确保灯条固定。
'''
translate = '''
1. 使用酒精棉片清洁X轴下方，确保表面无尘且无油渍。
2. 撕开灯条背胶的保护膜。
3. 对齐灯条与X轴下方，从左侧开始，缓慢向右侧按压，确保灯条固定。
'''

[[block]]
key = "e94cd6e4408d4159"
origin = '''
<ImageView src={require('./img/panda_breeze_installation15.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation15.webp').default} width="80%"/>
'''

[[block]]
key = "e15b82101ea2ec2b"
origin = '''
4、来回按压灯条，确保其牢固安装完毕。
'''
translate = '''
4、来回按压灯条，确保其牢固安装完毕。
'''

[[block]]
key = "32df2dbbff3196d0"
origin = '''
<ImageView src={require('./img/panda_breeze_installation17.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-breeze/img/panda_breeze_installation17.webp').default} width="80%"/>
'''
