[metadata]

[[block]]
key = "f033356e330d50b8"
origin = '''
---
sidebar_position: 2
---
'''
translate = '''
---
sidebar_position: 2
---
'''

[[block]]
key = "3d887ccdd890cdc9"
origin = '''
# H2 V2X 硬件
'''
translate = '''
# H2 V2X 硬件
'''

[[block]]
key = "5e9b2ccaa93f719a"
origin = '''
H2 V2X 硬件文档
'''
translate = '''
H2 V2X 硬件文档
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "d246b00b41b81b5c"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import ThemedImage from '@theme/ThemedImage';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import ThemedImage from '@theme/ThemedImage';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e106c153eb196b41"
origin = '''
## 模型下载
'''
translate = '''
## 模型下载
'''

[[block]]
key = "f78a4fa5349a29dc"
origin = '''
:::info[3D 参考文件]

H2 V2X 3D 建模参考文件 [bigtreetech/H2-V2X/3D Model/Reference Cad Model](https://github.com/bigtreetech/H2-V2X/tree/master/3D%20Model/Reference%20Cad%20Model)

:::
'''
translate = '''
:::info[3D 参考文件]

H2 V2X 3D 建模参考文件 [bigtreetech/H2-V2X/3D Model/Reference Cad Model](https://github.com/bigtreetech/H2-V2X/tree/master/3D%20Model/Reference%20Cad%20Model)

:::
'''

[[block]]
key = "61f720174bcb9c8f"
origin = '''
:::info[挤出机适配件下载]

Stealthburner 适配件 [bigtreetech/H2-V2X/3D Model/Stealthburner](https://github.com/bigtreetech/H2-V2X/tree/master/3D%20Model/Stealthburner)

EVA3 适配件 [bigtreetech/H2-V2X/3D Model/EVA3](https://github.com/bigtreetech/H2-V2X/tree/master/3D%20Model/EVA3)

:::
'''
translate = '''
:::info[挤出机适配件下载]

Stealthburner 适配件 [bigtreetech/H2-V2X/3D Model/Stealthburner](https://github.com/bigtreetech/H2-V2X/tree/master/3D%20Model/Stealthburner)

EVA3 适配件 [bigtreetech/H2-V2X/3D Model/EVA3](https://github.com/bigtreetech/H2-V2X/tree/master/3D%20Model/EVA3)

:::
'''

[[block]]
key = "e4e43b6d7201907d"
origin = '''
## 外观尺寸
'''
translate = '''
## 外观尺寸
'''

[[block]]
key = "6446646821c092a4"
origin = '''
XYZ尺寸: $53.9 mm * 37.88 mm * 51.52 mm$
'''
translate = '''
XYZ尺寸: $53.9 mm * 37.88 mm * 51.52 mm$
'''

[[block]]
key = "5563ae5ae05197f5"
origin = '''
<ImageView
    src={require('./img/H2V2X_Dimension1.png').default}
    alt="h2 v2x" width="60%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/extruder/h2-v2x/img/H2V2X_Dimension1.png').default}
    alt="h2 v2x" width="60%"
/>
'''

[[block]]
key = "dbea909394e3e542"
origin = '''
<ImageView
    src={require('./img/H2V2X_Dimension2.png').default}
    alt="h2 v2x" width="60%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/extruder/h2-v2x/img/H2V2X_Dimension2.png').default}
    alt="h2 v2x" width="60%"
/>
'''

[[block]]
key = "5ab46058afdc5861"
origin = '''
## 挤出机调节
'''
translate = '''
## 挤出机调节
'''

[[block]]
key = "351202443082cf1e"
origin = '''
:::warning
当调节螺钉停止转动时，请勿用力，以免损坏挤出机结构
:::
'''
translate = '''
:::warning
当调节螺钉停止转动时，请勿用力，以免损坏挤出机结构
:::
'''

[[block]]
key = "818d5528aa0762ed"
origin = '''
<div class="div-table">
    <ImageView
    src={require('./img/H2V2X_Filament1.png').default}
    alt="h2 v2x" width="35%" class="right-image"
    />
'''
translate = '''
<div class="div-table">
    <ImageView
    src={require('@site/docs/accessories-docs/extruder/h2-v2x/img/H2V2X_Filament1.png').default}
    alt="h2 v2x" width="35%" class="right-image"
    />
'''

[[block]]
key = "9be9d0b94c9024de"
origin = '''
    挤出齿轮的松紧可调节，以适应不同的耗材，逆时针方向转动螺杆为夹紧，顺时针方向转动螺杆为松弛(当螺杆停止转动时，请勿用力，以免造成挤出机损坏）
</div>
'''
translate = '''
    挤出齿轮的松紧可调节，以适应不同的耗材，逆时针方向转动螺杆为夹紧，顺时针方向转动螺杆为松弛(当螺杆停止转动时，请勿用力，以免造成挤出机损坏）
</div>
'''

[[block]]
key = "5ccce8756b4eb0f1"
origin = '''
## 挤出机元件耐温
'''
translate = '''
## 挤出机元件耐温
'''

[[block]]
key = "f12d8a58404bf002"
origin = '''
| H2 V2X | 元件最高温度  |
| ------ | ------------- |
| 电机   | $130^\circ C$ |
| 轴承   | $100^\circ C$ |
'''
translate = '''
| H2 V2X | 元件最高温度  |
| ------ | ------------- |
| 电机   | $130^\circ C$ |
| 轴承   | $100^\circ C$ |
'''

[[block]]
key = "c1754e6fd3cad4ff"
origin = '''
## 电机规格
'''
translate = '''
## 电机规格
'''

[[block]]
key = "2bad46144e3b60e2"
origin = '''
<div class="div-table">

<ImageView
    src={require('./img/H2V2X_motor1.png').default}
    alt="h2 v2x" width="60%" class="right-image"
/>
'''
translate = '''
<div class="div-table">

<ImageView
    src={require('@site/docs/accessories-docs/extruder/h2-v2x/img/H2V2X_motor1.png').default}
    alt="h2 v2x" width="60%" class="right-image"
/>
'''

[[block]]
key = "11ea6524e3f2170c"
origin = '''
| H2 V2X       | 电机规格                              |
| ------------ | ------------------------------------- |
| 额定电压     | DC 3.45V                              |
| 额定电流     | DC 1.5A per phase                     |
| 相数         | 2                                     |
| 绕组直流电阻 | $2.3 \Omega \pm 10 \%$ ($25^\circ C$) |
| 绕组电感     | $2.0 mH \pm 20 \%$                    |
| 保持扭矩     | $\ge 110mN*m$                         |
| 定位扭矩     | $7mN*mREF$                            |
| 绝缘电阻     | $\ge 100 M \Omega$ (DC 500V)          |
| 绝缘级别     | Class B                               |
| 转动惯量     | $8g*cm^3$                             |
'''
translate = '''
| H2 V2X       | 电机规格                              |
| ------------ | ------------------------------------- |
| 额定电压     | DC 3.45V                              |
| 额定电流     | DC 1.5A per phase                     |
| 相数         | 2                                     |
| 绕组直流电阻 | $2.3 \Omega \pm 10 \%$ ($25^\circ C$) |
| 绕组电感     | $2.0 mH \pm 20 \%$                    |
| 保持扭矩     | $\ge 110mN*m$                         |
| 定位扭矩     | $7mN*mREF$                            |
| 绝缘电阻     | $\ge 100 M \Omega$ (DC 500V)          |
| 绝缘级别     | Class B                               |
| 转动惯量     | $8g*cm^3$                             |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "b161ae0fe939d659"
origin = '''
## H2 V2X 结构图
'''
translate = '''
## H2 V2X 结构图
'''

[[block]]
key = "a51ac40301dc3d23"
origin = '''
<ThemedImage
    alt="Docusaurus themed image"
    sources={{
        light: require('./img/h2-v2x-component-light.png').default,
        dark: require('./img/h2-v2x-component-dark.png').default,
    }}
/>
'''
translate = '''
<ThemedImage
    alt="Docusaurus themed image"
    sources={{
        light: require('@site/docs/accessories-docs/extruder/h2-v2x/img/h2-v2x-component-light.png').default,
        dark: require('@site/docs/accessories-docs/extruder/h2-v2x/img/h2-v2x-component-dark.png').default,
    }}
/>
'''

[[block]]
key = "d11ebd658be76786"
origin = '''
| H2 V2X        | 结构图                 |             |                          |
| ------------- | ---------------------- | ----------- | ------------------------ |
| 1. 挤出机电机 | 2. 主齿轮              | 3. 齿轮箱   | 4. 682XZZ 轴承           |
| 5. 673ZZ 轴承 | 6. M3X4 杯头内六角螺丝 | 7. 从动齿轮 | 8. 输出齿轮              |
| 9. 挤出齿轮   | 10. 拨杆               | 18. 前盖    | 19. M3x35 平头内六角螺丝 |
'''
translate = '''
| H2 V2X        | 结构图                 |             |                          |
| ------------- | ---------------------- | ----------- | ------------------------ |
| 1. 挤出机电机 | 2. 主齿轮              | 3. 齿轮箱   | 4. 682XZZ 轴承           |
| 5. 673ZZ 轴承 | 6. M3X4 杯头内六角螺丝 | 7. 从动齿轮 | 8. 输出齿轮              |
| 9. 挤出齿轮   | 10. 拨杆               | 18. 前盖    | 19. M3x35 平头内六角螺丝 |
'''
