[metadata]

[[block]]
key = "934594cb16a73f08"
origin = '''
---
sidebar_position: 2
description: Microprobe 硬件
---
'''
translate = '''
---
sidebar_position: 2
description: Microprobe 硬件
---
'''

[[block]]
key = "4fc5f11d4c972a0d"
origin = '''
# Microprobe 硬件
'''
translate = '''
# Microprobe 硬件
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "4cca02bdfa4c2a11"
origin = '''
## 3D 模型
'''
translate = '''
## 3D 模型
'''

[[block]]
key = "e85ba2d35449d87a"
origin = '''
:::info[STEP 模型]

Microprobe STEP 模型 [BIQU microprobe mockup.STEP](https://github.com/bigtreetech/MicroProbe/blob/master/BIQU%20microprobe%20mockup.STEP)

:::
'''
translate = '''
:::info[STEP 模型]

Microprobe STEP 模型 [BIQU microprobe mockup.STEP](https://github.com/bigtreetech/MicroProbe/blob/master/BIQU%20microprobe%20mockup.STEP)

:::
'''

[[block]]
key = "849f2aab069e2dcb"
origin = '''
:::info[打印机适配件]

EVA 工具头 [MicroProbe Bracket for EVA](https://github.com/bigtreetech/MicroProbe/tree/master/MicroProbe%20Bracket%20for%20EVA)

EVA 3 工具头 [MicroProbe V2 Bracket for EVA 3](https://github.com/bigtreetech/MicroProbe/tree/master/MicroProbe%20V2%20Bracket%20for%20EVA%203)

Voron Stealthburner 工具头 [MicroProbe V2 Bracket for Stealthburner](https://github.com/bigtreetech/MicroProbe/tree/master/MicroProbe%20V2%20Bracket%20for%20Stealthburner)

Terminator 工具头 [Microprobe Bracket for Terminator](https://github.com/bigtreetech/MicroProbe/tree/master/Microprobe%20Bracket%20for%20Terminator)

:::
'''
translate = '''
:::info[打印机适配件]

EVA 工具头 [MicroProbe Bracket for EVA](https://github.com/bigtreetech/MicroProbe/tree/master/MicroProbe%20Bracket%20for%20EVA)

EVA 3 工具头 [MicroProbe V2 Bracket for EVA 3](https://github.com/bigtreetech/MicroProbe/tree/master/MicroProbe%20V2%20Bracket%20for%20EVA%203)

Voron Stealthburner 工具头 [MicroProbe V2 Bracket for Stealthburner](https://github.com/bigtreetech/MicroProbe/tree/master/MicroProbe%20V2%20Bracket%20for%20Stealthburner)

Terminator 工具头 [Microprobe Bracket for Terminator](https://github.com/bigtreetech/MicroProbe/tree/master/Microprobe%20Bracket%20for%20Terminator)

:::
'''

[[block]]
key = "935d41d38ee084c8"
origin = '''
## 硬件连接
'''
translate = '''
## 硬件连接
'''

[[block]]
key = "daa6e684c3ffe403"
origin = '''
<ImageView src={require('./img/microprobe-connect.png').default} width="50%"/>
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/microprobe/img/microprobe-connect.png').default} width="50%"/>
'''
