[metadata]

[[block]]
key = "2bcd097dd3f18e81"
origin = '''
---
sidebar_position: 1
description: TMC 5160 T Pro
---
'''
translate = '''
---
sidebar_position: 1
description: TMC 5160 T Pro
---
'''

[[block]]
key = "ddfcd83595942d4d"
origin = '''
# TMC 5160 T Pro
'''
translate = '''
# TMC 5160 T Pro
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "1937108d73c813af"
origin = '''
<div class="div-table">

<ImageView
    src={require('./img/tmc-5160-t-pro-title.png').default}
    alt="" width="35%" class="right-image"
/>
'''
translate = '''
<div class="div-table">

<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160-t-pro/img/tmc-5160-t-pro-title.png').default}
    alt="" width="35%" class="right-image"
/>
'''

[[block]]
key = "58b2c93828f9206e"
origin = '''
## Specifications
'''
translate = '''
## Specifications
'''

[[block]]
key = "476ebc0e3ea2c542"
origin = '''
| Specifications | TMC 5160 T Pro     |
| -------------- | ------------------ |
| 驱动芯片       | TMC 5160           |
| 驱动电压       | 8V - 48V DC        |
| 驱动电流       | 3.1A RMS 4.4A peak |
| 采样电阻       | 0.075 ohms         |
| MOSFET 型号    | JMSL0615AUD        |
'''
translate = '''
| Specifications | TMC 5160 T Pro     |
| -------------- | ------------------ |
| 驱动芯片       | TMC 5160           |
| 驱动电压       | 8V - 48V DC        |
| 驱动电流       | 3.1A RMS 4.4A peak |
| 采样电阻       | 0.075 ohms         |
| MOSFET 型号    | JMSL0615AUD        |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "6a770c30e1108b39"
origin = '''
## 接口示意图
'''
translate = '''
## 接口示意图
'''

[[block]]
key = "ab4eb3745231aef9"
origin = '''
:::info[原理图 / Schematic]

TMC 5160 T Pro 原理图 [BIGTREETECH TMC5160T_Pro-SCH.pdf](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/TMC5160(T)%20Pro%20V1.1/Hardware/BIGTREETECH%20TMC5160T_Pro-SCH.pdf)
:::
'''
translate = '''
:::info[原理图 / Schematic]

TMC 5160 T Pro 原理图 [BIGTREETECH TMC5160T_Pro-SCH.pdf](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/TMC5160(T)%20Pro%20V1.1/Hardware/BIGTREETECH%20TMC5160T_Pro-SCH.pdf)
:::
'''

[[block]]
key = "01c8ba9352b4ea86"
origin = '''
<ImageView
    src={require('./img/tmc-5160-t-pro-pinout.png').default}
    alt="" width="45%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160-t-pro/img/tmc-5160-t-pro-pinout.png').default}
    alt="" width="45%"
/>
'''

[[block]]
key = "a9ae5a7eafeac08f"
origin = '''
## 尺寸
'''
translate = '''
## 尺寸
'''

[[block]]
key = "e388d042fd2f1605"
origin = '''
:::info[STEP 模型]

TMC 5160 T Pro 模型 [TMC5160_Pro V1.1.step](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/TMC5160(T)%20Pro%20V1.1/3D/TMC5160_Pro%20V1.1.step)

:::
'''
translate = '''
:::info[STEP 模型]

TMC 5160 T Pro 模型 [TMC5160_Pro V1.1.step](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/TMC5160(T)%20Pro%20V1.1/3D/TMC5160_Pro%20V1.1.step)

:::
'''

[[block]]
key = "fd34b25ee2cfcfb5"
origin = '''
<ImageView
    src={require('./img/tmc-5160-t-pro-size.png').default}
    alt="" width="45%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160-t-pro/img/tmc-5160-t-pro-size.png').default}
    alt="" width="45%"
/>
'''

[[block]]
key = "59f0c275c335a1f7"
origin = '''
## Klipper SPI 配置
'''
translate = '''
## Klipper SPI 配置
'''

[[block]]
key = "6c87a61b4b69b225"
origin = '''
```klipper_cfg title="printer.cfg"
[tmc5160 stepper_x]
cs_pin: PD2
spi_software_sclk_pin: PC6
spi_software_mosi_pin: PC8
spi_software_miso_pin: PC7
diag1_pin: PF3
run_current: 0.80
sense_resistor: 0.075
interpolate: False
stealthchop_threshold: 0
driver_SGT: 0
```
'''
translate = '''
```klipper_cfg title="printer.cfg"
[tmc5160 stepper_x]
cs_pin: PD2
spi_software_sclk_pin: PC6
spi_software_mosi_pin: PC8
spi_software_miso_pin: PC7
diag1_pin: PF3
run_current: 0.80
sense_resistor: 0.075
interpolate: False
stealthchop_threshold: 0
driver_SGT: 0
```
'''
