[metadata]

[[block]]
key = "f033356e330d50b8"
origin = '''
---
sidebar_position: 2
---
'''
translate = '''
---
sidebar_position: 2
---
'''

[[block]]
key = "9b79b600fb78cf57"
origin = '''
# Eddy Duo Hardware
'''
translate = '''
# Eddy Duo Hardware
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "1d7c6aceba7becf8"
origin = '''
## **产品尺寸及接口**
'''
translate = '''
## **产品尺寸及接口**
'''

[[block]]
key = "3e2f539877e77779"
origin = '''
<ImageView src={require('./img/Eddy_Dimensions.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Dimensions.png').default} alt="" width="600" />
'''

[[block]]
key = "6468ae3c914b2693"
origin = '''
用于计算 XY 偏移的线圈中心点如下：
'''
translate = '''
用于计算 XY 偏移的线圈中心点如下：
'''

[[block]]
key = "dbcd6051134062fd"
origin = '''
<ImageView src={require('./img/Eddy_Dimensions1.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Dimensions1.png').default} alt="" width="600" />
'''

[[block]]
key = "33822e905edd61b5"
origin = '''
## **BOOT 按键位置**
'''
translate = '''
## **BOOT 按键位置**
'''

[[block]]
key = "8414cb209d5a5917"
origin = '''
<ImageView src={require('./img/eddy_boot_1.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_boot_1.png').default} alt="" width="600" />
'''

[[block]]
key = "bf849e9a5938b281"
origin = '''
BOOT 按钮在首次对 Eddy 烧录 Klipper 固件时使用；之后 Klipper 可以自动进入BOOT 模式并重新烧录固件。
'''
translate = '''
BOOT 按钮在首次对 Eddy 烧录 Klipper 固件时使用；之后 Klipper 可以自动进入BOOT 模式并重新烧录固件。
'''

[[block]]
key = "da64ad50088f1334"
origin = '''
**注意：**仅仅 Eddy V1.0 拥有 BOOT 功能，Eddy Coil V1.0 上的按键无功能。
'''
translate = '''
**注意：**仅仅 Eddy V1.0 拥有 BOOT 功能，Eddy Coil V1.0 上的按键无功能。
'''

[[block]]
key = "a8129b1df9326a63"
origin = '''
## **安装指南** 
'''
translate = '''
## **安装指南** 
'''

[[block]]
key = "3c34cb64e8a0868e"
origin = '''
### 安装高度
'''
translate = '''
### 安装高度
'''

[[block]]
key = "ebfced8380e4117c"
origin = '''
确保 Eddy 的安装位置高于喷嘴 2 至 3 毫米，以确保最佳性能。如果在校准过程中遇到错误，这些可能与 Eddy 的安装高度有关。有关解决方案，请参阅本手册
的故障排除部分。
'''
translate = '''
确保 Eddy 的安装位置高于喷嘴 2 至 3 毫米，以确保最佳性能。如果在校准过程中遇到错误，这些可能与 Eddy 的安装高度有关。有关解决方案，请参阅本手册
的故障排除部分。
'''

[[block]]
key = "873a32bc9e02eefb"
origin = '''
重要提示：需要注意的是，用户可能会将电流校准高度 20 毫米与 Eddy 的安装高度 2 至 3 毫米混淆。20 毫米的高度仅在本手册后续部分进行线圈电流校准时使用。
'''
translate = '''
重要提示：需要注意的是，用户可能会将电流校准高度 20 毫米与 Eddy 的安装高度 2 至 3 毫米混淆。20 毫米的高度仅在本手册后续部分进行线圈电流校准时使用。
'''

[[block]]
key = "b7d50792af245e55"
origin = '''
### 以 Voron2.4 为例
'''
translate = '''
### 以 Voron2.4 为例
'''

[[block]]
key = "5cb62e6aff20a2f6"
origin = '''
安装位置，完全替代原有 PL-08N 安装位
使用两颗 M3*25 螺丝（包装内附）将模块固定再 X Carriage 打印件上，如视图
'''
translate = '''
安装位置，完全替代原有 PL-08N 安装位
使用两颗 M3*25 螺丝（包装内附）将模块固定再 X Carriage 打印件上，如视图
'''

[[block]]
key = "7c7897b46d3e2702"
origin = '''
<ImageView src={require('./img/Eddy_Installation1.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Installation1.png').default} alt="" width="600" />
'''

[[block]]
key = "2008e04a2a0ed4c0"
origin = '''
<ImageView src={require('./img/Eddy_Installation2.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Installation2.png').default} alt="" width="600" />
'''

[[block]]
key = "19f7ff9341858059"
origin = '''
### 在其他机器上的安装
'''
translate = '''
### 在其他机器上的安装
'''

[[block]]
key = "621bcc6dcf87601b"
origin = '''
用户可在我们的 GitHub 仓库以及其他常见模型分享平台中找到适用于多种常见机型的支架。在安装 Eddy 的过程中，请确保 PCB 侧（背面）与热端保持尽可能大的距离。此类布局有助于最小化从热端到 Eddy 的热传导。
'''
translate = '''
用户可在我们的 GitHub 仓库以及其他常见模型分享平台中找到适用于多种常见机型的支架。在安装 Eddy 的过程中，请确保 PCB 侧（背面）与热端保持尽可能大的距离。此类布局有助于最小化从热端到 Eddy 的热传导。
'''

[[block]]
key = "fdabeb9f35c499be"
origin = '''
### Eddy + Manta M5P
'''
translate = '''
### Eddy + Manta M5P
'''

[[block]]
key = "867e3e836587c284"
origin = '''
<ImageView src={require('./img/Eddy_Connection.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Connection.png').default} alt="" width="600" />
'''

[[block]]
key = "3d1998d150e5ad60"
origin = '''
### Eddy + Manta M8P V2.0
'''
translate = '''
### Eddy + Manta M8P V2.0
'''

[[block]]
key = "bc5948326864e5d5"
origin = '''
<ImageView src={require('./img/Eddy_Connection1.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Connection1.png').default} alt="" width="600" />
'''

[[block]]
key = "1a9a532c7b42eaf6"
origin = '''
### Eddy Coil + EBB36 V1.2
'''
translate = '''
### Eddy Coil + EBB36 V1.2
'''

[[block]]
key = "64b236ae4654d3c9"
origin = '''
<ImageView src={require('./img/Eddy_Connection2.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Connection2.png').default} alt="" width="600" />
'''

[[block]]
key = "60e6e1f2286d380a"
origin = '''
### Eddy Coil + EBB42 V1.2
'''
translate = '''
### Eddy Coil + EBB42 V1.2
'''

[[block]]
key = "2288b9f2828d6e1a"
origin = '''
<ImageView src={require('./img/Eddy_Connection3.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/Eddy_Connection3.png').default} alt="" width="600" />
'''

[[block]]
key = "60ead07aeaedeedd"
origin = '''
### Eddy Duo + MANTA M5P（USB）
'''
translate = '''
### Eddy Duo + MANTA M5P（USB）
'''

[[block]]
key = "e27538486e9b0f2f"
origin = '''
<ImageView src={require('./img/eddy_connection4.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection4.png').default} alt="" width="600" />
'''

[[block]]
key = "a2d4d8f210264263"
origin = '''
### Eddy Duo + MANTA M8P V2.0（USB）
'''
translate = '''
### Eddy Duo + MANTA M8P V2.0（USB）
'''

[[block]]
key = "c898c8315a72386b"
origin = '''
<ImageView src={require('./img/eddy_connection6.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection6.png').default} alt="" width="600" />
'''

[[block]]
key = "c43d5dd6ba7c2ffe"
origin = '''
### Eddy Duo + MANTA M8P V2.0（CAN）
'''
translate = '''
### Eddy Duo + MANTA M8P V2.0（CAN）
'''

[[block]]
key = "3cd18bb89dccbdae"
origin = '''
<ImageView src={require('./img/eddy_connection7.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection7.png').default} alt="" width="600" />
'''

[[block]]
key = "6706ac33cc0cca23"
origin = '''
### Eddy Duo + EBB36
'''
translate = '''
### Eddy Duo + EBB36
'''

[[block]]
key = "69d6acbb9084b18d"
origin = '''
<ImageView src={require('./img/eddy_connection8.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection8.png').default} alt="" width="600" />
'''

[[block]]
key = "18fee9c6290453d4"
origin = '''
### Eddy Duo + EBB42
'''
translate = '''
### Eddy Duo + EBB42
'''

[[block]]
key = "4cc1601035a77b0b"
origin = '''
<ImageView src={require('./img/eddy_connection9.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection9.png').default} alt="" width="600" />
'''

[[block]]
key = "9f2c313c90cac700"
origin = '''
### Eddy Duo + EBB SB
'''
translate = '''
### Eddy Duo + EBB SB
'''

[[block]]
key = "f8a6ae74dc88682f"
origin = '''
<ImageView src={require('./img/eddy_connection10.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection10.png').default} alt="" width="600" />
'''

[[block]]
key = "390ba91ae713335e"
origin = '''
### Octopus V1.1/Pro V1.0/Pro V1.0.1 + Eddy Duo（USB）
'''
translate = '''
### Octopus V1.1/Pro V1.0/Pro V1.0.1 + Eddy Duo（USB）
'''

[[block]]
key = "8894f255f6d0cf7e"
origin = '''
<ImageView src={require('./img/eddy_connection11.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection11.png').default} alt="" width="600" />
'''

[[block]]
key = "8cfdd095e1f33ad4"
origin = '''
### Octopus V1.1/Pro V1.0/Pro V1.0.1 + Eddy Duo（CAN）
'''
translate = '''
### Octopus V1.1/Pro V1.0/Pro V1.0.1 + Eddy Duo（CAN）
'''

[[block]]
key = "3c228f93607e07de"
origin = '''
<ImageView src={require('./img/eddy_connection12.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection12.png').default} alt="" width="600" />
'''

[[block]]
key = "ee4af048fb2aefa6"
origin = '''
### Octopus Pro V1.1 + Eddy Duo（USB）
'''
translate = '''
### Octopus Pro V1.1 + Eddy Duo（USB）
'''

[[block]]
key = "fad6804a7beda78e"
origin = '''
<ImageView src={require('./img/eddy_connection13.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection13.png').default} alt="" width="600" />
'''

[[block]]
key = "945be403d521d35f"
origin = '''
### Octopus Pro V1.1 + Eddy Duo（CAN）
'''
translate = '''
### Octopus Pro V1.1 + Eddy Duo（CAN）
'''

[[block]]
key = "39811f9815bf142c"
origin = '''
<ImageView src={require('./img/eddy_connection14.png').default} alt="" width="600" />
'''
translate = '''
<ImageView src={require('@site/docs/accessories-docs/sensor/eddy/img/eddy_connection14.png').default} alt="" width="600" />
'''
