[metadata]

[[block]]
key = "a86742522b9afcd2"
origin = '''
---
sidebar_position: 2
description: Manta M5P 硬件功能配置
---
'''
translate = '''
---
sidebar_position: 2
description: Manta M5P 硬件功能配置
---
'''

[[block]]
key = "baebab4347e11b45"
origin = '''
# Manta M5P 硬件功能
'''
translate = '''
# Manta M5P 硬件功能
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e4e43b6d7201907d"
origin = '''
## 外观尺寸
'''
translate = '''
## 外观尺寸
'''

[[block]]
key = "c8105c982eb263cc"
origin = '''
:::info[STEP 模型]

Manta M5P 模型 [BIGTREETECH MANTA M5P-step.rar](https://github.com/bigtreetech/Manta-M5P/blob/master/3D/BIGTREETECH%20MANTA%20M5P-step.rar)

:::
'''
translate = '''
:::info[STEP 模型]

Manta M5P 模型 [BIGTREETECH MANTA M5P-step.rar](https://github.com/bigtreetech/Manta-M5P/blob/master/3D/BIGTREETECH%20MANTA%20M5P-step.rar)

:::
'''

[[block]]
key = "1728010ee308754f"
origin = '''
<Tabs groupId="m5p-dim">
    <TabItem value="m5p-dim-1" label="正面尺寸" default>
'''
translate = '''
<Tabs groupId="m5p-dim">
    <TabItem value="m5p-dim-1" label="正面尺寸" default>
'''

[[block]]
key = "88b02d8f5a8373f2"
origin = '''
        <ImageView src={require('./img/M5P_Dimension1.png').default} width="80%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_Dimension1.png').default} width="80%"/>
'''

[[block]]
key = "8815b566ecc95aa4"
origin = '''
    </TabItem>
    <TabItem value="m5p-dim-2" label="反面尺寸">
        <ImageView src={require('./img/M5P_Dimension2.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m5p-dim-2" label="反面尺寸">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_Dimension2.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "a2df1b4a41a65fdc"
origin = '''
## Pinout
'''
translate = '''
## Pinout
'''

[[block]]
key = "960160c15c2b5e71"
origin = '''
:::info[原理图 / Schematic]

Manta M5P 原理图 [BIGTREETECH MANTA M5P V1.0-SCH.pdf](https://github.com/bigtreetech/Manta-M5P/blob/master/Hardware/BIGTREETECH%20MANTA%20M5P%20V1.0-SCH.pdf)

:::
'''
translate = '''
:::info[原理图 / Schematic]

Manta M5P 原理图 [BIGTREETECH MANTA M5P V1.0-SCH.pdf](https://github.com/bigtreetech/Manta-M5P/blob/master/Hardware/BIGTREETECH%20MANTA%20M5P%20V1.0-SCH.pdf)

:::
'''

[[block]]
key = "29809f60ea86aee2"
origin = '''
<ImageView src={require('./img/manta-m5p-pinout.png').default} width="100%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-pinout.png').default} width="100%"/>
'''

[[block]]
key = "65fe332995c323ad"
origin = '''
## 步进电机驱动
'''
translate = '''
## 步进电机驱动
'''

[[block]]
key = "1a4a3842613a0d20"
origin = '''
### 驱动模式
'''
translate = '''
### 驱动模式
'''

[[block]]
key = "c7fa3648120cae4d"
origin = '''
<Tabs groupId="m5p-stepper-driver">
    <TabItem value="tmc-uart" label="Uart 模式" default>
'''
translate = '''
<Tabs groupId="m5p-stepper-driver">
    <TabItem value="tmc-uart" label="Uart 模式" default>
'''

[[block]]
key = "b3fc14f238b5a24c"
origin = '''
        使用 Uart 模式连接驱动
        <ImageView
            src={require('./img/manta-m5p-driver-uart.png').default}
            alt="" width="80%"
        />
    </TabItem>
    <TabItem value="tmc-spi" label="SPI 模式">
        使用 SPI 模式连接驱动
        <ImageView
            src={require('./img/manta-m5p-driver-spi.png').default}
            alt="" width="80%"
        />
    </TabItem>
    <TabItem value="step-dir" label="Step / DIR 模式">
        A4988 / DRV8825 使用跳线帽短接 MS0-MS2 以调整细分
        <ImageView
            src={require('./img/manta-m5p-driver-step.png').default}
            alt="" width="80%"
        />
    </TabItem>
</Tabs>
'''
translate = '''
        使用 Uart 模式连接驱动
        <ImageView
            src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-driver-uart.png').default}
            alt="" width="80%"
        />
    </TabItem>
    <TabItem value="tmc-spi" label="SPI 模式">
        使用 SPI 模式连接驱动
        <ImageView
            src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-driver-spi.png').default}
            alt="" width="80%"
        />
    </TabItem>
    <TabItem value="step-dir" label="Step / DIR 模式">
        A4988 / DRV8825 使用跳线帽短接 MS0-MS2 以调整细分
        <ImageView
            src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-driver-step.png').default}
            alt="" width="80%"
        />
    </TabItem>
</Tabs>
'''

[[block]]
key = "7597071185858aae"
origin = '''
### TMC Sensorless
'''
translate = '''
### TMC Sensorless
'''

[[block]]
key = "8115b33bf9048ced"
origin = '''
<ImageView src={require('./img/manta-m5p-sensorless.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-sensorless.png').default} width="80%"/>
'''

[[block]]
key = "e399c8f991a5a5a8"
origin = '''
### 驱动电压选择
'''
translate = '''
### 驱动电压选择
'''

[[block]]
key = "e459c43edfbf321c"
origin = '''
<Tabs groupId="m5p-driver-power">
    <TabItem value="m5p-power-24" label="使用 24V 电源" default>
'''
translate = '''
<Tabs groupId="m5p-driver-power">
    <TabItem value="m5p-power-24" label="使用 24V 电源" default>
'''

[[block]]
key = "fd2d1244d5af88f7"
origin = '''
        <ImageView src={require('./img/manta-m5p-driver-24.png').default} width="80%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-driver-24.png').default} width="80%"/>
'''

[[block]]
key = "b1717a175bd92cd2"
origin = '''
    </TabItem>
    <TabItem value="m5p-power-48" label="使用 48V 电源">
        <ImageView src={require('./img/manta-m5p-driver-48.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m5p-power-48" label="使用 48V 电源">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-driver-48.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "2e57f54e9eed83b0"
origin = '''
## 核心板
'''
translate = '''
## 核心板
'''

[[block]]
key = "74aa951c0c99de92"
origin = '''
### 核心板安装
'''
translate = '''
### 核心板安装
'''

[[block]]
key = "7731c1291c5ec784"
origin = '''
<Tabs groupId="m5p-cm">
    <TabItem value="m5p-cm-rpi" label="使用树莓派 CM4/CM5" default>
'''
translate = '''
<Tabs groupId="m5p-cm">
    <TabItem value="m5p-cm-rpi" label="使用树莓派 CM4/CM5" default>
'''

[[block]]
key = "85d2180e0c9cb91d"
origin = '''
        <ImageView src={require('./img/m5p_cm_rpi.png').default} width="80%"/>
'''
translate = '''
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/m5p_cm_rpi.png').default} width="80%"/>
'''

[[block]]
key = "9231f444f5e4a30f"
origin = '''
    </TabItem>
    <TabItem value="m5p-cm-cb" label="使用 CB1/CB2">
        <ImageView src={require('./img/m5p_cm_cb.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''
translate = '''
    </TabItem>
    <TabItem value="m5p-cm-cb" label="使用 CB1/CB2">
        <ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/m5p_cm_cb.png').default} width="80%"/>
    </TabItem>
</Tabs>
'''

[[block]]
key = "83e4703555823190"
origin = '''
### USB 供电
'''
translate = '''
### USB 供电
'''

[[block]]
key = "340b5cd38d34a846"
origin = '''
MANTA M5P通电后，MCU左侧的红灯D22将亮起，表示已通电。当仅使用USB为板供电或通过USB供电时，请将跳线帽插入VUSB。
'''
translate = '''
MANTA M5P通电后，MCU左侧的红灯D22将亮起，表示已通电。当仅使用USB为板供电或通过USB供电时，请将跳线帽插入VUSB。
'''

[[block]]
key = "f3cbf743a1a3b50f"
origin = '''
<ImageView src={require('./img/M5P_USB_PS.png').default} width="45%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_USB_PS.png').default} width="45%"/>
'''

[[block]]
key = "66e7f403422dd275"
origin = '''
### DSI / CSI连接
'''
translate = '''
### DSI / CSI连接
'''

[[block]]
key = "13380f4537b6b7c6"
origin = '''
:::info[需要硬件支持]

DSI / CSI 需要核心板硬件支持

:::
'''
translate = '''
:::info[需要硬件支持]

DSI / CSI 需要核心板硬件支持

:::
'''

[[block]]
key = "6d718901f7ae7dbe"
origin = '''
<ImageView src={require('./img/M5P_DSI.png').default} width="100%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_DSI.png').default} width="100%"/>
'''

[[block]]
key = "d3d60d033160c6bb"
origin = '''
## 风扇
'''
translate = '''
## 风扇
'''

[[block]]
key = "42a1c5868cbd4eef"
origin = '''
### 风扇电压选择
'''
translate = '''
### 风扇电压选择
'''

[[block]]
key = "6349d2e529592521"
origin = '''
使用跳线帽配置输出电压
'''
translate = '''
使用跳线帽配置输出电压
'''

[[block]]
key = "0295af4d22b63c7b"
origin = '''
:::warning

在选择电压之前，请确认风扇的工作电压

:::
'''
translate = '''
:::warning

在选择电压之前，请确认风扇的工作电压

:::
'''

[[block]]
key = "16c292e612c98b63"
origin = '''
<ImageView src={require('./img/manta-m5p-fan-voltage.png').default} width="40%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/manta-m5p-fan-voltage.png').default} width="40%"/>
'''

[[block]]
key = "33f14c7d5c17fff4"
origin = '''
## 传感器
'''
translate = '''
## 传感器
'''

[[block]]
key = "055af79b3798a6be"
origin = '''
### BLTouch
'''
translate = '''
### BLTouch
'''

[[block]]
key = "b098289f84358488"
origin = '''
<ImageView src={require('./img/M5P_BLTouch_Wiring.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_BLTouch_Wiring.png').default} width="80%"/>
'''

[[block]]
key = "4fbb9a4c823aff32"
origin = '''
### 100K NTC 或 PT1000 设置
'''
translate = '''
### 100K NTC 或 PT1000 设置
'''

[[block]]
key = "5c954ce7088e30f6"
origin = '''
当使用100K NTC热敏电阻时，无需插入跳线帽 `TH0` `TH1` 的上拉电阻为 4.7K 0.1%。
'''
translate = '''
当使用100K NTC热敏电阻时，无需插入跳线帽 `TH0` `TH1` 的上拉电阻为 4.7K 0.1%。
'''

[[block]]
key = "f049c1a8e6c858f5"
origin = '''
:::info[使用 PT1000]

使用PT1000时，需要插入 PT 的跳线帽。此时 `TH0` `TH1` 的上拉电阻为2.2K。

这样读取的温度精度将远不如MAX31865读取的精度

<ImageView src={require('./img/M5P_100K.png').default} width="20%"/>

:::
'''
translate = '''
:::info[使用 PT1000]

使用PT1000时，需要插入 PT 的跳线帽。此时 `TH0` `TH1` 的上拉电阻为2.2K。

这样读取的温度精度将远不如MAX31865读取的精度

<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_100K.png').default} width="20%"/>

:::
'''

[[block]]
key = "b0593a3f25c4d84e"
origin = '''
### 耗材传感器
'''
translate = '''
### 耗材传感器
'''

[[block]]
key = "47283dad62cdb5ab"
origin = '''
<ImageView src={require('./img/M5P_Filament.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_Filament.png').default} width="80%"/>
'''

[[block]]
key = "1edc2ff103b2910c"
origin = '''
### 接近开关接线
'''
translate = '''
### 接近开关接线
'''

[[block]]
key = "3e57b668342dbf1e"
origin = '''
使用 PNP 接近开关
'''
translate = '''
使用 PNP 接近开关
'''

[[block]]
key = "75a9d37256d4b093"
origin = '''
<ImageView src={require('./img/M5P_Proximity-PNP.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_Proximity-PNP.png').default} width="80%"/>
'''

[[block]]
key = "7d3ce3e1e66fa0ba"
origin = '''
:::info[NPN 接近开关]

NPN 接近开关不需要接 `Pull UP` 跳线帽

:::
'''
translate = '''
:::info[NPN 接近开关]

NPN 接近开关不需要接 `Pull UP` 跳线帽

:::
'''

[[block]]
key = "1b82752cdbb59462"
origin = '''
## 其他硬件
'''
translate = '''
## 其他硬件
'''

[[block]]
key = "c5ba87e7a93379bf"
origin = '''
### Neopixel 
'''
translate = '''
### Neopixel 
'''

[[block]]
key = "33743405abd0145c"
origin = '''
<ImageView src={require('./img/M5P_RGB_Wiring.png').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/board-docs/manta-series/manta-m5p/img/M5P_RGB_Wiring.png').default} width="80%"/>
'''
