[metadata]

[[block]]
key = "4437cd0edc25491c"
origin = '''
---
sidebar_position: 1
description: TMC 5160
---
'''
translate = '''
---
sidebar_position: 1
description: TMC 5160
---
'''

[[block]]
key = "72cd314e7f700a4e"
origin = '''
# TMC 5160
'''
translate = '''
# TMC 5160
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "9a4d9968e431e52b"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocCardList from '@theme/DocCardList';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
import DocCardList from '@theme/DocCardList';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "cd6a63fd30ce31eb"
origin = '''
<div class="div-table">

<ImageView
    src={require('./img/TMC5160_Title.png').default}
    alt="" width="35%" class="right-image"
/>
'''
translate = '''
<div class="div-table">

<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160/img/TMC5160_Title.png').default}
    alt="" width="35%" class="right-image"
/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## 产品简介
'''

[[block]]
key = "64cbb44b90634b8d"
origin = '''
TMC5160 是一款大功率步进电机驱动控制芯片，使用外置MOSFET，最大电流可达20A，工作时发热小。
'''
translate = '''
TMC5160 是一款大功率步进电机驱动控制芯片，使用外置MOSFET，最大电流可达20A，工作时发热小。
'''

[[block]]
key = "58b2c93828f9206e"
origin = '''
## Specifications
'''
translate = '''
## Specifications
'''

[[block]]
key = "efa16337a4251e0f"
origin = '''
| Specifications | TMC 5160  |
| -------------- | --------- |
| 驱动芯片       | TMC 5160  |
| 输入电压       | 8-40V     |
| 驱动电流       | 4.4A peak |
'''
translate = '''
| Specifications | TMC 5160  |
| -------------- | --------- |
| 驱动芯片       | TMC 5160  |
| 输入电压       | 8-40V     |
| 驱动电流       | 4.4A peak |
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "6a770c30e1108b39"
origin = '''
## 接口示意图
'''
translate = '''
## 接口示意图
'''

[[block]]
key = "d7eaaf886cf73a2e"
origin = '''
:::info[原理图 / Schematic]

TMC 5160 原理图 [TMC5160-Schematic.pdf)](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/TMC5160(T)/hardware/TMC5160-Schematic.pdf)

:::
'''
translate = '''
:::info[原理图 / Schematic]

TMC 5160 原理图 [TMC5160-Schematic.pdf)](https://github.com/bigtreetech/BIGTREETECH-Stepper-Motor-Driver/blob/master/TMC5160(T)/hardware/TMC5160-Schematic.pdf)

:::
'''

[[block]]
key = "3e58c856f2d122c5"
origin = '''
<ImageView
    src={require('./img/TMC5160_Pin.png').default}
    alt="" width="60%"
/>
'''
translate = '''
<ImageView
    src={require('@site/docs/accessories-docs/tmc-driver/tmc-5160/img/TMC5160_Pin.png').default}
    alt="" width="60%"
/>
'''

[[block]]
key = "9f7e406f4964b5b4"
origin = '''
## 硬件配置
'''
translate = '''
## 硬件配置
'''

[[block]]
key = "27c29e272a91d3ae"
origin = '''
### 驱动电流
'''
translate = '''
### 驱动电流
'''

[[block]]
key = "61c480eb999cb042"
origin = '''
TMC 5160 的最大驱动电流取决于使用的采样电阻。默认值为 $0.075 \Omega$
'''
translate = '''
TMC 5160 的最大驱动电流取决于使用的采样电阻。默认值为 $0.075 \Omega$
'''

[[block]]
key = "0df8bdf7d340cc54"
origin = '''
| $R_{sense}$ [$\Omega$] | RMS current [A] | Sine wave peak current [A] |
| ---------------------- | --------------- | -------------------------- |
| 0.22                   | 1.1             | 1.5                        |
| 0.15                   | 1.6             | 2.2                        |
| 0.12                   | 2.0             | 2.8                        |
| 0.10                   | 2.3             | 3.3                        |
| 0.075                  | 3.1             | 4.4                        |
| 0.066                  | 3.5             | 5.0                        |
| 0.050                  | 4.7             | 6.6                        |
| 0.033                  | 7.1             | 10.0                       |
| 0.022                  | 10.6            | 15.0                       |
'''
translate = '''
| $R_{sense}$ [$\Omega$] | RMS current [A] | Sine wave peak current [A] |
| ---------------------- | --------------- | -------------------------- |
| 0.22                   | 1.1             | 1.5                        |
| 0.15                   | 1.6             | 2.2                        |
| 0.12                   | 2.0             | 2.8                        |
| 0.10                   | 2.3             | 3.3                        |
| 0.075                  | 3.1             | 4.4                        |
| 0.066                  | 3.5             | 5.0                        |
| 0.050                  | 4.7             | 6.6                        |
| 0.033                  | 7.1             | 10.0                       |
| 0.022                  | 10.6            | 15.0                       |
'''

[[block]]
key = "89f2a80180cbba78"
origin = '''
:::warning[更换采样电阻]

如果需要更大电流需要更换采样电阻。由于模块体积限制更换低于 $0.05 \Omega$ 的采样电阻可能会导致驱动损坏。

:::
'''
translate = '''
:::warning[更换采样电阻]

如果需要更大电流需要更换采样电阻。由于模块体积限制更换低于 $0.05 \Omega$ 的采样电阻可能会导致驱动损坏。

:::
'''
