[metadata]

[[block]]
key = "dd24dfa5953e1236"
origin = '''
---
sidebar_position: 1
---
'''
translate = '''
---
sidebar_position: 1
---
'''

[[block]]
key = "bdda3df8de7dfc43"
origin = '''
# 更多系列
'''
translate = '''
# More Series
'''

[[block]]
key = "fc911c463a91de11"
origin = '''
## Pop 系列
'''
translate = '''
## Pop Series
'''

[[block]]
key = "f9831f3cb5726e99"
origin = '''
[Pop 系列模块](category/pop-series-module)
'''
translate = '''
[Pop Series Module](category/pop-series-module)
'''
