[metadata]

[[block]]
key = "58eb1ab8e1d7d71a"
origin = '''
# Panda Revo P1 Hotend
'''
translate = '''
# Panda Revo P1 Hotend
'''

[[block]]
key = "11880411c1dae9f6"
origin = '''
<div class="div-table">

<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_Title.webp').default} width="40%" class="right-image"/>
'''
translate = '''
<div class="div-table">

<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_Title.webp').default} width="40%" class="right-image"/>
'''

[[block]]
key = "6e3d031df0b0cf65"
origin = '''
## **产品简介**
'''
translate = '''
## **产品简介**
'''

[[block]]
key = "b792682adce469f5"
origin = '''
与E3D共同开发的Panda Revo具有无需工具、30秒喷嘴更换和Revo™HF喷嘴，可实现高达40mm³/s的燃烧流速，以及强大的60W加热器核心。与Bambu实验室的P1打印机完全兼容。提升您的打印体验！
'''
translate = '''
与E3D共同开发的Panda Revo具有无需工具、30秒喷嘴更换和Revo™HF喷嘴，可实现高达40mm³/s的燃烧流速，以及强大的60W加热器核心。与Bambu实验室的P1打印机完全兼容。提升您的打印体验！
'''

[[block]]
key = "53b10a12d3de6d92"
origin = '''
## **功能亮点**
'''
translate = '''
## **功能亮点**
'''

[[block]]
key = "c895fd7b096ee00c"
origin = '''
- 与E3D共同开发，集成E3D RapidChange Revo™生态系统，与除Revo™皮带喷嘴外的所有Revo™喷嘴兼容。
- 采用E3D定制的NTC100k热敏电阻的60W加热器芯，满足高速高流量打印的功率要求。
- 配有0.4mm Revo™高流量喷嘴，超高流量。
- 徒手快速更换喷嘴30秒。
- 可更换喷嘴，无需更换整个喷嘴。
- 与Bambu实验室的P1系列打印机兼容。
'''
translate = '''
- 与E3D共同开发，集成E3D RapidChange Revo™生态系统，与除Revo™皮带喷嘴外的所有Revo™喷嘴兼容。
- 采用E3D定制的NTC100k热敏电阻的60W加热器芯，满足高速高流量打印的功率要求。
- 配有0.4mm Revo™高流量喷嘴，超高流量。
- 徒手快速更换喷嘴30秒。
- 可更换喷嘴，无需更换整个喷嘴。
- 与Bambu实验室的P1系列打印机兼容。
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "bc575faf3aa7b2df"
origin = '''
:::warning

在使用和冷却过程中，有可能烫伤你的手。

您的HotEnd和打印机由您负责。我们不对因使用、误用或滥用我们的产品而造成的损害负责。

Revo喷嘴应在不使用工具的情况下用手固定，在开始打印之前，确保喷嘴完全拧紧

Revo喷嘴必须在室温下固定，以避免烧伤。

:::
'''
translate = '''
:::warning

在使用和冷却过程中，有可能烫伤你的手。

您的HotEnd和打印机由您负责。我们不对因使用、误用或滥用我们的产品而造成的损害负责。

Revo喷嘴应在不使用工具的情况下用手固定，在开始打印之前，确保喷嘴完全拧紧

Revo喷嘴必须在室温下固定，以避免烧伤。

:::
'''

[[block]]
key = "76c444e71c2b9f6d"
origin = '''
## **规格**
'''
translate = '''
## **规格**
'''

[[block]]
key = "6619deea86b2b16f"
origin = '''
| 长度           | 47.3mm                |
| -------------- | --------------------- |
| **包装尺寸**   | **95x66x28mm**        |
| **最高温度**   | **300℃**              |
| **最大流量**   | **40mm³/s**           |
| **喷嘴材料**   | **黄铜**              |
| **喷嘴直径**   | **0.4mm**             |
| **喷嘴型号**   | **E3D Revo™高流量**   |
| **加热棒电压** | **24V**               |
| **加热棒功率** | **60W**               |
| **热敏电阻**   | **NTC100k**           |
| **兼容性**     | **Bambu Lab P1P/P1S** |
'''
translate = '''
| 长度           | 47.3mm                |
| -------------- | --------------------- |
| **包装尺寸**   | **95x66x28mm**        |
| **最高温度**   | **300℃**              |
| **最大流量**   | **40mm³/s**           |
| **喷嘴材料**   | **黄铜**              |
| **喷嘴直径**   | **0.4mm**             |
| **喷嘴型号**   | **E3D Revo™高流量**   |
| **加热棒电压** | **24V**               |
| **加热棒功率** | **60W**               |
| **热敏电阻**   | **NTC100k**           |
| **兼容性**     | **Bambu Lab P1P/P1S** |
'''

[[block]]
key = "93a73a9bf52b234b"
origin = '''
| 包装清单                             | 数量  |
| ------------------------------------ | ----- |
| **散热器**                           | **1** |
| **P1的加热棒芯组件（带弹簧和套筒）** | **1** |
| **0.4mm Revo™高流量喷嘴**            | **1** |
| **BIQU X E3D贴纸**                   | **1** |
'''
translate = '''
| 包装清单                             | 数量  |
| ------------------------------------ | ----- |
| **散热器**                           | **1** |
| **P1的加热棒芯组件（带弹簧和套筒）** | **1** |
| **0.4mm Revo™高流量喷嘴**            | **1** |
| **BIQU X E3D贴纸**                   | **1** |
'''

[[block]]
key = "8d07a34e73430e77"
origin = '''
:::info[3D 模型]

https://github.com/bigtreetech/Panda_Revo/tree/master/3D

:::
'''
translate = '''
:::info[3D 模型]

https://github.com/bigtreetech/Panda_Revo/tree/master/3D

:::
'''

[[block]]
key = "1d4d588a0053c343"
origin = '''
## 安装指南
'''
translate = '''
## 安装指南
'''

[[block]]
key = "9b7862364caf9a73"
origin = '''
###  P1的安装视频教程
'''
translate = '''
###  P1的安装视频教程
'''

[[block]]
key = "7f92a9884b4f1d6a"
origin = '''
 https://www.youtube.com/watch?v=wyYv6dBOpak
'''
translate = '''
 https://www.youtube.com/watch?v=wyYv6dBOpak
'''

[[block]]
key = "6308bc17c79770af"
origin = '''
### 完整的热端组件
'''
translate = '''
### 完整的热端组件
'''

[[block]]
key = "a17051e15fc18a1d"
origin = '''
（不包括冷却风扇）用于P1系列打印机。
'''
translate = '''
（不包括冷却风扇）用于P1系列打印机。
'''

[[block]]
key = "6738f87aef370a14"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In1.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In1.webp').default} width="80%"/>
'''

[[block]]
key = "57d7dc92048f190c"
origin = '''
该图像显示P1系列打印机的“完整热端部件”，不包括冷却风扇以供后续部件参考。
'''
translate = '''
该图像显示P1系列打印机的“完整热端部件”，不包括冷却风扇以供后续部件参考。
'''

[[block]]
key = "5953bd07f591343f"
origin = '''
:::warning

在对打印机或其电子设备进行任何维护之前，请始终关闭电源并断开打印机的连接，以防止短路和潜在损坏。在拆卸热端等零件时，这一点尤为重要，因为如果打印机打开，裸露的电线和组件可能会造成电气损坏。如有任何问题或疑问，请联系我们的支持团队寻求帮助。

:::
'''
translate = '''
:::warning

在对打印机或其电子设备进行任何维护之前，请始终关闭电源并断开打印机的连接，以防止短路和潜在损坏。在拆卸热端等零件时，这一点尤为重要，因为如果打印机打开，裸露的电线和组件可能会造成电气损坏。如有任何问题或疑问，请联系我们的支持团队寻求帮助。

:::
'''

[[block]]
key = "fc809d7b46ef1c08"
origin = '''
### 所需的工具和零件
'''
translate = '''
### 所需的工具和零件
'''

[[block]]
key = "35cd92d209cb10ba"
origin = '''
- H2.0六角扳手
- 常备的热端冷却风扇
- 常备的安装螺钉（用于散热器和冷却风扇）
'''
translate = '''
- H2.0六角扳手
- 常备的热端冷却风扇
- 常备的安装螺钉（用于散热器和冷却风扇）
'''

[[block]]
key = "66737fc09eb0ab92"
origin = '''
### 准备工作
'''
translate = '''
### 准备工作
'''

[[block]]
key = "6b4dc299c1b5dff1"
origin = '''
用切割杆手动切割灯丝，确保喷嘴温度已冷却至50℃以下，并关闭打印机电源。
'''
translate = '''
用切割杆手动切割灯丝，确保喷嘴温度已冷却至50℃以下，并关闭打印机电源。
'''

[[block]]
key = "99f8ed361a5175c3"
origin = '''
### 拆卸
'''
translate = '''
### 拆卸
'''

[[block]]
key = "b27f0dbd2eefea84"
origin = '''
**步骤1-拆卸前壳体**
'''
translate = '''
**步骤1-拆卸前壳体**
'''

[[block]]
key = "6a310a06da8f2f6b"
origin = '''
断开风扇连接器，完全拆下前壳体总成。
'''
translate = '''
断开风扇连接器，完全拆下前壳体总成。
'''

[[block]]
key = "586eb8a9d5f8d263"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In2.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In2.webp').default} width="80%"/>
'''

[[block]]
key = "2e53294f64049465"
origin = '''
**步骤2-断开电缆**
'''
translate = '''
**步骤2-断开电缆**
'''

[[block]]
key = "c6f57776499eadb9"
origin = '''
断开hotend风扇和加热器连接器与板的连接，然后将电线从下图所示的夹子中滑出（用红色箭头指示），将其拆下。
'''
translate = '''
断开hotend风扇和加热器连接器与板的连接，然后将电线从下图所示的夹子中滑出（用红色箭头指示），将其拆下。
'''

[[block]]
key = "f1576578b6b5c979"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In3.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In3.webp').default} width="80%"/>
'''

[[block]]
key = "3f4164312c3f9533"
origin = '''
**步骤3-拆除热端组件**
'''
translate = '''
**步骤3-拆除热端组件**
'''

[[block]]
key = "7149df725bb3f750"
origin = '''
用H2.0六角扳手拆下2个螺钉，然后轻轻向下拉，继续拆下杆和组件。
'''
translate = '''
用H2.0六角扳手拆下2个螺钉，然后轻轻向下拉，继续拆下杆和组件。
'''

[[block]]
key = "fda382cd79232f13"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In4.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In4.webp').default} width="80%"/>
'''

[[block]]
key = "0d2a70253554f55a"
origin = '''
**步骤4–转移散热器风扇**
'''
translate = '''
**步骤4–转移散热器风扇**
'''

[[block]]
key = "9b9ae47aea8f48a6"
origin = '''
拧松固定风扇的两个螺钉以卸下散热器风扇。
'''
translate = '''
拧松固定风扇的两个螺钉以卸下散热器风扇。
'''

[[block]]
key = "f9036512636fccdf"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In5.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In5.webp').default} width="80%"/>
'''

[[block]]
key = "748da263b6a637ce"
origin = '''
并将其安装到您的全新Panda Revo上。
'''
translate = '''
并将其安装到您的全新Panda Revo上。
'''

[[block]]
key = "3a3fa943baa05cd7"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In6.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In6.webp').default} width="80%"/>
'''

[[block]]
key = "1c71e89c0fca3bfc"
origin = '''
确保根据图片将电缆放置在电缆导槽中，使HeaterCore套管的平面与散热器的侧面平行。
'''
translate = '''
确保根据图片将电缆放置在电缆导槽中，使HeaterCore套管的平面与散热器的侧面平行。
'''

[[block]]
key = "88df2f583e2b4b54"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In7.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In7.webp').default} width="80%"/>
'''

[[block]]
key = "24fbdbebc34c408b"
origin = '''
下图显示了“完整的热端组件”，供您参考。
'''
translate = '''
下图显示了“完整的热端组件”，供您参考。
'''

[[block]]
key = "a47da84445dacb6d"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In8.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In8.webp').default} width="80%"/>
'''

[[block]]
key = "f371817c5cf586d4"
origin = '''
### 装配
'''
translate = '''
### 装配
'''

[[block]]
key = "9648988fd6e23b44"
origin = '''
**步骤1-安装Panda Revo Hotend**
'''
translate = '''
**步骤1-安装Panda Revo Hotend**
'''

[[block]]
key = "42877170c333b54e"
origin = '''
将Panda Revo hotend组件插入挤出机，然后拧紧2个螺钉。
'''
translate = '''
将Panda Revo hotend组件插入挤出机，然后拧紧2个螺钉。
'''

[[block]]
key = "f6259c65c74ea17b"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In9.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In9.webp').default} width="80%"/>
'''

[[block]]
key = "b0079d7dc9ed4048"
origin = '''
:::info

确保使用H2.0六角扳手牢固地拧紧热端螺钉，避免过度拧紧。

:::
'''
translate = '''
:::info

确保使用H2.0六角扳手牢固地拧紧热端螺钉，避免过度拧紧。

:::
'''

[[block]]
key = "48d6723e93c1ec02"
origin = '''
**步骤2-连接热端电缆**
'''
translate = '''
**步骤2-连接热端电缆**
'''

[[block]]
key = "648e4e1dae7f6cf7"
origin = '''
将电线重新插入夹子（将连接器重新插入板上加热器的下部插槽和hotend风扇的中间插槽）。
'''
translate = '''
将电线重新插入夹子（将连接器重新插入板上加热器的下部插槽和hotend风扇的中间插槽）。
'''

[[block]]
key = "965be45ccce3603d"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In10.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In10.webp').default} width="80%"/>
'''

[[block]]
key = "30cb8de33a020df6"
origin = '''
**步骤3-安装前壳体**
'''
translate = '''
**步骤3-安装前壳体**
'''

[[block]]
key = "1f006e470cfa031c"
origin = '''
通过将风扇连接器重新连接到板上（最上面的插槽）来连接外壳组件，然后关闭前外壳组件盖。
'''
translate = '''
通过将风扇连接器重新连接到板上（最上面的插槽）来连接外壳组件，然后关闭前外壳组件盖。
'''

[[block]]
key = "6bd5099cc77fe136"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In11.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In11.webp').default} width="80%"/>
'''

[[block]]
key = "c08965dba86a562b"
origin = '''
## 如何验证
'''
translate = '''
## 如何验证
'''

[[block]]
key = "165021f4fd723002"
origin = '''
打开打印机电源并运行设备的**校准**过程。如果流程通过，则表示操作已成功。
'''
translate = '''
打开打印机电源并运行设备的**校准**过程。如果流程通过，则表示操作已成功。
'''

[[block]]
key = "758db2344f3333b2"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In12.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In12.webp').default} width="80%"/>
'''

[[block]]
key = "83dbc44623f35b50"
origin = '''
## 切片器设置
'''
translate = '''
## 切片器设置
'''

[[block]]
key = "da171281d484637d"
origin = '''
**喷嘴尺寸参数**
'''
translate = '''
**喷嘴尺寸参数**
'''

[[block]]
key = "7a049177cd28ac9b"
origin = '''
请在此处找到更详细的切片机设置指南:
https://e3d-online.zendesk.com/hc/en-us/articles/4777443097757-Filament-Starter-Settings
'''
translate = '''
请在此处找到更详细的切片机设置指南:
https://e3d-online.zendesk.com/hc/en-us/articles/4777443097757-Filament-Starter-Settings
'''

[[block]]
key = "25d63cbaaf0eea67"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_Nozzle.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_Nozzle.webp').default} width="80%"/>
'''

[[block]]
key = "d45a326cf3432125"
origin = '''
单击“编辑图标”并输入断料检测设置。
'''
translate = '''
单击“编辑图标”并输入断料检测设置。
'''

[[block]]
key = "167bb38a1a204bb2"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In13.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In13.webp').default} width="80%"/>
'''

[[block]]
key = "dc340fdc5aede0c7"
origin = '''
将“耗材”下的“最大体积速度”更改为35-40左右，具体取决于您使用的耗材。
'''
translate = '''
将“耗材”下的“最大体积速度”更改为35-40左右，具体取决于您使用的耗材。
'''

[[block]]
key = "b85dab84a92d62e4"
origin = '''
如果观察到挤出不足的迹象，请降低此数字，直到恢复打印质量。
'''
translate = '''
如果观察到挤出不足的迹象，请降低此数字，直到恢复打印质量。
'''

[[block]]
key = "3b19491bade0ae3c"
origin = '''
<ImageView src={require('./img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In14.webp').default} width="80%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/hotend/panda-revo/img/Panda_Revo_P1_Hotend/Panda_Revo_P1_Hotend_In14.webp').default} width="80%"/>
'''
