[metadata]

[[block]]
key = "1ecc15ff390b2db4"
origin = '''
---
sidebar_position: 3
---
'''
translate = '''
---
sidebar_position: 3
---
'''

[[block]]
key = "1fdf15bf295b28fb"
origin = '''
# SKR Pico 固件配置
'''
translate = '''
# SKR Pico 固件配置
'''

[[block]]
key = "c98f93097e9072ad"
origin = '''
SKR Pico 固件配置
'''
translate = '''
SKR Pico 固件配置
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "710dc62b3fd1deb6"
origin = '''
## 写入 Klipper 固件
'''
translate = '''
## 写入 Klipper 固件
'''

[[block]]
key = "5153a5e9cf31e79a"
origin = '''
SKR Pico 写入 Klipper 固件参考 [SKR 系列固件 (RP2040)](../skr-firmware-rp2040.md)
'''
translate = '''
SKR Pico 写入 Klipper 固件参考 [SKR 系列固件 (RP2040)](../skr-firmware-rp2040.md)
'''

[[block]]
key = "97a654915a067474"
origin = '''
## Klipper 配置文件参考
'''
translate = '''
## Klipper 配置文件参考
'''

[[block]]
key = "1dc5a8ccb8103778"
origin = '''
``` klipper_cfg title="printer.cfg"
[stepper_x]
step_pin: gpio11
dir_pin: !gpio10
enable_pin: !gpio12
microsteps: 16
rotation_distance: 40
endstop_pin: ^gpio4
'''
translate = '''
``` klipper_cfg title="printer.cfg"
[stepper_x]
step_pin: gpio11
dir_pin: !gpio10
enable_pin: !gpio12
microsteps: 16
rotation_distance: 40
endstop_pin: ^gpio4
'''

[[block]]
key = "9c6cbcdebf78edda"
origin = '''
# endstop_pin: tmc2209_stepper_x:virtual_endstop
'''
translate = '''
# endstop_pin: tmc2209_stepper_x:virtual_endstop
'''

[[block]]
key = "ffce4dd5a63fff48"
origin = '''
# homing_retract_dist: 0
'''
translate = '''
# homing_retract_dist: 0
'''

[[block]]
key = "80d7368d4139d0cf"
origin = '''
position_endstop: 0
position_max: 235
homing_speed: 50
'''
translate = '''
position_endstop: 0
position_max: 235
homing_speed: 50
'''

[[block]]
key = "fd6e708b1dbb4a65"
origin = '''
[tmc2209 stepper_x]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 0
run_current: 0.8
hold_current: 0.6
stealthchop_threshold: 999999
'''
translate = '''
[tmc2209 stepper_x]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 0
run_current: 0.8
hold_current: 0.6
stealthchop_threshold: 999999
'''

[[block]]
key = "f2a6b137ef8812b2"
origin = '''
# diag_pin: ^gpio4
'''
translate = '''
# diag_pin: ^gpio4
'''

[[block]]
key = "787fcdf3673d4c6a"
origin = '''
# driver_SGTHRS: 100
'''
translate = '''
# driver_SGTHRS: 100
'''

[[block]]
key = "9d953223822d54a5"
origin = '''
[stepper_y]
step_pin: gpio6
dir_pin: !gpio5
enable_pin: !gpio7
microsteps: 16
rotation_distance: 40
endstop_pin: ^gpio3
'''
translate = '''
[stepper_y]
step_pin: gpio6
dir_pin: !gpio5
enable_pin: !gpio7
microsteps: 16
rotation_distance: 40
endstop_pin: ^gpio3
'''

[[block]]
key = "9425bf61a9e12196"
origin = '''
# endstop_pin: tmc2209_stepper_y:virtual_endstop
'''
translate = '''
# endstop_pin: tmc2209_stepper_y:virtual_endstop
'''

[[block]]
key = "ffce4dd5a63fff48"
origin = '''
# homing_retract_dist: 0
'''
translate = '''
# homing_retract_dist: 0
'''

[[block]]
key = "80d7368d4139d0cf"
origin = '''
position_endstop: 0
position_max: 235
homing_speed: 50
'''
translate = '''
position_endstop: 0
position_max: 235
homing_speed: 50
'''

[[block]]
key = "a4fc7179a8244e95"
origin = '''
[tmc2209 stepper_y]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 2
run_current: 0.8
hold_current: 0.6
stealthchop_threshold: 999999
diag_pin: ^gpio3
driver_SGTHRS: 100
'''
translate = '''
[tmc2209 stepper_y]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 2
run_current: 0.8
hold_current: 0.6
stealthchop_threshold: 999999
diag_pin: ^gpio3
driver_SGTHRS: 100
'''

[[block]]
key = "ea21f7704bc41e12"
origin = '''
[stepper_z]
step_pin: gpio19
dir_pin: gpio28
enable_pin: !gpio2
microsteps: 16
rotation_distance: 8
'''
translate = '''
[stepper_z]
step_pin: gpio19
dir_pin: gpio28
enable_pin: !gpio2
microsteps: 16
rotation_distance: 8
'''

[[block]]
key = "051c595b1587fb3a"
origin = '''
# endstop_pin: ^gpio25
'''
translate = '''
# endstop_pin: ^gpio25
'''

[[block]]
key = "e1cfa6f9f6b92b86"
origin = '''
# position_endstop: 0
'''
translate = '''
# position_endstop: 0
'''

[[block]]
key = "5cd34246b954f8fa"
origin = '''
endstop_pin: probe:z_virtual_endstop
position_min: -2.0
position_max: 250
homing_speed: 12
'''
translate = '''
endstop_pin: probe:z_virtual_endstop
position_min: -2.0
position_max: 250
homing_speed: 12
'''

[[block]]
key = "ae548b3d20746495"
origin = '''
[tmc2209 stepper_z]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 1
run_current: 0.580
hold_current: 0.500
stealthchop_threshold: 999999
'''
translate = '''
[tmc2209 stepper_z]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 1
run_current: 0.580
hold_current: 0.500
stealthchop_threshold: 999999
'''

[[block]]
key = "d78f853de5572741"
origin = '''
[extruder]
step_pin: gpio14
dir_pin: !gpio13
enable_pin: !gpio15
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.4
filament_diameter: 1.75
heater_pin: gpio23
sensor_type: EPCOS 100K B57560G104F
sensor_pin: gpio27
control: pid
pid_Kp: 22.2
pid_Ki: 1.08
pid_Kd: 114
min_temp: 0
max_temp: 300
max_extrude_cross_section:2
'''
translate = '''
[extruder]
step_pin: gpio14
dir_pin: !gpio13
enable_pin: !gpio15
microsteps: 16
rotation_distance: 33.500
nozzle_diameter: 0.4
filament_diameter: 1.75
heater_pin: gpio23
sensor_type: EPCOS 100K B57560G104F
sensor_pin: gpio27
control: pid
pid_Kp: 22.2
pid_Ki: 1.08
pid_Kd: 114
min_temp: 0
max_temp: 300
max_extrude_cross_section:2
'''

[[block]]
key = "49bf88deea472742"
origin = '''
[tmc2209 extruder]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 3
run_current: 0.650
hold_current: 0.500
stealthchop_threshold: 999999
'''
translate = '''
[tmc2209 extruder]
uart_pin: gpio9
tx_pin: gpio8
uart_address: 3
run_current: 0.650
hold_current: 0.500
stealthchop_threshold: 999999
'''

[[block]]
key = "231ec2bbcf4efafd"
origin = '''
[filament_switch_sensor runout_sensor]
switch_pin: ^gpio16
pause_on_runout: True
'''
translate = '''
[filament_switch_sensor runout_sensor]
switch_pin: ^gpio16
pause_on_runout: True
'''

[[block]]
key = "547b46569f51b992"
origin = '''
# [filament_motion_sensor smart_sensor]
'''
translate = '''
# [filament_motion_sensor smart_sensor]
'''

[[block]]
key = "b0f8ef1a5ad03e1c"
origin = '''
# switch_pin: ^gpio16
'''
translate = '''
# switch_pin: ^gpio16
'''

[[block]]
key = "4babbcf08f68af08"
origin = '''
# detection_length: 2.5
'''
translate = '''
# detection_length: 2.5
'''

[[block]]
key = "3b67c78d2338a08e"
origin = '''
[heater_bed]
heater_pin: gpio21
sensor_type: EPCOS 100K B57560G104F
sensor_pin: gpio26
control: pid
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130
'''
translate = '''
[heater_bed]
heater_pin: gpio21
sensor_type: EPCOS 100K B57560G104F
sensor_pin: gpio26
control: pid
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 130
'''

[[block]]
key = "10d4ba031acea7d1"
origin = '''
[fan]
pin: gpio17
'''
translate = '''
[fan]
pin: gpio17
'''

[[block]]
key = "ea1a7df76fec8e99"
origin = '''
[heater_fan hotend_fan]
pin: gpio18
heater: extruder
heater_temp: 50.0
'''
translate = '''
[heater_fan hotend_fan]
pin: gpio18
heater: extruder
heater_temp: 50.0
'''

[[block]]
key = "97ab03b046d78a15"
origin = '''
[heater_fan controller_fan]
pin: gpio20
heater: heater_bed
heater_temp: 45.0
'''
translate = '''
[heater_fan controller_fan]
pin: gpio20
heater: heater_bed
heater_temp: 45.0
'''

[[block]]
key = "2f0b3fc53c25059c"
origin = '''
[mcu]
'''
translate = '''
[mcu]
'''

[[block]]
key = "ce9dda019463789c"
origin = '''
# serial: /dev/serial/by-id/usb-Klipper_rp2040_E66094A027854422-if00
'''
translate = '''
# serial: /dev/serial/by-id/usb-Klipper_rp2040_E66094A027854422-if00
'''

[[block]]
key = "38fd9c214683c818"
origin = '''
serial: /dev/ttyAMA0
restart_method: command
'''
translate = '''
serial: /dev/ttyAMA0
restart_method: command
'''

[[block]]
key = "1599772d4ba7adf1"
origin = '''
[printer]
kinematics: cartesian
max_velocity: 500
max_accel: 3000
max_z_velocity: 25
max_z_accel: 30
'''
translate = '''
[printer]
kinematics: cartesian
max_velocity: 500
max_accel: 3000
max_z_velocity: 25
max_z_accel: 30
'''

[[block]]
key = "6fd25d1dc939266d"
origin = '''
#[bltouch]
'''
translate = '''
#[bltouch]
'''

[[block]]
key = "ea773e74c9fdb4c4"
origin = '''
#sensor_pin: gpio22
'''
translate = '''
#sensor_pin: gpio22
'''

[[block]]
key = "dbab364b64357e44"
origin = '''
#control_pin: gpio29
'''
translate = '''
#control_pin: gpio29
'''

[[block]]
key = "e7476432116276c6"
origin = '''
[neopixel board_rgb]
pin: gpio24
chain_count: 1
color_order: GRB
initial_RED: 0.3
initial_GREEN: 0.3
initial_BLUE: 0.3
```
'''
translate = '''
[neopixel board_rgb]
pin: gpio24
chain_count: 1
color_order: GRB
initial_RED: 0.3
initial_GREEN: 0.3
initial_BLUE: 0.3
```
'''
