[metadata]

[[block]]
key = "f4f18beb18d54706"
origin = '''
---
sidebar_position: 4
description: Panda Bamboo Feeder 固件发布说明
---
'''
translate = '''
---
sidebar_position: 4
description: Panda Bamboo Feeder Firmware Release History
---
'''

[[block]]
key = "78e7975c9be8808a"
origin = '''
# Panda Bamboo Feeder 固件发布记录
'''
translate = '''
# Panda Bamboo Feeder Firmware Release History
'''

[[block]]
key = "27f2a384b8ff46e7"
origin = '''
### [01.00.00.01](https://github.com/bigtreetech/Panda_Bamboo_Feeder/blob/master/Firmware/01.00.00.01/panda_bambu_feeder-01.00.00.01.bin)
'''
translate = '''
### [01.00.00.01](https://github.com/bigtreetech/Panda_Bamboo_Feeder/blob/master/Firmware/01.00.00.01/panda_bambu_feeder-01.00.00.01.bin)
'''

[[block]]
key = "4df679ba8e3230b3"
origin = '''
- 首次发布的出厂固件
'''
translate = '''
- Initial factory release.
'''
