[metadata]

[[block]]
key = "6a41874291b4e873"
origin = '''
---
sidebar_position: 2
description: Panda Bamboo Feeder 硬件
---
'''
translate = '''
---
sidebar_position: 2
description: Panda Bamboo Feeder Hardware
---
'''

[[block]]
key = "044e85f841a682b9"
origin = '''
# Panda Bamboo Feeder 硬件
'''
translate = '''
# Panda Bamboo Feeder Hardware
'''

[[block]]
key = "801bfd96315251dd"
origin = '''
## 产品外观尺寸 {/* #p_size */}
'''
translate = '''
## Dimensions {/* #p_size */}
'''

[[block]]
key = "e35e4ac1abd08992"
origin = '''
:::info[模型]

[外尺寸参考模型](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Reference%20Cad)

:::
'''
translate = '''
:::info[models]

[reference models for external dimensions](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Reference%20Cad)

:::
'''

[[block]]
key = "38133fc95d51297d"
origin = '''
<ImageView src={require('./img/03size.webp').default} width="50%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/03size.webp').default} width="50%"/>
'''

[[block]]
key = "a70aaae5f2477312"
origin = '''
## 硬件接口
'''
translate = '''
## Hardware Interface
'''

[[block]]
key = "14e1addc43f70103"
origin = '''
<ImageView src={require('./img/hardware.webp').default} width="50%"/>
'''
translate = '''
<ImageView src={require('./img/hardware.webp').default} width="50%"/>
'''

[[block]]
key = "2b6ae49b5d7e7dc3"
origin = '''
- `退料键`: 用于退出耗材。
'''
translate = '''
- `Retract Button`: Used to retract/unload filament.
'''

[[block]]
key = "61cede637a8f949c"
origin = '''
- `进料键`: 用于将耗材送入打印机挤出机。
'''
translate = '''
- `Load Button`: Used to feed filament into the printer extruder.
'''

[[block]]
key = "bfd8b4af0ab713ac"
origin = '''
- `Type-C` 接口: 可通过USB进行恢复出厂设置。
'''
translate = '''
- `Type-C` Port: Can be used for factory resets via USB.
'''

[[block]]
key = "ebbaea1438438f69"
origin = '''
## 注意事项
'''
translate = '''
## Important Notes
'''

[[block]]
key = "edfacf31220dc933"
origin = '''
1. 最多三个熊猫喂竹器联动使用。
'''
translate = '''
1. Linkage Limit: A maximum of three Panda Bamboo Feeders can be linked and used together.
'''

[[block]]
key = "0bfd2bd929cbbbc9"
origin = '''
2. 如需同时使用多个熊猫喂竹器，位于最上方的喂竹器需要额外连接 DC 电源（需额外购买 24V/2.8A 电源适配器）。由于拓竹 AMS 接口供电能力有限，若同时为多个熊猫喂竹器供电，可能导致打印机运行异常。
'''
translate = '''
2. Power Requirements: When using multiple units, the topmost Feeder requires an external DC power supply (a 24V/2.8A power adapter must be purchased separately). Due to the limited power output of the Bambu Lab AMS interface, attempting to power multiple units through the printer simultaneously may cause system instability or malfunctions.
'''

[[block]]
key = "b1bd29e845aaa772"
origin = '''
3. 喂竹器可与 AMS 及 AMS 2 Pro 同时安装，但是不可同时使用， 通过AMS打印时请使用电源适配器上的开关，给喂竹器断电。
'''
translate = '''
3. AMS Compatibility: The Panda Bamboo Feeder can be installed alongside the AMS or AMS 2 Pro; however, they cannot be used simultaneously. When printing via the AMS, please use the switch on the power adapter to turn off the Panda Bamboo Feeder.
'''

[[block]]
key = "34a8fdfda6402503"
origin = '''
4. 喂竹器仅为连续打印续料以及耗材缓冲设计，无多色打印功能。
'''
translate = '''
4. Functionality Clarification: The Panda Bamboo Feeder is designed specifically for filament relay (auto-refill) and material buffering. It does not support multi-color printing.
'''

[[block]]
key = "1d4d588a0053c343"
origin = '''
## 安装指南
'''
translate = '''
## Installation Guide
'''

[[block]]
key = "1a7fae7189fc6fb7"
origin = '''
### P1/X1 系列机型
'''
translate = '''
### P1/X1 Series Models
'''

[[block]]
key = "4c0b6aeb6166e324"
origin = '''
1. 准备打印件
'''
translate = '''
1. Pre-print Required Components
'''

[[block]]
key = "5f97393cb96d9791"
origin = '''
    提前打印好需要的安装打印件,[点击此处下载。](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Mounting%20solution/Universal%20Mounting%20Bracket%20for%20PX%20series)
'''
translate = '''
    Ensure all required components are printed before starting the installation. The print files are available for download [here](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Mounting%20solution/Universal%20Mounting%20Bracket%20for%20PX%20series).
'''

[[block]]
key = "a9b50ed4f0534076"
origin = '''
    <ImageView src={require('./img/install00.webp').default} width="50%"/>
'''
translate = '''
    <ImageView src={require('./img/install00.webp').default} width="50%"/>
'''

[[block]]
key = "5d810db785dbbb91"
origin = '''
2. 安装固定挂扣
'''
translate = '''
2. Install the Mounting Tab
'''

[[block]]
key = "74c5c817140df721"
origin = '''
    使用包装内的螺丝，将打印好的“固定挂扣”固定在熊猫喂竹器的背部。
'''
translate = '''
    Use the screws in the package to secure the 3D printed Mounting Tab to the back of the Panda Bamboo Feeder.
'''

[[block]]
key = "6ad1e1e66b1ee1cb"
origin = '''
    <ImageView src={require('./img/install01.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install01.webp').default} width="30%"/>
'''

[[block]]
key = "89f8e8ea573c3392"
origin = '''
3. 安装快拆安装架
'''
translate = '''
3. Install the Quick-Release Mounting Grid
'''

[[block]]
key = "64ff258378b32f22"
origin = '''
    如图所示，将线缆穿过打印好的的“快拆安装架”并放入理线槽内（请确保 DC 接头和 MX3.0 接头方向正确）。
'''
translate = '''
    As shown in the diagram, thread the cable through the printed Quick-Release Mounting Grid and place it into the cable channel (ensure the DC head and MX3.0 are inserted correctly)
'''

[[block]]
key = "59b7881d2b5e1239"
origin = '''
    <ImageView src={require('./img/install02.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install02.webp').default} width="30%"/>
'''

[[block]]
key = "88f7493a3a6c5e9a"
origin = '''
    将打印的“理线锁扣”卡入快拆安装架中。
'''
translate = '''
    Snap the printed Cable Management Insert into the quick-release mounting grid.
'''

[[block]]
key = "15236054f0773536"
origin = '''
    <ImageView src={require('./img/install03.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install03.webp').default} width="30%"/>
'''

[[block]]
key = "6339e41c54f26d13"
origin = '''
    <ImageView src={require('./img/install04.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install04.webp').default} width="30%"/>
'''

[[block]]
key = "274894d535a6d179"
origin = '''
4. 安装底座
'''
translate = '''
4. Attach Base
'''

[[block]]
key = "ce6a3e0744363701"
origin = '''
    排好线后，将快拆安装架整体滑入打印好的“固定底座”中。
'''
translate = '''
    Once the cables are arranged, slide the entire quick-release mounting frame into the printed Fixed Base.
'''

[[block]]
key = "eaf80ed706af7050"
origin = '''
    <ImageView src={require('./img/install05.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install05.webp').default} width="30%"/>
'''

[[block]]
key = "1b2e040dff4bc3dc"
origin = '''
5. 固定喂竹器
'''
translate = '''
5. Mount the Feeder
'''

[[block]]
key = "642b9f59862b373f"
origin = '''
    通过固定挂扣将喂竹器卡入快拆安装架上，并接好线缆。
'''
translate = '''
    Snap the Panda Bamboo Feeder onto the quick-release mounting grid via the mounting tab and connect the cables.
'''

[[block]]
key = "d9e12c4f570d453b"
origin = '''
    <ImageView src={require('./img/install06.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install06.webp').default} width="30%"/>
'''

[[block]]
key = "451a5c7671eb2a81"
origin = '''
    使用随附的纳米双面胶粘贴于固定底座背面并移除离型纸，后将固定底座粘贴于机器合适的位置，如打印机侧面。
'''
translate = '''
    Apply the included double-sided tape to the back of the fixed base, remove the release liner, and stick the base to a suitable location, such as the side of the printer.
'''

[[block]]
key = "4b5e66cb36235828"
origin = '''
    <ImageView src={require('./img/install06.2.webp').default} width="20%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install06.2.webp').default} width="20%"/>
'''

[[block]]
key = "54c665911d399d51"
origin = '''
### Panda Perch 安装
'''
translate = '''
### Panda Perch Installation
'''

[[block]]
key = "e6701f75bb70ca23"
origin = '''
如果你有 BIQU Panda Perch，可在步骤二后通过固定挂扣将喂竹器卡入其侧面的六角孔中并用下图卡扣将挂扣牢牢固定在Panda Perch 内部。（亦需提前打印好固定挂扣，请[点击此处下载](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Mounting%20solution/Panda%20Perch%20H2D%20mounting%20bracket)）
'''
translate = '''
For BIQU Panda Perch users: Following Step 2 in P1/X1 Series Models, snap the Feeder into the hexagonal hole on the side of the Perch using the mounting tab. Secure the hook firmly from the inside with the printed clip shown below. [Click here to download the required print files](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Mounting%20solution/Panda%20Perch%20H2D%20mounting%20bracket).
'''

[[block]]
key = "3ee7a80607d7ace0"
origin = '''
<ImageView src={require('./img/install07.webp').default} width="30%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install07.webp').default} width="30%"/>
'''

[[block]]
key = "ea2ca30700ae661c"
origin = '''
<ImageView src={require('./img/install08.webp').default} width="30%"/>
'''
translate = '''
<ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/install08.webp').default} width="30%"/>
'''

[[block]]
key = "975333d274b508fa"
origin = '''
### A1 系列机型
'''
translate = '''
### A1 Series Models
'''

[[block]]
key = "4c0b6aeb6166e324"
origin = '''
1. 准备打印件
'''
translate = '''
1. Pre-print Required Components
'''

[[block]]
key = "abc8c1a01b574dc6"
origin = '''
    提前打印好需要的安装打印件：缠料检测删除， 安装支架。[点击此处下载模型文件](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Mounting%20solution/A1)。
'''
translate = '''
    Pre-print the Tangle Detection Delete Module and Mounting Bracket before installation. Download files [here](https://github.com/bigtreetech/Panda_Bamboo_Feeder/tree/master/3D%20Model/Mounting%20solution/A1).
'''

[[block]]
key = "6086b4245f2221ea"
origin = '''
    <ImageView src={require('./img/a1install00.01.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install00.01.webp').default} width="30%"/>
'''

[[block]]
key = "1618b05c4f7bf9cb"
origin = '''
    <ImageView src={require('./img/a1install00.02.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install00.02.webp').default} width="30%"/>
'''

[[block]]
key = "cd62463a83846255"
origin = '''
2. 开始安装
'''
translate = '''
2. Begin Installation
'''

[[block]]
key = "c1b667d9006a4ded"
origin = '''
    使用螺丝刀轻轻按压图示位置打开卡扣，切勿用力过猛以免损坏。
'''
translate = '''
    Open the buckle at the indicated position, being careful not to apply too much force to avoid damage.
'''

[[block]]
key = "80d6ca9f7bcb121c"
origin = '''
    <ImageView src={require('./img/a1install01.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install01.webp').default} width="30%"/>
'''

[[block]]
key = "5baa18c735427b2c"
origin = '''
    取下弹簧，并将图中圈出的固定环旋转 90 度以卸下。
'''
translate = '''
    Remove the spring and rotate the securing ring, circled in the image, by 90 degrees to detach it.
'''

[[block]]
key = "0744cdb8144e388e"
origin = '''
    <ImageView src={require('./img/a1install02.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install02.webp').default} width="30%"/>
'''

[[block]]
key = "d5cebb10bec62320"
origin = '''
    将缠料检测删除模块插入打印头。
'''
translate = '''
    Insert the Tangle Detection Delete Module into the print head.
'''

[[block]]
key = "61c719af7e4c4a6c"
origin = '''
    <ImageView src={require('./img/a1install03.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install03.webp').default} width="30%"/>
'''

[[block]]
key = "da913a0c8b1e49b6"
origin = '''
    重新装回刚才卸下的固定环。
'''
translate = '''
    Reinstall the securing ring that was previously removed.
'''

[[block]]
key = "621109fb08a77edf"
origin = '''
    <ImageView src={require('./img/a1install04.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install04.webp').default} width="30%"/>
'''

[[block]]
key = "d8856ea9d1453a23"
origin = '''
    注意安装方向：固定环上的突起部分必须朝向切刀侧。
'''
translate = '''
    Pay attention to the direction: the protrusion on the securing ring should face the cutter side.
'''

[[block]]
key = "dc56f2c7c6749847"
origin = '''
    <ImageView src={require('./img/a1install05.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install05.webp').default} width="30%"/>
'''

[[block]]
key = "1ed51b356d984d07"
origin = '''
    使用包装内的螺丝，将打印好的安装支架固定在喂竹器背部（请留意支架的安装方向，如图所示）。
'''
translate = '''
    Use the screws in the package to secure the printed Mounting Bracket to the back of the Panda Bamboo Feeder (pay attention to the orientation).
'''

[[block]]
key = "217ef5e9bb9377d7"
origin = '''
    <ImageView src={require('./img/a1install06.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('./img/a1install06.webp').default} width="30%"/>
'''

[[block]]
key = "113b2bebc6660dd7"
origin = '''
    如图所示，将其卡入耗材架的顶端。
'''
translate = '''
    As shown in the diagram, snap it into the top end of the filament spool holder.
'''

[[block]]
key = "407d031e44ea44b9"
origin = '''
    <ImageView src={require('./img/a1install07.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install07.webp').default} width="30%"/>
'''

[[block]]
key = "4a39235bbd7037e7"
origin = '''
    :::info

    进料管优化：如果您仅将喂竹器作为缓冲器使用，或直接从该料架供料，请将进料口的 PTFE 管更换为稍长一些的规格，以防止耗材缠绕。

    :::
'''
translate = '''
    :::info

    If you are only using the Panda Bamboo Feeder as a buffer, or if you plan to use filament directly from this filament spool holder, you will need to replace the PTFE tube at the Panda Bamboo Feeder filament inlet with a slightly longer one to prevent filament tangling.

    :::
'''

[[block]]
key = "1309566b0c9c4804"
origin = '''
    弧度提醒：注意，PTFE 管不宜过长或过短，应保持自然,顺滑的曲线弧度。
'''
translate = '''
    The PTFE tube should not be too long or too short. It should form a natural, smooth curve.
'''

[[block]]
key = "f9ed8aeb79391545"
origin = '''
    <ImageView src={require('./img/a1install08.webp').default} width="30%"/>
'''
translate = '''
    <ImageView src={require('@site/docs/panda-series/module/panda-bamboo-feeder/img/a1install08.webp').default} width="30%"/>
'''

[[block]]
key = "9214fd69fcb57caf"
origin = '''
### DIY定制支架
'''
translate = '''
### Custom DIY Mounting
'''

[[block]]
key = "aa811155d7477550"
origin = '''
可[参考此处](#p_size)下载外尺寸参考模型自行设计其他打印机的安装支架。
'''
translate = '''
[Refer to here](#p_size) to download the reference models for external dimensions and design your own custom mounting brackets for other printer models.
'''
