# this workflow use as pull request check 

name: wiki-PR-build-workflow

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build wiki
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        
      # init yarn 
    - name: Install dependencies
      run: yarn

      # build 
    - name: build wiki 
      run: yarn run build
