[metadata]

[[block]]
key = "af6b7d3f6046442f"
origin = '''
---
sidebar_position: 1
description: EZ 5160 Pro 驱动简介
---
'''
translate = '''
---
sidebar_position: 1
description: EZ 5160 Pro 驱动简介
---
'''

[[block]]
key = "fd6de86680027c0e"
origin = '''
# EZ 5160 Pro intro
'''
translate = '''
# EZ 5160 Pro intro
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "c53eab5258f79993"
origin = '''
<div class="div-table">

import EZ5160Pro from "./img/EZ5160_title.svg";

<EZ5160Pro class="right-image" width="30%" height="auto"/>
'''
translate = '''
<div class="div-table">

import EZ5160Pro from "@site/docs/accessories-docs/ez-series/ez-5160/img/EZ5160_title.svg";

<EZ5160Pro class="right-image" width="30%" height="auto"/>
'''

[[block]]
key = "f9c6f48ba32e89c6"
origin = '''
## 产品简介
'''
translate = '''
## 产品简介
'''

[[block]]
key = "594ea1dda0fa75d3"
origin = '''
EZ 5160 Pro 使用 TMC 5160 步进电机控制芯片，外置 MOSFET，最大电压可以达到 48V。
'''
translate = '''
EZ 5160 Pro 使用 TMC 5160 步进电机控制芯片，外置 MOSFET，最大电压可以达到 48V。
'''

[[block]]
key = "0a3a0b592b9c285e"
origin = '''
</div>
'''
translate = '''
</div>
'''

[[block]]
key = "5896f32630f9d24c"
origin = '''
## Specification
'''
translate = '''
## Specification
'''

[[block]]
key = "772d18c243042a87"
origin = '''
| EZ 5160 Pro | Specification      |
| ----------- | ------------------ |
| 外观尺寸    | $18.5 mm * 20 mm$  |
| 驱动芯片    | TMC5160-TA         |
| 输入电压    | 8V-48V             |
| 输出电流    | 2.5A RMS 3.0A Peak |
| 最大细分    | 256                |
| 工作模式    | SPI                |
'''
translate = '''
| EZ 5160 Pro | Specification      |
| ----------- | ------------------ |
| 外观尺寸    | $18.5 mm * 20 mm$  |
| 驱动芯片    | TMC5160-TA         |
| 输入电压    | 8V-48V             |
| 输出电流    | 2.5A RMS 3.0A Peak |
| 最大细分    | 256                |
| 工作模式    | SPI                |
'''
