[metadata]

[[block]]
key = "bc600d30da322f36"
origin = '''
---
sidebar_position: 2
description: EZ 5160 Pro 硬件
---
'''
translate = '''
---
sidebar_position: 2
description: EZ 5160 Pro 硬件
---
'''

[[block]]
key = "431bac781cb1e79e"
origin = '''
# EZ 5160 Pro Hardware
'''
translate = '''
# EZ 5160 Pro Hardware
'''

[[block]]
key = "42cb5c59eadfa74c"
origin = '''
{/* import lib start */}
'''
translate = '''
{/* import lib start */}
'''

[[block]]
key = "57c04bdb90a8f887"
origin = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''
translate = '''
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';
'''

[[block]]
key = "44d464596d54269c"
origin = '''
{/* import lib end */}
'''
translate = '''
{/* import lib end */}
'''

[[block]]
key = "e106c153eb196b41"
origin = '''
## 模型下载
'''
translate = '''
## 模型下载
'''

[[block]]
key = "412692a1f2338300"
origin = '''
:::info[3D 参考文件]

[bigtreetech/BIGTREETECH-EZ-Driver/BIGTREETECH EZ5160 Pro V1.0](https://github.com/bigtreetech/BIGTREETECH-EZ-Driver/tree/main/BIGTREETECH%20EZ5160%20Pro%20V1.0)

:::
'''
translate = '''
:::info[3D 参考文件]

[bigtreetech/BIGTREETECH-EZ-Driver/BIGTREETECH EZ5160 Pro V1.0](https://github.com/bigtreetech/BIGTREETECH-EZ-Driver/tree/main/BIGTREETECH%20EZ5160%20Pro%20V1.0)

:::
'''

[[block]]
key = "15e78c207b794d0b"
origin = '''
## EZ 系列引脚参考 
'''
translate = '''
## EZ 系列引脚参考 
'''

[[block]]
key = "c132fe3413707129"
origin = '''
[EZ 系列引脚说明](../ez-series-pin.md)
'''
translate = '''
[EZ 系列引脚说明](../ez-series-pin.md)
'''
